### ISSUE TITLE
System libraries loaded via namespace?

### ISSUE THREAD

**Issue by christianwoe** [rstudio/renv#1671] opened 2023-09-04 07:04 UTC
Dear all,

I recently started to having problems that sometimes older packages are loaded when opening projects with renv in RStudio and having a Rmd scipt open. The library version used may be versions from the underlying system. Restarting the R session helps, but not always in the first attempt. Closing the script open in the editor before opening seems to fix this as well, but only temporary it seems.

I just updated to renv 1.0.2 and did not observe this before.
Maybe something broke while updating?

Here is an example of the error when I try to load tidyverse in such a project:
```
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: NULL
  error: package or namespace load failed for ‘tidyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘cli’ 3.6.0 is already loaded, but >= 3.6.1 is require
```
In the renv library version 3.6.1 is installed, but the underlying system has version 3.6.0, which seems to be loaded in such cases (Did not check where the version comes from).
When I check `sessionInfo()` I find in `loaded via a namespace (and not attached):` somewhere `cli_3.6.0`

Any idea what could be the problem here?

Kind regards,
Christian

**Comment by kevinushey** [comment] 2023-09-05 23:30
Any chance you can share a reproducible example?

**Comment by kevinushey** [comment] 2023-11-13 21:44
> When I load an R project in Rstudio, and then immediately run sessionInfo(), I can see that Rstudio has loaded via namespace (not attached) packages that it detects are used in the project. Sounds helpful - but unfortunately it looks to my global user library to grab whatever version it can find there - and therefore ignores the renv project library that I would actually like to use.

Is this true even with the `renv` project library being automatically activated on startup?

**Comment by cath-parkinson** [comment] 2023-11-14 09:21
All automatic - the `renv` project library is activated by `source("renv/activate.R")` in `.Rprofile`. I'm using the recommended `renv` workflow (no adjustments or work arounds). My process to get the above error message - open project, restart R, then attempt to run my R shiny app.

**Comment by kevinushey** [comment] 2023-11-14 18:24
Thanks! We'll try to take a look at this soon.

**Comment by aowenson-imm** [comment] 2023-11-24 17:57
I too get this error, but in a simple R script not RStudio. And hopefully I have a simple reproducible example:
- a system install of R, with package `Matrix` version `1.5-4` in its subfolder `lib64/R/library/`
- add R paths to environment variables (e.g. `PATH`), **but crucially do not add** `lib64/R/library/`
- create a clean renv using standard workflow. I have confirmed that subfolder "lib64/R/library/" does not appear anywhere in `renv::diagnostics()`
- in the renv, install package "Seurat". renv sees the system install of `Matrix` is too old, but does not download a new version

Only workaround I have is manually-updating `Matrix` first.

**Comment by kevinushey** [comment] 2023-12-01 18:59
Thanks, I think I was able to reproduce. This was with R 4.2.3 on Ubuntu 22.04:

```
$ R

R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

- Project '/tmp/tmp.RuW14QFtQt' loaded. [renv 1.0.3]
> find.package("Matrix")
[1] "/home/kevin/.cache/R/renv/sandbox/R-4.2/aarch64-unknown-linux-gnu/e11edd0e/Matrix"
> packageVersion("Matrix")
[1] ‘1.5.3’
> renv::install("Seurat")
# Downloading packages -------------------------------------------------------
- Downloading Seurat from CRAN ...              OK [file is up to date]
- Downloading cowplot from CRAN ...             OK [file is up to date]
- Downloading ggplot2 from CRAN ...             OK [file is up to date]
- Downloading cli from CRAN ...                 OK [file is up to date]
- Downloading glue from CRAN ...                OK [file is up to date]
- Downloading gtable from CRAN ...              OK [file is up to date]
- Downloading lifecycle from CRAN ...           OK [file is up to date]
- Downloading rlang from CRAN ...               OK [file is up to date]
- Downloading isoband from CRAN ...             OK [file is up to date]
- Downloading scales from CRAN ...              OK [file is up to date]
- Downloading farver from CRAN ...              OK [file is up to date]
- Downloading labeling from CRAN ...            OK [file is up to date]
- Downloading munsell from CRAN ...             OK [file is up to date]
- Downloading colorspace from CRAN ...          OK [file is up to date]
- Downloading R6 from CRAN ...                  OK [file is up to date]
- Downloading RColorBrewer from CRAN ...        OK [file is up to date]
- Downloading viridisLite from CRAN ...         OK [file is up to date]
- Downloading tibble from CRAN ...              OK [file is up to date]
- Downloading fansi from CRAN ...               OK [file is up to date]
- Downloading magrittr from CRAN ...            OK [file is up to date]
- Downloading pillar from CRAN ...              OK [file is up to date]
- Downloading utf8 from CRAN ...                OK [file is up to date]
- Downloading vctrs from CRAN ...               OK [file is up to date]
- Downloading pkgconfig from CRAN ...           OK [file is up to date]
- Downloading withr from CRAN ...               OK [file is up to date]
- Downloading fastDummies from CRAN ...         OK [file is up to date]
- Downloading data.table from CRAN ...          OK [file is up to date]
- Downloading stringr from CRAN ...             OK [file is up to date]
- Downloading stringi from CRAN ...             OK [file is up to date]
- Downloading fitdistrplus from CRAN ...        OK [file is up to date]
- Downloading future from CRAN ...              OK [file is up to date]
- Downloading digest from CRAN ...              OK [file is up to date]
- Downloading globals from CRAN ...             OK [file is up to date]
- Downloading listenv from CRAN ...             OK [file is up to date]
- Downloading parallelly from CRAN ...          OK [file is up to date]
- Downloading future.apply from CRAN ...        OK [file is up to date]
- Downloading generics from CRAN ...            OK [file is up to date]
- Downloading ggrepel from CRAN ...             OK [file is up to date]
- Downloading Rcpp from CRAN ...                OK [file is up to date]
- Downloading ggridges from CRAN ...            OK [file is up to date]
- Downloading httr from CRAN ...                OK [file is up to date]
- Downloading curl from CRAN ...                OK [file is up to date]
- Downloading jsonlite from CRAN ...            OK [file is up to date]
- Downloading mime from CRAN ...                OK [file is up to date]
- Downloading openssl from CRAN ...             OK [file is up to date]
- Downloading askpass from CRAN ...             OK [file is up to date]
- Downloading sys from CRAN ...                 OK [file is up to date]
- Downloading ica from CRAN ...                 OK [file is up to date]
- Downloading igraph from CRAN ...              OK [file is up to date]
- Downloading cpp11 from CRAN ...               OK [file is up to date]
- Downloading irlba from CRAN ...               OK [file is up to date]
- Downloading leiden from CRAN ...              OK [file is up to date]
- Downloading reticulate from CRAN ...          OK [file is up to date]
- Downloading RcppTOML from CRAN ...            OK [file is up to date]
- Downloading here from CRAN ...                OK [file is up to date]
- Downloading rprojroot from CRAN ...           OK [file is up to date]
- Downloading png from CRAN ...                 OK [file is up to date]
- Downloading rappdirs from CRAN ...            OK [file is up to date]
- Downloading lmtest from CRAN ...              OK [file is up to date]
- Downloading zoo from CRAN ...                 OK [file is up to date]
- Downloading matrixStats from CRAN ...         OK [file is up to date]
- Downloading miniUI from CRAN ...              OK [file is up to date]
- Downloading shiny from CRAN ...               OK [file is up to date]
- Downloading httpuv from CRAN ...              OK [file is up to date]
- Downloading later from CRAN ...               OK [file is up to date]
- Downloading promises from CRAN ...            OK [file is up to date]
- Downloading fastmap from CRAN ...             OK [file is up to date]
- Downloading xtable from CRAN ...              OK [file is up to date]
- Downloading fontawesome from CRAN ...         OK [file is up to date]
- Downloading htmltools from CRAN ...           OK [file is up to date]
- Downloading base64enc from CRAN ...           OK [file is up to date]
- Downloading ellipsis from CRAN ...            OK [file is up to date]
- Downloading sourcetools from CRAN ...         OK [file is up to date]
- Downloading crayon from CRAN ...              OK [file is up to date]
- Downloading commonmark from CRAN ...          OK [file is up to date]
- Downloading bslib from CRAN ...               OK [file is up to date]
- Downloading cachem from CRAN ...              OK [file is up to date]
- Downloading jquerylib from CRAN ...           OK [file is up to date]
- Downloading memoise from CRAN ...             OK [file is up to date]
- Downloading sass from CRAN ...                OK [file is up to date]
- Downloading fs from CRAN ...                  OK [file is up to date]
- Downloading patchwork from CRAN ...           OK [file is up to date]
- Downloading pbapply from CRAN ...             OK [file is up to date]
- Downloading plotly from CRAN ...              OK [file is up to date]
- Downloading htmlwidgets from CRAN ...         OK [file is up to date]
- Downloading knitr from CRAN ...               OK [file is up to date]
- Downloading evaluate from CRAN ...            OK [file is up to date]
- Downloading highr from CRAN ...               OK [file is up to date]
- Downloading xfun from CRAN ...                OK [file is up to date]
- Downloading yaml from CRAN ...                OK [file is up to date]
- Downloading rmarkdown from CRAN ...           OK [file is up to date]
- Downloading tinytex from CRAN ...             OK [file is up to date]
- Downloading tidyr from CRAN ...               OK [file is up to date]
- Downloading dplyr from CRAN ...               OK [file is up to date]
- Downloading tidyselect from CRAN ...          OK [file is up to date]
- Downloading purrr from CRAN ...               OK [file is up to date]
- Downloading lazyeval from CRAN ...            OK [file is up to date]
- Downloading crosstalk from CRAN ...           OK [file is up to date]
- Downloading progressr from CRAN ...           OK [file is up to date]
- Downloading RANN from CRAN ...                OK [file is up to date]
- Downloading RcppAnnoy from CRAN ...           OK [file is up to date]
- Downloading RcppHNSW from CRAN ...            OK [file is up to date]
- Downloading ROCR from CRAN ...                OK [file is up to date]
- Downloading gplots from CRAN ...              OK [file is up to date]
- Downloading gtools from CRAN ...              OK [file is up to date]
- Downloading caTools from CRAN ...             OK [file is up to date]
- Downloading bitops from CRAN ...              OK [file is up to date]
- Downloading RSpectra from CRAN ...            OK [file is up to date]
- Downloading RcppEigen from CRAN ...           OK [file is up to date]
- Downloading Rtsne from CRAN ...               OK [file is up to date]
- Downloading scattermore from CRAN ...         OK [file is up to date]
- Downloading sctransform from CRAN ...         OK [file is up to date]
- Downloading reshape2 from CRAN ...            OK [file is up to date]
- Downloading plyr from CRAN ...                OK [file is up to date]
- Downloading gridExtra from CRAN ...           OK [file is up to date]
- Downloading RcppArmadillo from CRAN ...       OK [file is up to date]
- Downloading spatstat.explore from CRAN ...    OK [file is up to date]
- Downloading spatstat.data from CRAN ...       OK [file is up to date]
- Downloading spatstat.utils from CRAN ...      OK [file is up to date]
- Downloading spatstat.geom from CRAN ...       OK [file is up to date]
- Downloading deldir from CRAN ...              OK [file is up to date]
- Downloading polyclip from CRAN ...            OK [file is up to date]
- Downloading spatstat.random from CRAN ...     OK [file is up to date]
- Downloading spatstat.sparse from CRAN ...     OK [file is up to date]
- Downloading abind from CRAN ...               OK [file is up to date]
- Downloading tensor from CRAN ...              OK [file is up to date]
- Downloading goftest from CRAN ...             OK [file is up to date]
- Downloading uwot from CRAN ...                OK [file is up to date]
- Downloading FNN from CRAN ...                 OK [file is up to date]
- Downloading RcppProgress from CRAN ...        OK [file is up to date]
- Downloading dqrng from CRAN ...               OK [file is up to date]
- Downloading BH from CRAN ...                  OK [file is up to date]
- Downloading sitmo from CRAN ...               OK [file is up to date]
- Downloading SeuratObject from CRAN ...        OK [file is up to date]
- Downloading sp from CRAN ...                  OK [file is up to date]
- Downloading spam from CRAN ...                OK [file is up to date]
- Downloading dotCall64 from CRAN ...           OK [file is up to date]
Successfully downloaded 137 packages in 23 seconds.

The following package(s) will be installed:
- abind            [1.4-5]
- askpass          [1.2.0]
- base64enc        [0.1-3]
- BH               [1.81.0-1]
- bitops           [1.0-7]
- bslib            [0.6.1]
- cachem           [1.0.8]
- caTools          [1.18.2]
- cli              [3.6.1]
- colorspace       [2.1-0]
- commonmark       [1.9.0]
- cowplot          [1.1.1]
- cpp11            [0.4.6]
- crayon           [1.5.2]
- crosstalk        [1.2.1]
- curl             [5.1.0]
- data.table       [1.14.8]
- deldir           [2.0-2]
- digest           [0.6.33]
- dotCall64        [1.1-1]
- dplyr            [1.1.4]
- dqrng            [0.3.2]
- ellipsis         [0.3.2]
- evaluate         [0.23]
- fansi            [1.0.5]
- farver           [2.1.1]
- fastDummies      [1.7.3]
- fastmap          [1.1.1]
- fitdistrplus     [1.1-11]
- FNN              [1.1.3.2]
- fontawesome      [0.5.2]
- fs               [1.6.3]
- future           [1.33.0]
- future.apply     [1.11.0]
- generics         [0.1.3]
- ggplot2          [3.4.4]
- ggrepel          [0.9.4]
- ggridges         [0.5.4]
- globals          [0.16.2]
- glue             [1.6.2]
- goftest          [1.2-3]
- gplots           [3.1.3]
- gridExtra        [2.3]
- gtable           [0.3.4]
- gtools           [3.9.5]
- here             [1.0.1]
- highr            [0.10]
- htmltools        [0.5.7]
- htmlwidgets      [1.6.3]
- httpuv           [1.6.12]
- httr             [1.4.7]
- ica              [1.0-3]
- igraph           [1.5.1]
- irlba            [2.3.5.1]
- isoband          [0.2.7]
- jquerylib        [0.1.4]
- jsonlite         [1.8.7]
- knitr            [1.45]
- labeling         [0.4.3]
- later            [1.3.1]
- lazyeval         [0.2.2]
- leiden           [0.4.3.1]
- lifecycle        [1.0.4]
- listenv          [0.9.0]
- lmtest           [0.9-40]
- magrittr         [2.0.3]
- matrixStats      [1.1.0]
- memoise          [2.0.1]
- mime             [0.12]
- miniUI           [0.1.1.1]
- munsell          [0.5.0]
- openssl          [2.1.1]
- parallelly       [1.36.0]
- patchwork        [1.1.3]
- pbapply          [1.7-2]
- pillar           [1.9.0]
- pkgconfig        [2.0.3]
- plotly           [4.10.3]
- plyr             [1.8.9]
- png              [0.1-8]
- polyclip         [1.10-6]
- progressr        [0.14.0]
- promises         [1.2.1]
- purrr            [1.0.2]
- R6               [2.5.1]
- RANN             [2.6.1]
- rappdirs         [0.3.3]
- RColorBrewer     [1.1-3]
- Rcpp             [1.0.11]
- RcppAnnoy        [0.0.21]
- RcppArmadillo    [0.12.6.6.0]
- RcppEigen        [0.3.3.9.4]
- RcppHNSW         [0.5.0]
- RcppProgress     [0.4.2]
- RcppTOML         [0.2.2]
- reshape2         [1.4.4]
- reticulate       [1.34.0]
- rlang            [1.1.2]
- rmarkdown        [2.25]
- ROCR             [1.0-11]
- rprojroot        [2.0.4]
- RSpectra         [0.16-1]
- Rtsne            [0.16]
- sass             [0.4.7]
- scales           [1.3.0]
- scattermore      [1.2]
- sctransform      [0.4.1]
- Seurat           [5.0.1]
- SeuratObject     [5.0.1]
- shiny            [1.8.0]
- sitmo            [2.0.2]
- sourcetools      [0.1.7-1]
- sp               [2.1-2]
- spam             [2.10-0]
- spatstat.data    [3.0-3]
- spatstat.explore [3.2-5]
- spatstat.geom    [3.2-7]
- spatstat.random  [3.2-2]
- spatstat.sparse  [3.0-3]
- spatstat.utils   [3.0-4]
- stringi          [1.8.2]
- stringr          [1.5.1]
- sys              [3.4.2]
- tensor           [1.5]
- tibble           [3.2.1]
- tidyr            [1.3.0]
- tidyselect       [1.2.0]
- tinytex          [0.49]
- utf8             [1.2.4]
- uwot             [0.1.16]
- vctrs            [0.6.4]
- viridisLite      [0.4.2]
- withr            [2.5.2]
- xfun             [0.41]
- xtable           [1.8-4]
- yaml             [2.3.7]
- zoo              [1.8-12]
These packages will be installed into "/tmp/tmp.RuW14QFtQt/renv/library/R-4.2/aarch64-unknown-linux-gnu".

Do you want to proceed? [Y/n]: y

# Installing packages --------------------------------------------------------
- Installing cli ...                            OK [built from source and cached in 5.4s]
- Installing glue ...                           OK [built from source and cached in 1.0s]
- Installing rlang ...                          OK [built from source and cached in 7.7s]
- Installing lifecycle ...                      OK [built from source and cached in 1.0s]
- Installing gtable ...                         OK [built from source and cached in 1.2s]
- Installing isoband ...                        OK [built from source and cached in 2.9s]
- Installing farver ...                         OK [built from source and cached in 13s]
- Installing labeling ...                       OK [built from source and cached in 0.87s]
- Installing colorspace ...                     OK [built from source and cached in 3.8s]
- Installing munsell ...                        OK [built from source and cached in 0.9s]
- Installing R6 ...                             OK [built from source and cached in 0.76s]
- Installing RColorBrewer ...                   OK [built from source and cached in 0.91s]
- Installing viridisLite ...                    OK [built from source and cached in 0.65s]
- Installing scales ...                         OK [built from source and cached in 2.9s]
- Installing fansi ...                          OK [built from source and cached in 2.8s]
- Installing magrittr ...                       OK [built from source and cached in 0.89s]
- Installing utf8 ...                           OK [built from source and cached in 2.4s]
- Installing vctrs ...                          OK [built from source and cached in 12s]
- Installing pillar ...                         OK [built from source and cached in 2.2s]
- Installing pkgconfig ...                      OK [built from source and cached in 0.58s]
- Installing tibble ...                         OK [built from source and cached in 2.2s]
- Installing withr ...                          OK [built from source and cached in 0.93s]
- Installing ggplot2 ...                        OK [built from source and cached in 8.8s]
- Installing cowplot ...                        OK [built from source and cached in 2.2s]
- Installing data.table ...                     OK [built from source and cached in 14s]
- Installing stringi ...                        OK [built from source and cached in 38s]
- Installing stringr ...                        OK [built from source and cached in 1.6s]
- Installing fastDummies ...                    OK [built from source and cached in 0.75s]
- Installing fitdistrplus ...                   OK [built from source and cached in 4.9s]
- Installing digest ...                         OK [built from source and cached in 2.8s]
- Installing globals ...                        OK [built from source and cached in 1.1s]
- Installing listenv ...                        OK [built from source and cached in 1.0s]
- Installing parallelly ...                     OK [built from source and cached in 1.8s]
- Installing future ...                         OK [built from source and cached in 2.9s]
- Installing future.apply ...                   OK [built from source and cached in 1.4s]
- Installing generics ...                       OK [built from source and cached in 0.89s]
- Installing Rcpp ...                           OK [built from source and cached in 16s]
- Installing ggrepel ...                        OK [built from source and cached in 7.1s]
- Installing ggridges ...                       OK [built from source and cached in 2.6s]
- Installing curl ...                           OK [built from source and cached in 2.4s]
- Installing jsonlite ...                       OK [built from source and cached in 2.8s]
- Installing mime ...                           OK [built from source and cached in 0.77s]
- Installing sys ...                            OK [built from source and cached in 0.85s]
- Installing askpass ...                        OK [built from source and cached in 0.7s]
- Installing openssl ...                        OK [built from source and cached in 3.5s]
- Installing httr ...                           OK [built from source and cached in 2.2s]
- Installing ica ...                            OK [built from source and cached in 1.1s]
- Installing cpp11 ...                          OK [built from source and cached in 0.79s]
- Installing igraph ...                         OK [built from source and cached in 1.2m]
- Installing irlba ...                          OK [built from source and cached in 2.8s]
- Installing RcppTOML ...                       OK [built from source and cached in 6.9s]
- Installing rprojroot ...                      OK [built from source and cached in 0.82s]
- Installing here ...                           OK [built from source and cached in 0.7s]
- Installing png ...                            OK [built from source and cached in 0.86s]
- Installing rappdirs ...                       OK [built from source and cached in 0.74s]
- Installing reticulate ...                     OK [built from source and cached in 13s]
- Installing leiden ...                         OK [built from source and cached in 3.6s]
- Installing zoo ...                            OK [built from source and cached in 2.6s]
- Installing lmtest ...                         OK [built from source and cached in 1.6s]
- Installing matrixStats ...                    OK [built from source and cached in 7.0s]
- Installing later ...                          OK [built from source and cached in 9.9s]
- Installing fastmap ...                        OK [built from source and cached in 1.8s]
- Installing promises ...                       OK [built from source and cached in 5.5s]
- Installing httpuv ...                         OK [built from source and cached in 41s]
- Installing xtable ...                         OK [built from source and cached in 1.1s]
- Installing base64enc ...                      OK [built from source and cached in 0.8s]
- Installing ellipsis ...                       OK [built from source and cached in 0.93s]
- Installing htmltools ...                      OK [built from source and cached in 2.0s]
- Installing fontawesome ...                    OK [built from source and cached in 1.1s]
- Installing sourcetools ...                    OK [built from source and cached in 1.7s]
- Installing crayon ...                         OK [built from source and cached in 1.1s]
- Installing commonmark ...                     OK [built from source and cached in 6.3s]
- Installing cachem ...                         OK [built from source and cached in 1.1s]
- Installing jquerylib ...                      OK [built from source and cached in 0.89s]
- Installing memoise ...                        OK [built from source and cached in 0.94s]
- Installing fs ...                             OK [built from source and cached in 16s]
- Installing sass ...                           OK [built from source and cached in 59s]
- Installing bslib ...                          OK [built from source and cached in 3.2s]
- Installing shiny ...                          OK [built from source and cached in 11s]
- Installing miniUI ...                         OK [built from source and cached in 1.4s]
- Installing patchwork ...                      OK [built from source and cached in 2.5s]
- Installing pbapply ...                        OK [built from source and cached in 0.92s]
- Installing evaluate ...                       OK [built from source and cached in 0.86s]
- Installing xfun ...                           OK [built from source and cached in 1.8s]
- Installing highr ...                          OK [built from source and cached in 0.69s]
- Installing yaml ...                           OK [built from source and cached in 3.2s]
- Installing knitr ...                          OK [built from source and cached in 3.6s]
- Installing tinytex ...                        OK [built from source and cached in 0.95s]
- Installing rmarkdown ...                      OK [built from source and cached in 3.3s]
- Installing htmlwidgets ...                    OK [built from source and cached in 1.2s]
- Installing tidyselect ...                     OK [built from source and cached in 1.6s]
- Installing dplyr ...                          OK [built from source and cached in 6.2s]
- Installing purrr ...                          OK [built from source and cached in 2.6s]
- Installing tidyr ...                          OK [built from source and cached in 4.8s]
- Installing lazyeval ...                       OK [built from source and cached in 1.1s]
- Installing crosstalk ...                      OK [built from source and cached in 1.5s]
- Installing plotly ...                         OK [built from source and cached in 5.7s]
- Installing progressr ...                      OK [built from source and cached in 1.6s]
- Installing RANN ...                           OK [built from source and cached in 4.0s]
- Installing RcppAnnoy ...                      OK [built from source and cached in 16s]
- Installing RcppHNSW ...                       OK [built from source and cached in 12s]
- Installing gtools ...                         OK [built from source and cached in 1.3s]
- Installing bitops ...                         OK [built from source and cached in 0.77s]
- Installing caTools ...                        OK [built from source and cached in 1.6s]
- Installing gplots ...                         OK [built from source and cached in 2.1s]
- Installing ROCR ...                           OK [built from source and cached in 1.3s]
- Installing RcppEigen ...                      OK [built from source and cached in 26s]
- Installing RSpectra ...                       OK [built from source and cached in 1.1m]
- Installing Rtsne ...                          OK [built from source and cached in 11s]
- Installing scattermore ...                    OK [built from source and cached in 2.6s]
- Installing plyr ...                           OK [built from source and cached in 5.2s]
- Installing reshape2 ...                       OK [built from source and cached in 5.2s]
- Installing gridExtra ...                      OK [built from source and cached in 1.1s]
- Installing RcppArmadillo ...                  OK [built from source and cached in 13s]
- Installing sctransform ...                    OK [built from source and cached in 14s]
- Installing spatstat.utils ...                 OK [built from source and cached in 2.2s]
- Installing spatstat.data ...                  OK [built from source and cached in 3.1s]
- Installing deldir ...                         OK [built from source and cached in 2.0s]
- Installing polyclip ...                       OK [built from source and cached in 3.7s]
- Installing spatstat.geom ...                  OK [built from source and cached in 19s]
- Installing spatstat.random ...                OK [built from source and cached in 11s]
- Installing abind ...                          OK [built from source and cached in 0.78s]
- Installing tensor ...                         OK [built from source and cached in 0.58s]
- Installing spatstat.sparse ...                OK [built from source and cached in 3.0s]
- Installing goftest ...                        OK [built from source and cached in 0.81s]
- Installing spatstat.explore ...               OK [built from source and cached in 15s]
- Installing FNN ...                            OK [built from source and cached in 5.1s]
- Installing RcppProgress ...                   OK [built from source and cached in 0.47s]
- Installing BH ...                             OK [built from source and cached in 9.5s]
- Installing sitmo ...                          OK [built from source and cached in 7.5s]
- Installing dqrng ...                          OK [built from source and cached in 7.2s]
- Installing uwot ...                           OK [built from source and cached in 31s]
- Installing sp ...                             OK [built from source and cached in 5.4s]
- Installing dotCall64 ...                      OK [built from source and cached in 1.1s]
- Installing spam ...                           OK [built from source and cached in 13s]
- Installing SeuratObject ...                   FAILED
Error: Error installing package 'SeuratObject':
========================================

* installing *source* package ‘SeuratObject’ ...
** package ‘SeuratObject’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++14 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/Rcpp/include' -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/RcppEigen/include' -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++14 -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/Rcpp/include' -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/RcppEigen/include' -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong   -fpic  -g -O2  -c data_manipulation.cpp -o data_manipulation.o
gcc -I"/opt/R/4.2.3/lib/R/include" -DNDEBUG  -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/Rcpp/include' -I'/tmp/tmp.RuW14QFtQt/renv/staging/1/RcppEigen/include' -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong   -fpic  -g -O2  -c valid_pointer.c -o valid_pointer.o
g++ -std=gnu++14 -shared -L/opt/R/4.2.3/lib/R/lib -L/usr/local/lib -o SeuratObject.so RcppExports.o data_manipulation.o valid_pointer.o -L/opt/R/4.2.3/lib/R/lib -lR
installing to /tmp/tmp.RuW14QFtQt/renv/staging/1/00LOCK-SeuratObject/00new/SeuratObject/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘Matrix’ 1.5-3 is being loaded, but >= 1.6.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘SeuratObject’
* removing ‘/tmp/tmp.RuW14QFtQt/renv/staging/1/SeuratObject’
install of package 'SeuratObject' failed [error code 1]
Traceback (most recent calls last):
12: renv::install("Seurat")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
```

It looks like `renv` is failing to see that a newer version of Matrix is required by the dependent package `SeuratObject`.

**Comment by kevinushey** [comment] 2023-12-04 19:03
This should now be resolved in the latest development builds of `renv` -- you can install it with:

```
renv::install("rstudio/renv")
```

Please let me know if the issue persists for you with the latest versions. Thanks!

**Closed** 2023-12-04 19:02 UTC
Labels: bug

**Comment by aowenson-imm** [comment] 2023-12-05 14:39
I confirm this fixes my issue.

**Comment by kevinushey** [comment] 2023-12-05 20:52
Great, thanks for taking the time to confirm and report back!
