### ISSUE TITLE
[Feature Request] renv::init() in an old project suggests old package versions

### ISSUE THREAD

**Issue by AlbanSagouis** [rstudio/renv#1146] opened 2023-02-10 09:09 UTC
If i have a 10 year old project on my system and I try to run it today, chances are that it will not run because of R and package updates.

If I run `renv::init()` renv will detect the installed versions of R, it will go through the scripts and detect the packages used in the code and if some of these packages are already in the cache then the latest version number from the cache will be stored and finally, if a package used in the old project is not in the cache, the latest version will be found online.
I hope I got it more or less right until here.

The behaviour I'd like would rather be:
`renv` detects that the project is old or this is specified by the user
`renv` suggests two modes to the user: 
 - archival snapshot only. If the intent of the user is only to get a complete `renv.lock` for reproducibility with old package versions, I think a code solution from `renv` is a possibility.
 
 - working directory. If the user wants to actually run the code:
    `renv` suggests the most compatible R version or offers to try installing old packages on the current installed R version
    `renv` offers to download package versions from the time the project was last updated

I looked into packages [groundhog](https://cran.r-project.org/web/packages/groundhog/index.html) and [oldr](https://github.com/duckmayr/oldr) for suggesting old package versions based on a given date.

**Comment by kevinushey** [comment] 2023-02-10 22:16
Thanks for the feature request! We've been considering a similar interface; e.g. a way to snapshot a project using whatever R packages were current at some date in the past.

**Comment by hadley** [comment] 2023-05-01 19:10
Duplicate of #413

**Closed by hadley** 2023-05-01 19:10 UTC
Labels: feature, checkout :checkered_flag:
