### ISSUE TITLE
renv init/restore/hydrate seems to bring in in packages from ~/.Rprofile

### ISSUE THREAD

**Issue by zkamvar** [rstudio/renv#821] opened 2021-08-24 23:38 UTC
So, I'm trying to work on a way of encapsulating {renv} in a package and I'm running into a problem where package discovery will bring in packages that I have listed in my .Rprofile: https://github.com/zkamvar/config-files/blob/5ad9fe201f7c5085d0fdb0c4a3fcee9a378874dd/.Rprofile

I've tried several interventions, including running {callr} with `user_profile = FALSE` and setting the `R_PROFILE_USER` envvar to "nada", but so far nothing seems to work. Any advice?

<details>
<summary>Test project using the {cowsay} package</summary>

Here, I'm creating a project with one file that just says `cowsay::say('hello')`. 

The cowsay package has a total of three dependencies. That plus {renv} will come to five packages needed for the project. 

``` r
  tmp <- tempfile() 
  dir.create(tmp) 
  writeLines("cowsay::say('hello')", file.path(tmp, 'test.R')) 
  renv::init(tmp) 
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Resolving missing dependencies  ... 
#> Installing fortunes [1.5-4] ...
#>  OK [linked cache]
#> Installing rmsfact [0.0.3] ...
#>  OK [linked cache]
#> Installing cowsay [0.8.0] ...
#>  OK [linked cache]
#> Installing rlang [0.4.11] ...
#>  OK [linked cache]
#> Installing ellipsis [0.3.2] ...
#>  OK [linked cache]
#> Installing fansi [0.5.0] ...
#>  OK [linked cache]
#> Installing glue [1.4.2] ...
#>  OK [linked cache]
#> Installing lifecycle [1.0.0] ...
#>  OK [linked cache]
#> Installing magrittr [2.0.1] ...
#>  OK [linked cache]
#> Installing cli [3.0.1] ...
#>  OK [linked cache]
#> Installing utf8 [1.2.2] ...
#>  OK [linked cache]
#> Installing vctrs [0.3.8] ...
#>  OK [linked cache]
#> Installing pillar [1.6.2] ...
#>  OK [linked cache]
#> Installing pkgconfig [2.0.3] ...
#>  OK [linked cache]
#> Installing tibble [3.1.3] ...
#>  OK [linked cache]
#> Installing rematch2 [2.1.2] ...
#>  OK [linked cache]
#> Installing parsedate [1.2.1] ...
#>  OK [linked cache]
#> * Lockfile written to '/private/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T/RtmpmJCYJf/file51c87c42f338/renv.lock'.
  print(renv:::lockfile(file.path(tmp, "renv.lock"))) 
#> A lockfile containing 5 package records.
  rownames(installed.packages()) 
#>  [1] "cli"        "cowsay"     "crayon"     "ellipsis"   "fansi"     
#>  [6] "fortunes"   "glue"       "lifecycle"  "magrittr"   "parsedate" 
#> [11] "pillar"     "pkgconfig"  "rematch2"   "renv"       "rlang"     
#> [16] "rmsfact"    "tibble"     "utf8"       "vctrs"      "base"      
#> [21] "boot"       "class"      "cluster"    "codetools"  "compiler"  
#> [26] "datasets"   "foreign"    "graphics"   "grDevices"  "grid"      
#> [31] "KernSmooth" "lattice"    "MASS"       "Matrix"     "methods"   
#> [36] "mgcv"       "nlme"       "nnet"       "parallel"   "rpart"     
#> [41] "spatial"    "splines"    "stats"      "stats4"     "survival"  
#> [46] "tcltk"      "tools"      "utils"
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

</details>

**Comment by kevinushey** [comment] 2021-08-24 23:55
This is probably coming from here:

https://github.com/rstudio/renv/blob/cbe48ed782a08dda044094b902e6dc9ce5de5c3d/R/hydrate.R#L167-L171

The assumption here is that users running `renv` will most likely want the packages referenced in their `.Rprofile` to also be available in their `renv` projects, since that's the behaviour they would see by default.

Some things that probably need to be done here:

- Respect the `R_PROFILE_USER` environment variable,
- Consider disabling this if `config$user.profile()` is false,
- Provide some other mechanism for opting out.

**Comment by zkamvar** [comment] 2021-08-25 00:04
Fastest response in the west! :cowboy_hat_face: 

I think either of these solutions would help tremendously. FWIW, I initially assumed that `R_PROFILE_USER` would work because that's what `renv::init()` respects: https://github.com/rstudio/renv/blob/6b3a20efa633a0094560d1db22eae8ed1b84f6cf/R/load.R#L279-L281

**Comment by zkamvar** [comment] 2021-08-28 00:18
I just tested out 04e7373 and it appears to work!

``` r
    tmp <- tempfile() 
    dir.create(tmp) 
    writeLines('cowsay::say("hello")', file.path(tmp, "test.R")) 
    renv::init(tmp) 
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> * Resolving missing dependencies  ... 
#> Installing crayon [1.4.1] ...
#>  OK [linked cache]
#> Installing fortunes [1.5-4] ...
#>  OK [linked cache]
#> Installing rmsfact [0.0.3] ...
#>  OK [linked cache]
#> Installing cowsay [0.8.0] ...
#>  OK [linked cache]
#> * Lockfile written to '/private/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T/RtmpcMpSQz/filebf73a0658a2/renv.lock'.
```

<sup>Created on 2021-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       macOS Catalina 10.15.7      
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Los_Angeles         
#>  date     2021-08-27                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package     * version  date       lib
#>  R backports     1.2.1    <NA>       [?]
#>  R cli           3.0.1    <NA>       [?]
#>  P crayon        1.4.1    2021-02-08 [?]
#>  R digest        0.6.27   <NA>       [?]
#>  R ellipsis      0.3.2    <NA>       [?]
#>  R evaluate      0.14     <NA>       [?]
#>  R fansi         0.5.0    <NA>       [?]
#>  R fs            1.5.0    <NA>       [?]
#>  R glue          1.4.2    <NA>       [?]
#>  R highr         0.9      <NA>       [?]
#>  R htmltools     0.5.1.1  <NA>       [?]
#>  R knitr         1.33     <NA>       [?]
#>  R lifecycle     1.0.0    <NA>       [?]
#>  R magrittr      2.0.1    <NA>       [?]
#>  R pillar        1.6.2    <NA>       [?]
#>  R pkgconfig     2.0.3    <NA>       [?]
#>  R purrr         0.3.4    <NA>       [?]
#>  P renv          0.14.0-7 2021-08-27 [?]
#>  R reprex        2.0.1    <NA>       [?]
#>  R rlang         0.4.11   <NA>       [?]
#>  R rmarkdown     2.10     <NA>       [?]
#>  R sessioninfo   1.1.1    <NA>       [?]
#>  R stringi       1.7.4    <NA>       [?]
#>  R stringr       1.4.0    <NA>       [?]
#>  R styler        1.5.1    <NA>       [?]
#>  R tibble        3.1.3    <NA>       [?]
#>  R utf8          1.2.2    <NA>       [?]
#>  R vctrs         0.3.8    <NA>       [?]
#>  R withr         2.4.2    <NA>       [?]
#>  R xfun          0.25     <NA>       [?]
#>  R yaml          2.2.1    <NA>       [?]
#>  source                                  
#>  <NA>                                    
#>  <NA>                                    
#>  CRAN (R 4.1.0)                          
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  https://zkamvar.r-universe.dev (R 4.1.1)
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#>  <NA>                                    
#> 
#> [1] /private/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T/RtmpcMpSQz/filebf73a0658a2/renv/library/R-4.1/x86_64-apple-darwin17.0
#> [2] /private/var/folders/qd/dpdhfsz12wb3c7wz0xdm6dbm0000gn/T/RtmpcMpSQz/renv-system-library
#> 
#>  P ── Loaded and on-disk path mismatch.
#>  R ── Package was removed from disk.
```

</details>

**Comment by zkamvar** [comment] 2021-09-10 19:08
Would you like me to close this or would you prefer to wait until the release?

**Comment by kevinushey** [comment] 2021-09-10 19:11
Since you've confirmed this is resolved in the current development version, I think we can close this. Thanks!

**Closed** 2021-09-10 21:54 UTC
