### ISSUE TITLE
error opening archive

### ISSUE THREAD

**Issue by adamaltmejd** [rstudio/renv#954] opened 2022-03-02 13:42 UTC
I get the same error for any package - all failing to decompress. Both on linux and mac.

```
> renv::install("rstudio/renv")
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/b706c67eaf80e8c250d6c128c3bc4b80f65fd085' ...
	OK [downloaded 464 Kb in 1.4 secs]
/usr/bin/tar xf '~/Library/Application Support/renv/source/github/renv/renv_b706c67eaf80e8c250d6c128c3bc4b80f65fd085.tar.gz' -C '/var/folders/b9/b7hn3x0x7pv_1q51k3xmw6m40000gn/T//RtmparKLP0/renv-description-d72c4c0f5d2e' 'rstudio-renv-b706c67/DESCRIPTION'
================================================================================

tar: Error opening archive: Failed to open '~/Library/Application Support/renv/source/github/renv/renv_b706c67eaf80e8c250d6c128c3bc4b80f65fd085.tar.gz'
Error: error decompressing archive [error code 1]
In addition: Warning message:
could not retrieve available packages for url 'https://Rdatatable.gitlab.io/data.table/bin/macosx/big-sur-arm64/contrib/4.1'
Traceback (most recent calls last):
16: renv::install("rstudio/renv")
15: retrieve(names(remotes))
14: handler(package, renv_retrieve_impl(package))
13: renv_retrieve_impl(package)
12: renv_retrieve_github(record)
11: renv_retrieve_package(record, url, path)
10: renv_retrieve_successful(record, path)
 9: renv_description_read(path, subdir = subdir)
 8: filebacked(scope = "DESCRIPTION", path = path, callback = renv_description_read_impl,
        subdir = subdir, ...)
 7: callback(path, ...)
 6: renv_archive_decompress(path, files = file, exdir = exdir)
 5: renv_archive_decompress_tar(archive, files = files, exdir = exdir,
        ...)
 4: renv_tar_decompress(tar, archive = archive, files = files, exdir = exdir,
        ...)
 3: renv_system_exec(tar, args, action = "decompressing archive")
 2: stopf(fmt, action, status)
 1: stop(sprintf(fmt, ...), call. = call.)
```

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] colorout_1.2-2

loaded via a namespace (and not attached):
[1] compiler_4.1.2
```

Running `remotes::install_github("rstudio/renv")` works perfectly fine, and untarring the file directly works as well. I'm wondering if has to do with the "~" not being expanded when quoted?

**Comment by adamaltmejd** [comment] 2022-03-02 13:50
Actually seems this is solved by installing the latest version from github using remotes and then using it to add the latest github version to the renv cache by running `renv::install("rstudio/renv")`, and then from within the project where 15.3 is installed running `renv::install("rstudio/renv")` too.

**Comment by adamaltmejd** [comment] 2022-03-02 18:34
Run R in a folder where renv is not active. Install the latest github version with `remotes::install_github("rstudio/renv")`. Then install it again in the same folder with `renv::install("rstudio/renv")`, this will add it to the renv cache and now you can go back into your renv project and run `renv::install("rstudio/renv")` and it should work.

**Comment by kevinushey** [comment] 2022-03-02 19:29
Duplicate of https://github.com/rstudio/renv/issues/953 -- I'll try to submit a fixed version to CRAN ASAP.

**Closed by kevinushey** 2022-03-02 19:29 UTC

**Comment by adamaltmejd** [comment] 2022-03-02 20:32
Ah sorry I thought that error looked different. Thanks!
