### ISSUE TITLE
Project always 'out-of-sync' since renv 0.17.0

### ISSUE THREAD

**Issue by salim-b** [rstudio/renv#1159] opened 2023-03-08 11:50 UTC
After upgrading to renv 0.17.0, my renv project using `snapshot.type: explicit` keeps being "out-of-sync" without any apparent reason.

The `renv/activate.R` script (or `renv:::renv_project_synchronized_check()`) just emits the message:

```
* Project '~/REDACTED' loaded. [renv 0.17.0]
* The project is currently out-of-sync.
* Use `renv::status()` for more details.
```

- `renv::status(cache = TRUE)` doesn't show any issues (i.e. invisible output).

- `renv::snapshot(repos = "https://cloud.r-project.org")` says `* The lockfile is already up to date.`.

- `renv::restore()` says `* The library is already synchronized with the lockfile.`.

What's going wrong here?

**Comment by kevinushey** [comment] 2023-03-08 23:43
Can you share the output of:

```
str(renv::status())
```

That might give some pointers.

**Comment by kevinushey** [comment] 2023-03-09 03:52
Sorry, I think I've found the cause -- will have a fix shortly.

**Comment by kevinushey** [comment] 2023-03-16 04:53
Should be fixed in the development version of `renv` -- thanks for reporting!

**Closed by kevinushey** 2023-03-16 04:53 UTC
