### ISSUE TITLE
renv failing when restoring from a private repository

### ISSUE THREAD

**Issue by guillecarc** [rstudio/renv#466] opened 2020-06-30 14:17 UTC
I am restoring from my companie's server in Gitlab, and renv is not able to restore the package even though it has recorded correctly in the lock file.

This is  the error i get:

```Retrieving 'https://git.my-company.com/api/v4/projects/ds%2Ftdtwitter/repository/archive.tar.gz?sha=12345ac4c943234567f784fc39c2fb6588fa0f7f' ...
Warning message:
In (function (url, destfile, method, quiet = FALSE, mode = "w",  :
  cannot open URL 'Retrieving 'https://git.my-company.com/api/v4/projects/ds%2Ftdtwitter/repository/archive.tar.gz?sha=12345ac4c943234567f784fc39c2fb6588fa0f7f': HTTP status was '404 Not Found'

**Comment by kevinushey** [comment] 2020-06-30 20:11
Is the repository URL correct? Are you able to download the package if you copy + paste that URL into your browser (for example)?

The other possibility is that if your repository requires authentication for access, you may need to set `GITLAB_PAT`. This is discussed briefly at https://rstudio.github.io/renv/articles/renv.html#authentication.

**Comment by guillecarc** [comment] 2020-07-01 08:19
@kevinhankens Yes, i can download the package if i copy paste the url in my browser.

The repo has already been authenticated and registered in the renv.lock file.

**Comment by kevinushey** [comment] 2020-07-01 16:22
Can you also share the output of `sessionInfo()` for the copy of R running on that server? To double-check, are you sure the R session from which you're trying to restore does have access to that particular URL? 

It might help to know the output of:

```
url <- "https://git.my-company.com/api/v4/projects/ds%2Ftdtwitter/repository/archive.tar.gz?sha=12345ac4c943234567f784fc39c2fb6588fa0f7f"
download.file(url, destfile = tempfile())
download.file(url, destfile = tempfile(), method = "libcurl")
download.file(url, destfile = tempfile(), method = "curl")
```

to see if this affects all of R's downloaders, or just certain ones.

It'd also be helpful to have the full `renv::restore()` output just so I know exactly what you're seeing.

**Comment by dagola** [comment] 2020-11-03 10:47
I encountered the same issue and I think I the root cause is here
https://github.com/rstudio/renv/blob/5f181f6d0d5e9c803c278227b3bb230a9a0c87b2/R/remotes.R#L388
This seems to call the `download` function from `remotes` which allows to pass an `auth_token`. However, the `GITLAB_PAT` environment variable is not used here.

**Comment by kevinushey** [comment] 2020-11-03 16:27
This is where we read `GITLAB_PAT`:

https://github.com/rstudio/renv/blob/5f181f6d0d5e9c803c278227b3bb230a9a0c87b2/R/download.R#L469-L477

**Comment by jacobschwan** [comment] 2021-09-14 17:49
I just encountered a similar issue when trying to build a Docker container that required a package in a private GitLab repo. `remotes::install_gitlab("mygroup/private-package")` would install the package correctly, but both `renv::restore()` and `renv::install(gitlab::mygroup/private-package)` produced a similar 404 message as if the GITLAB_PAT token was not being passed.

My issue was resolved by installing `curl` as part of my container build.  It appears that the Private-Token header is not passed along correctly when other download methods are used.  Once `curl` was available, both `renv::install()` and `renv::restore()` successfully installed my private repository package.

**Comment by kevinushey** [comment] 2021-09-14 17:55
Indeed, if authentication is required, then `renv` requires the `curl` command line utility to be installed. There's probably some place I can make this more clear, but it is documented in the Downloads section of https://rstudio.github.io/renv/articles/renv.html.

**Comment by hadley** [comment] 2023-04-28 17:11
It sounds like the issues here are resolved, so I'm going to close. Please let me know if I've misunderstood.

**Closed by hadley** 2023-04-28 17:11 UTC
