### ISSUE TITLE
Errors when enumerating dependencies in files with special characters

### ISSUE THREAD

**Issue by netique** [rstudio/renv#421] opened 2020-05-10 18:13 UTC
When snapshoting the project after update to `renv 0.10.0` and `R 4.0`, `renv` discovered several errors in `*.Rmd` files. ALL of these refer to the "special" Czech characters, e.g. _"í", "á"_ etc. (see the caret at the very end in the log below pointing to what supposed to be "í", but it is rendered wrongly). When confirming to proceed, everything seems to run just OK and lockfile is created as usual. HOWEVER, when I reopen the project afterwards, bunch of critical and fatal errors occurs (see the screenschots below). This has to do something with encoding, but `*.Rmd` files are standard `UTF-8`. Only solution is to use `.renvignore` and simply ignore all `*.Rmd` files. Then, everything is OK.
```
Diagnostics Report -- renv [0.10.0]
===================================

# Session Info =======================
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Czech_Czechia.1250  LC_CTYPE=Czech_Czechia.1250   
[3] LC_MONETARY=Czech_Czechia.1250 LC_NUMERIC=C                  
[5] LC_TIME=Czech_Czechia.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0    packrat_0.5.0  renv_0.10.0   

# Project ============================
Project path: "C:/Users/netik/Desktop/socinov"

# Status =============================
WARNING: One or more problems were discovered while enumerating dependencies.

C:/Users/netik/Desktop/socinov/01_report.Rmd
--------------------------------------------

ERROR 1: C:/Users/netik/Desktop/socinov/01_report.Rmd:460:45: unexpected input
459: 
460: df_prosoc_w1 <- ifelse(df_sdq_comp2$KontrolnĂ­
                                                 ^
```
<img width="271" alt="1" src="https://user-images.githubusercontent.com/34926852/81507036-b71f9100-92fa-11ea-830d-7d667aa6eb6d.png">
<img width="354" alt="2" src="https://user-images.githubusercontent.com/34926852/81507041-bc7cdb80-92fa-11ea-8820-abaa64eec654.png">

**Comment by kevinushey** [comment] 2020-05-11 16:51
This looks like it might be due to a change in the behavior of R's parser in R 4.0.0. For example:

```
> x <- enc2utf8('á')
> parse(text = x, encoding = "UTF-8")
Error in parse(text = x, encoding = "UTF-8") : 
  <text>:1:1: unexpected input
1: Ã¡
    ^
```

It looks like the parser is incorrectly interpreting UTF-8 content as though it were in the native locale. :-/ I'll see if we need to find a way to work around this.

**Comment by kevinushey** [comment] 2020-05-11 17:03
For now, I don't have a better recommendation other than to stick with R 3.6.3 for the interim.

**Comment by kevinushey** [comment] 2020-05-19 23:44
I believe this is now fixed on master. You can install the development version of `renv` for a project with:

```
renv::upgrade(version = "master")
```

Please feel free to re-open if this doesn't resolve the issue for you.

**Comment by netique** [comment] 2020-05-21 08:40
I confirm it is fixed.

**Comment by kevinushey** [comment] 2020-05-21 18:19
That's unfortunate. :-/

Can you please provide a reproducible example then, so I can properly test?

**Comment by netique** [comment] 2020-05-26 16:30
Sorry for the delay. You can clone this repo with `Rproject` containing files `utf8.R` and `win1252.R` that both contains the problematic characters and are encoded with UTF-8 and WINDOWS-1252, respectively. Note that only UTF-8 encoded file throws an error when inspected by `renv`. Nearly all `renv` calls ends with the error. [https://github.com/netique/renv_reprex](https://github.com/netique/renv_reprex)

**Comment by kevinushey** [comment] 2020-05-26 21:39
Thank you! I believe I have a more appropriate fix for this on master now.

**Comment by netique** [comment] 2020-05-28 16:00
Seems OK!

**Comment by kevinushey** [comment] 2020-05-28 16:35
Phew! Glad to hear it.

**Closed by kevinushey** 2020-05-28 16:35 UTC

**Comment by lc822** [comment] 2020-06-08 08:39
Hi,

I am getting a similar problem.  When I run `renv::status()`, I get the following warnings:

```
WARNING: One or more problems were discovered while enumerating dependencies.

/Users/lucy/Documents/Rscripts/16-pyscenic_gene_regulatory_network.R
----------------------------------------------------------------------------------------------------------------------------------------------

ERROR 1: attempt to use zero-length variable name

/Users/lucy/Documents/Rscripts/tradeSeq.R
-------------------------------------------------------------------------------------------------------------------

ERROR 1: attempt to use zero-length variable name

Please see `?renv::dependencies` for more information.
```

I have updated renv to `0.10.0-46` but it didn't fix the problem.

Best,
Lucy

**Comment by kevinushey** [comment] 2020-06-09 01:11
@lc822: any chance you can share a reproducible example?

**Comment by lc822** [comment] 2020-08-01 12:33
Hi @kevinushey,

I'm not exactly sure what the issue was, but somehow I managed to fix it!

Best,
Lucy

**Comment by kevinushey** [comment] 2020-08-03 16:10
Phew, glad to hear it! Please feel free to file another issue if you encounter this again.

**Comment by daniel-conn17** [comment] 2020-08-31 21:42
Hi, I'm getting this error. I'm using renv 0.12.0-1. I'm not sure what other relevant information you need. I'm using R 4.0.1 on Ubuntu 18.0.04. I'm not sure where to begin with solving the issue.

**Comment by kevinushey** [comment] 2020-08-31 21:55
A reproducible example would be greatly appreciated.

**Comment by gacolitti** [comment] 2020-09-04 13:31
I was receiving a similar error:

```
WARNING: One or more problems were discovered while enumerating dependencies.

/Users/Gio/Documents/r/projects/test/Untitled.Rmd
-------------------------------------------------

ERROR 1: <text>:18:0: unexpected end of input
16: 
17: 
   ^

Please see `?renv::dependencies` for more information.
```

Upgrading to `renv` 0.12.0.3 did not solve the issue. But after ensuring the offending code chunk does not get evaluated using `eval=FALSE`, the error no longer appears.

This is the original Untitled.Rmd that causes the error:

````
---
title: test
---

```{r}
---
title: "Title"
---
```
````

After this is the one that doesn't cause an error:

````
---
title: test
---

```{r, eval=FALSE}
---
title: "Title"
---
```
````

**Comment by kevinushey** [comment] 2020-09-04 17:04
Well, that is expected -- the code you have in that chunk is not valid R code. So the diagnostics system has correctly informed you of an error in your document.

**Comment by kevinushey** [comment] 2020-09-08 16:52
Thanks, that makes the issue more clear. `renv` does not try to execute any code when scanning R code chunks for dependencies, so it does not "know" that the default chunk option is `eval = FALSE` here.

**Comment by FrsLry** [comment] 2021-04-13 08:26
I have the same problem than @gacolitti on my side. I have the following error message:

```
> renv::status()
WARNING: One or more problems were discovered while enumerating dependencies.

C:/Users/leroy/Desktop/phd/01-czech_bird_atlas.Rmd
--------------------------------------------------

ERROR 1: <text>:1964:0: unexpected end of input
1962: 
1963: 
     ^

Please see `?renv::dependencies` for more information.
```

Here again, the line indicated is not the correct one (I tried to erase the chunk at this line and it didn't change the error message). 

As you can see, I have a significant number of lines (almost 2000) and it is complicated to skim across my entire script to find the error. 

Can we know the precise line of the bug?

**Comment by netique** [comment] 2021-04-13 09:14
@FrsLry Have a look at the possible non-ASCII characters, which generally messes things up. E.g. https://pages.cs.wisc.edu/~markm/ascii.html

**Comment by FrsLry** [comment] 2021-04-13 09:34
Thanks. With the help of git, I managed to find the error (it was a pipe `%>%` that was misplaced). 

What is weird is that the script was running, the markdown was knitting but only renv was throwing me an warning. 

Moreover, the error was at line 909 , note 1962 (_i.e._ the last line of my .Rmd). Is there any logic to link the line indicated and the actual error line?

**Comment by kevinushey** [comment] 2021-04-13 16:10
A reproducible example would be helpful. It's possible we're somehow messing up the line count when scanning the associated code and reporting errors.

**Comment by FrsLry** [comment] 2021-04-13 17:25
Okay, I managed to reproduce the same error message in an easier way. 

The issue occurs when the options of a code chunk contains `echo = F, eval = F` (I tried with only `echo = F` and the line count is correct) and that there is an error in this code chunk. 

As it is unevaluated by Rmarkdown/knitr, there's no error message for this code chunk, but renv seems to take the code of chunk into account 

For instance, if you copy paste this script in a Rmarkdown file:

````
Load the libraries

```{r, warning=F, message=F}
library(abind)
library(ade4)
library(tidyverse)
```


Lorem ipsum dolor sit amet consectetur adipiscing elit potenti, proin hendrerit in nullam a nascetur fusce, tincidunt duis iaculis
 commodo dapibus sapien aenean. Molestie erat aliquam dictumst penatibus tellus eu a eros blandit, auctor tristique ante 
nulla vestibulum venenatis conubia lectus egestas, magna orci platea fermentum inceptos lacus nec vulputate. Nunc aliquet 
sociis tristique quam pretium urna rutrum cras molestie, tempus rhoncus dictum scelerisque dis egestas neque posuere.

Habitasse scelerisque parturient ac nostra varius malesuada purus ultrices, vel tristique sagittis lectus leo mauris arcu, luctus 
metus at augue duis conubia imperdiet. Iaculis integer fermentum nunc massa hendrerit convallis tortor mauris proin lacus, 
egestas congue bibendum purus lectus mattis velit id eu ligula, pretium mus sodales cras nec felis aptent quis molestie. 
Parturient curabitur diam urna class torquent ultricies suspendisse, ridiculus tempor vestibulum fringilla risus volutpat.


```{r, eval=F, echo=F}
## Code chunk unevaluetad with an error
starwars %>%
  filter(homeworld == "Tatooine") %>% 
  # ggplot()+
  # geom_density(aes(height))
```

Lorem ipsum dolor sit amet consectetur adipiscing elit potenti, proin hendrerit in nullam a nascetur fusce, tincidunt duis iaculis
 commodo dapibus sapien aenean. Molestie erat aliquam dictumst penatibus tellus eu a eros blandit, auctor tristique ante 
nulla vestibulum venenatis conubia lectus egestas, magna orci platea fermentum inceptos lacus nec vulputate. Nunc aliquet 
sociis tristique quam pretium urna rutrum cras molestie, tempus rhoncus dictum scelerisque dis egestas neque posuere.

Habitasse scelerisque parturient ac nostra varius malesuada purus ultrices, vel tristique sagittis lectus leo mauris arcu, luctus 
metus at augue duis conubia imperdiet. Iaculis integer fermentum nunc massa hendrerit convallis tortor mauris proin lacus, 
egestas congue bibendum purus lectus mattis velit id eu ligula, pretium mus sodales cras nec felis aptent quis molestie. 
Parturient curabitur diam urna class torquent ultricies suspendisse, ridiculus tempor vestibulum fringilla risus volutpat.

````

You should obtain a warning message with the wrong line count indicating the line 37 while the error is at line 24:

```
> renv::status()
WARNING: One or more problems were discovered while enumerating dependencies.

C:/Users/franc/Desktop/test/script.Rmd
--------------------------------------

ERROR 1: <text>:38:0: unexpected end of input
36: 
37: 
   ^

Please see `?renv::dependencies` for more information.
Do you want to proceed? [y/N]: 
```

This is not an important issue but maybe this post can help. 

PS: Thanks for this great package!

**Comment by kevinushey** [comment] 2021-04-13 18:04
Thank you! This is a bug in `renv` -- we should not be attempting to diagnose chunks marked with `eval=F`. As a workaround, you can set `eval=FALSE`; that is, avoid using the `F` short-hand. I'll get this fixed up soon.

**Comment by FrsLry** [comment] 2021-04-13 21:18
Oh yes, the option `eval=FALSE` solves the problem, good!
