### ISSUE TITLE
packages I can see in the lockfile appear missing when I run devtools::check()

### ISSUE THREAD

**Issue by ifeanyi588** [rstudio/renv#887] opened 2021-12-07 19:43 UTC
I am currently developing an R package called SAEplus. I recently switched from building this on one server to another server. The package was fully able to the tested, built and installed on the first server but ever since I switched servers I have not been able to test my package without error. I think the error is occurring because renv is loading from the system file and not the project lockfile. At the moment devtools::check() leads to the following error. Notice that the bestNormalize function which I can see in the lockfile appears to be missing because I only installed the package within the project.  

**-- Building ---------------------------------------------------------------------------- SAEplus --
Setting env vars:
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
---------------------------------------------------------------------------------------------------
v  checking for file 'D:\Ify\GitProjects\SAEplus/DESCRIPTION' (587ms)
-  preparing 'SAEplus': (4m 54s)
v  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
   Warning message:
   could not load renv from project "C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rbuild82078067e2d/SAEplus"; reloading previously-loaded renv 
-  installing *source* package 'SAEplus' ...
   ** using staged installation
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     there is no package called 'bestNormalize'
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package 'SAEplus'
-  removing 'C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rinst82077bd1458/SAEplus'
         -----------------------------------
   ERROR: package installation failed

Error: System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> * checking for file 'D:\Ify\GitProjects\SAEplus/DESCRIPTION' ... OK
E> * preparing 'SAEplus':
E> * checking DESCRIPTION meta-information ... OK
E> * installing the package to build vignettes
E>       -----------------------------------
E> Warning message:
E> could not load renv from project "C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rbuild82078067e2d/SAEplus"; reloading previously-loaded renv 
E> * installing *source* package 'SAEplus' ...
E> ** using staged installation
E> ** R
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
E>   there is no package called 'bestNormalize'
E> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
E> Execution halted
E> ERROR: lazy loading failed for package 'SAEplus'
E> * removing 'C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rinst82077bd1458/SAEplus'
E>       -----------------------------------
E> ERROR: package installation failed

 Stack trace:

 1. devtools::check(document = FALSE, check_dir = dirname(getwd()))
 2. withr::with_envvar(pkgbuild::compiler_flags(FALSE), action = "pre ...
 3. base:::force(code)
 4. pkgbuild::build(pkg$path, tempdir(), args = build_args, quiet = q ...
 5. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options ...
 6. base:::force(code)
 7. pkgbuild:::rcmd_build_tools(options$cmd, c(options$path, options$ ...
 8. pkgbuild:::with_build_tools(callr::rcmd_safe(..., env = env,  ...
 9. withr::with_path(rtools_path(), code)
 10. base:::force(code)
 11. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE,  ...
 12. callr:::run_r(options)
 13. base:::with(options, with_envvar(env, do.call(processx::run,  ...
 14. base:::with.default(options, with_envvar(env, do.call(processx::r ...
 15. base:::eval(substitute(expr), data, enclos = parent.frame())
 16. base:::eval(substitute(expr), data, enclos = parent.frame())
 17. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args  ...
 18. base:::force(code)
 19. base:::do.call(processx::run, c(list(bin, args = real_cmdargs,  ...
 20. (function (command = NULL, args = character(), error_on_status = TRUE,  ...
 21. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> * checking for file 'D:\Ify\GitProjects\SAEplus/DESCRIPTION' ... OK
E> * preparing 'SAEplus':
E> * checking DESCRIPTION meta-information ... OK
E> * installing the package to build vignettes
E>       -----------------------------------
E> Warning message:
E> could not load renv from project "C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rbuild82078067e2d/SAEplus"; reloading previously-loaded renv 
E> * installing *source* package 'SAEplus' ...
E> ** using staged installation
E> ** R
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
E>   there is no package called 'bestNormalize'
E> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
E> Execution halted
E> ERROR: lazy loading failed for package 'SAEplus'
E> * removing 'C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rinst82077bd1458/SAEplus'
E>       -----------------------------------
E> ERROR: package installation failed 

Execution halted

Exited with status 1.**

**Comment by ifeanyi588** [comment] 2021-12-07 19:47
Here is the results of .libPaths()
[1] "D:/Ify/GitProjects/SAEplus/renv/library/R-4.1/x86_64-w64-mingw32"     
[2] "C:/Users/wb559885/AppData/Local/Temp/9/RtmpAfsnCo/renv-system-library"

Below is the result of running renv::diagnostics. I just noticed actually that the cache path at the very bottom is different from the system path where it seems devtools::check() goes to pick up the packages: 
Diagnostics Report [renv 0.14.0]
================================

# Session Info =======================
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] SAEplus_0.1.0  testthat_3.0.4

loaded via a namespace (and not attached):
  [1] leafem_0.1.6        colorspace_2.0-2    ellipsis_0.3.2     
  [4] class_7.3-19        leaflet_2.0.4.1     rgdal_1.5-27       
  [7] rprojroot_2.0.2     base64enc_0.1-3     fs_1.5.0           
 [10] dichromat_2.0-0     quadmesh_0.5.0      rstudioapi_0.13    
 [13] proxy_0.4-26        listenv_0.8.0       remotes_2.4.0      
 [16] lubridate_1.8.0     prodlim_2019.11.13  fansi_0.5.0        
 [19] splines_4.1.2       codetools_0.2-18    doParallel_1.0.16  
 [22] cachem_1.0.5        pkgload_1.2.1       Formula_1.2-4      
 [25] jsonlite_1.7.2      reproj_0.4.2        tmaptools_3.1-1    
 [28] rgeos_0.5-8         png_0.1-7           hdm_0.3.1          
 [31] compiler_4.1.2      backports_1.4.0     assertthat_0.2.1   
 [34] Matrix_1.3-4        fastmap_1.1.0       cli_3.0.1          
 [37] htmltools_0.5.2     prettyunits_1.1.1   tools_4.1.2        
 [40] gtable_0.3.0        glue_1.4.2          dplyr_1.0.7        
 [43] doRNG_1.8.2         Rcpp_1.0.7          parallelMap_1.5.1  
 [46] raster_3.5-2        vctrs_0.3.8         countrycode_1.3.0  
 [49] iterators_1.0.13    leafsync_0.1.0      crosstalk_1.2.0    
 [52] timeDate_3043.102   lwgeom_0.2-8        bestNormalize_1.8.2
 [55] exactextractr_0.7.1 gower_0.2.2         globals_0.14.0     
 [58] ps_1.6.0            lifecycle_1.0.0     renv_0.14.0        
 [61] rngtools_1.5.2      devtools_2.4.2      XML_3.99-0.8       
 [64] future_1.23.0       terra_1.4-22        rgee_1.1.0         
 [67] MASS_7.3-54         scales_1.1.1        ipred_0.9-12       
 [70] hms_1.1.1           parallel_4.1.2      proj4_1.0-10.1     
 [73] RColorBrewer_1.1-2  BBmisc_1.11         memoise_2.0.0      
 [76] reticulate_1.22     ggplot2_3.3.5       dtplyr_1.1.0       
 [79] rpart_4.1-15        desc_1.3.0          foreach_1.5.1      
 [82] e1071_1.7-9         checkmate_2.0.0     butcher_0.1.5      
 [85] pkgbuild_1.2.0      osmextract_0.4.0    lava_1.6.10        
 [88] geometry_0.4.5      rlang_0.4.11        pkgconfig_2.0.3    
 [91] bitops_1.0-7        lattice_0.20-45     purrr_0.3.4        
 [94] sf_1.0-4            recipes_0.1.17      htmlwidgets_1.5.4  
 [97] processx_3.5.2      tidyselect_1.1.1    parallelly_1.29.0  
[100] magrittr_2.0.1      R6_2.5.0            generics_0.1.1     
[103] DBI_1.1.1           pillar_1.6.2        haven_2.4.3        
[106] withr_2.4.2         units_0.7-2         stars_0.5-4        
[109] nnet_7.3-16         survival_3.2-13     spex_0.7.1         
[112] abind_1.4-5         RCurl_1.98-1.5      sp_1.4-6           
[115] future.apply_1.8.1  tibble_3.1.3        crayon_1.4.1       
[118] KernSmooth_2.23-20  utf8_1.2.2          usethis_2.0.1      
[121] grid_4.1.2          tmap_3.3-2          data.table_1.14.0  
[124] callr_3.7.0         forcats_0.5.1       digest_0.6.27      
[127] classInt_0.4-3      tidyr_1.1.4         munsell_0.5.0      
[130] viridisLite_0.4.0   magic_1.5-9         sessioninfo_1.1.1  

# Project ============================
Project path: "D:/Ify/GitProjects/SAEplus"

# Status =============================
* The project is already synchronized with the lockfile.
The following package(s) are used in the project, but are not installed:

	emdi
	pacman
	readstata13
	rhdx
	spatstat
	tidyverse

Consider installing these packages, and then using `renv::snapshot()`
to record these packages in the lockfile.


# Packages ===========================
Traceback (most recent calls last):
4: renv::diagnostics()
3: tryCatch(reporter(project), error = renv_error_handler)
2: tryCatchList(expr, classes, parentenv, handlers)
1: tryCatchOne(expr, names, parentenv, handlers[[1L]])

# User Profile =======================
[no user profile detected]

# Settings ===========================
List of 8
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "packrat"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE
 $ vcs.ignore.local         : logi TRUE

# Options ============================
List of 8
 $ defaultPackages                     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method                : chr "wininet"
 $ download.file.extra                 : NULL
 $ install.packages.compile.from.source: chr "interactive"
 $ pkgType                             : chr "both"
 $ repos                               : Named chr "https://cloud.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent                        : logi TRUE
 $ renv.verbose                        : logi TRUE

# Environment Variables ==============
HOME                        = C:/Users/wb559885/Documents
LANG                        = <NA>
MAKE                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = D:/Ify/GitProjects/SAEplus/renv/library/R-4.1/x86_64-w64-mingw32;C:/Users/wb559885/AppData/Local/Temp/9/RtmpAfsnCo/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:/Users/wb559885/Documents/R/win-library/4.1
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = D:/Ify/GitProjects/SAEplus

# PATH ===============================
- C:\Users\wb559885\AppData\Local\r-miniconda\Scripts
- C:\Users\wb559885\AppData\Local\r-miniconda\envs\r-reticulate\Scripts
- C:\Users\wb559885\AppData\Local\r-miniconda\envs\r-reticulate
- C:\Program Files\R\R-4.1.2\bin\x64
- C:\python38-32\Scripts\
- C:\python38-32\
- C:\Windows\system32
- C:\Windows
- C:\Windows\System32\Wbem
- C:\Windows\System32\WindowsPowerShell\v1.0\
- C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
- C:\opscode\chef\bin
- c:\opscode\chef\embedded\bin
- C:\opscode\chef\bin
- c:\opscode\chef\embedded\bin
- C:\opscode\chef\bin\
- C:\Users\wb559885\AppData\Local\Google\Chrome\Application
- C:\python38-32\Scripts\
- C:\python38-32\
- C:\Windows\system32
- C:\Windows
- C:\Windows\System32\Wbem
- C:\Windows\System32\WindowsPowerShell\v1.0\
- C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
- C:\opscode\chef\bin
- c:\opscode\chef\embedded\bin
- C:\opscode\chef\bin
- c:\opscode\chef\embedded\bin
- C:\opscode\chef\bin\
- C:\Users\wb559885\AppData\Local\Programs\Git\cmd

# Cache ==============================
There are a total of 278 package(s) installed in the renv cache.
Cache path: "C:/Users/wb559885/AppData/Local/renv/cache/v5/R-4.1/x86_64-w64-mingw32"

**Comment by kevinushey** [comment] 2021-12-07 20:22
> Warning message:
could not load renv from project "C:/Users/wb559885/AppData/Local/Temp/9/Rtmp8Em4rx/Rbuild82078067e2d/SAEplus"; reloading previously-loaded renv

This is probably related. Did you call `renv::init()` or `renv::restore()` in the project on your other server?

**Comment by ifeanyi588** [comment] 2021-12-07 20:25
I use renv::restore(). Should be using renv::init()?

**Comment by ifeanyi588** [comment] 2021-12-07 20:48
I have now run renv::init() choosing the second option and it still failed.

**Comment by kevinushey** [comment] 2021-12-07 20:51
It also looks like the "packages" part of the diagnostics report failed to run; what do you see if you run:

```
renv:::renv_diagnostics_packages(getwd())
```

within the project directory? (presumedly you see an error; hopefully it provides something useful)

What happens if you try to call something like:

```
renv::load("/path/to/project")
```

from an R session outside of that `renv` project? Do you see any errors?

**Comment by ifeanyi588** [comment] 2021-12-07 21:34
Here is what I get from running renv::renv_diagnostics_packages(getwd())
# Packages ===========================
Error in data.frame(Library = renv_diagnostics_packages_version(libstate,  : 
  arguments imply differing number of rows: 294, 296

I get no errors with renv::load(getwd())
I get this:
* Project 'D:/Ify/GitProjects/SAEplus' loaded. [renv 0.14.0]

**Comment by kevinushey** [comment] 2021-12-07 22:28
Thanks -- if I understand correctly, this is the project you're working on:

https://github.com/SSA-Statistical-Team-Projects/SAEplus

I'm able to reproduce the issue you're seeing there; I'm going to try and investigate.

**Comment by kevinushey** [comment] 2021-12-07 23:58
I believe this issue should be resolved in the development version of `renv`. Would you be willing to try installing it with:

```
renv::upgrade(version = "main")
```

And then restart the R session, and try running `devtools::check()` again?

**Comment by vitalydrukeraz** [comment] 2021-12-16 19:55
I had a very similar issue and the latest dev version of renv fixed it - thank you. However - I'm seeing that my R_LIBS_USER and therefore .libPaths() now includes the R system library (which is read only at my work and seems to be causing problems). I'm not seeing anything explicitly about this in the `NEWS.md` file - is this deliberate behavior?

**Comment by kevinushey** [comment] 2021-12-17 00:15
Right, the sandbox is disabled by default now. See https://github.com/rstudio/renv/issues/614 for details, but the short version is that lots of administrators like to use programs that regularly clean out temporary directories, and sometimes those programs aren't very smart about not following symlinks / junctions (which means they end up deleting your R installation!)

**Comment by brianrepko** [comment] 2022-03-23 22:27
I'm just now adding vignettes to a package that is using R 3.6.1 and renv 0.12.5 and getting this same issue. `devtools::check()` and `devtools::build()` both fail with vignettes included but succeed with vignettes turned off but `devtools::build_vignettes()` works.

I'll look through the `NEWS.md` file to figure out which version I need to go to - been burned on this before though...

**Comment by brianrepko** [comment] 2022-03-23 22:40
upgraded to 0.15.3 and this seems to be working - now to run through a bunch of checks and review the changelog

**Closed** 2023-04-27 13:51 UTC
