### ISSUE TITLE
renv::install with explicit dependencies = Imports still installs Suggests 

### ISSUE THREAD

**Issue by Fuco1** [rstudio/renv#1336] opened 2023-05-25 10:06 UTC
If I'm trying to install "active project", suggested packages get installed even when I explicitly only request `Imports` to be installed.  The following code seems to be responsible:

```R
  # if this is the DESCRIPTION file for the active project, include
  # Suggests since they're often needed as well. such packages will be
  # considered development dependencies, except for package projects
  type <- "unknown"
  project <-
    project %||%
    renv_dependencies_state(key = "root") %||%
    renv_project_resolve()

  if (renv_path_same(file.path(project, "DESCRIPTION"), path)) {

    # collect profile-specific dependencies as well
    profile <- renv_profile_get()
    field <- if (length(profile))
      sprintf("Config/renv/profiles/%s/dependencies", profile)

    fields <- c(fields, "Suggests", field)
    type <- renv_description_type(desc = dcf)

  }
```

Basically, now if I want to really only install `Imports` packages, I have to use some renv internals to generate a list of the dependencies and then filter out the "dev" dependencies (also I have to set `Type` in description to some bogus value so the type is not "package").

This behaviour is very unintuitive and is not documented anywhere in `install`.  I think when user explicitly passes the dependencies parameter, nothing should happen to it and it should be taken as-is.

**Comment by Fuco1** [comment] 2023-05-25 13:48
Sorry, I should've been more precise.  In a `renv` project, call `renv::install("PATH_TO_PROJECT", dependencies = "Imports")`.  I'm not sure if path needs to be absolute or you can pass `"."` for current directory.  I always use absolute path.

I don't know if this is normal, but I'm trying to install the project "to itself" as a dependency so that my analysis script can require itself (instead of using `devtools::load_all()`. (the `R/` contains all the logic and then I have a top-level file `run.R` which loads the package with `library` and does the analysis)

**Comment by hadley** [comment] 2023-05-25 16:48
And presumably you have a `DESCRIPTION` file?

**Comment by hadley** [comment] 2023-05-25 17:43
If so, this is a duplicate of #1019

**Comment by kevinushey** [comment] 2023-05-25 18:46
I think this issue might be slightly different -- it sounds like the `dependencies` argument is being ignored in this scenario? The other issue relates to what dependencies are installed by default?

**Comment by hadley** [comment] 2023-05-25 19:06
@kevinushey good catch, I'll add a note to that issue.

**Comment by Fuco1** [comment] 2023-05-27 23:12
@kevinushey The argument is not ignored, but `Suggests` is appended to it as you see on this line `fields <- c(fields, "Suggests", field)`.

@hadley Yes, I do. Sorry for not mentioning it. Here's a version with unrelated stuff removed

```
Package: Redacted
Title: Redacted
Version: 1.0.0
Authors@R:
    person(given = "Matúš",
           family = "Goljer",
           role = c("aut", "cre"),
           email = "matus.goljer@somewhere")
Description: Redacted
License: Redacted
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Depends:
    R (>= 4.3.0)
LinkingTo:
    Rcpp,
    testthat
Imports:
    AzureAuth,
    AzureStor,
    Rcpp
Suggests:
    testthat (>= 3.0.0),
    testthatBdd,
    devtools
Config/testthat/edition: 3
```

**Closed** 2023-07-19 20:56 UTC
Labels: bug, install :basket:
