### ISSUE TITLE
Adding renv to existing project errors when using cache

### ISSUE THREAD

**Issue by al-obrien** [rstudio/renv#583] opened 2020-12-01 23:24 UTC
When initializing `renv` (i.e. `renv::init()`) on an existing project, and connecting it to a currently unused network cache location, the process fails with this error: **`Error: source file 'M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32/Rcpp' does not exist`**

At first I thought this was related to an 'unreachable' default cache location, so I ensured a folder location existed and pointed the project to it. When that didn't work, I removed sandboxing as was suggested elsewhere for similar errors. As such, my `.Renviron` file looks like:

```
RENV_PATHS_CACHE = 'N:/SHORT/NETWORK/PATH/TO/SHARED/CACHE/renv_cache'
 
# Remove the sandboxing
RENV_CONFIG_SANDBOX_ENABLED = FALSE
```

However, this did not work. Each time the `init()` failed I had to run `renv::deactivate()` and remove the 'renv' folder or the process would not reinitialize:

```
renv::init()
This project already has a private library. What would you like to do? 

1: Activate the project and use the existing library.
2: Re-initialize the project with a new library.
3: Abort project initialization.

Selection: 2
* Initializing project ...
Error: failed to create directory at path 'M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32'
In addition: Warning message:
In dir.create(rownames(info), recursive = TRUE) :
  cannot create dir 'M:/MY/NETWORK/PATH/PROJECT', reason 'Invalid argument'
```

After deactivating and removing 'renv', I would try `renv::init()` again and it would proceed a bit further, but eventually would hit an error for another package like below:

```
renv::init()
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... [69/177] Error: source file 'M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32/Rcpp' does not exist
```

Perhaps I am missing something simple for using a cache. The issue is resolved if I don't use the caching feature but I would like to use it if possible.

**Comment by kevinushey** [comment] 2020-12-02 00:05
One possibility: does your network path contain any special characters (e.g. spaces, quotes, other non-alphanumeric characters)?

Can you also confirm that you do indeed have write access to the `renv` cache directory? What happens if you try to manually create this directory from R, e.g.

```
dir.create("M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32", recursive = TRUE)
```

Can you also try running with:

```
options(warn = 2)
options(error = renv:::renv_error_handler_call())
renv::init()
```

as you may get more output from `renv` when the warning is emitted.

**Comment by al-obrien** [comment] 2020-12-02 01:09
To answer your questions:

- There are indeed spaces and dashes in the full path name (e.g. M:/folder/next folder/another - folder/); they are also quite long, this is why I have a mount point that is downstream of folders I do not typically use.
- I created the cache folder initially and I can see files in there from the ~60 successful attempts to copy into the cache location. I can also run `dir.create()` to create new folders in both the cache and Rproject locations. I suspect that error occurred because the directory already exists from the prior `init()`? *Maybe the path name is too long when trying to make the new directory?*

```
# Both succeed...
# Rproject location
dir.create('M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32/renv/library/R-3.6/x86_64-w64-mingw32/TEST', recursive = T)

# Cache location
dir.create('N:/SHORT/NETWORK/PATH/TO/SHARED/CACHE/renv_cache/v5/R-3.6/x86_64-w64-mingw32/TEST', recursive = T)
```

- I `deactivate`d and cleaned up the exiting 'renv' folders and tried again using the provided code. As in prior instances, it copied over many items (over 70 now) but failed on the 74th item. Before it said `Rcpp` was an issue (which now appears in the cache) but the new error I think is for `prettyunits`.

```
options(warn = 2)
options(error = renv:::renv_error_handler_call())
renv::init()
```
The detailed error that resulted is below. 
```
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... [74/177] Error in normalizePath(path.expand(path), winslash, mustWork) : 
  (converted from warning) path[1]="N:\LOCAT~1\CUSTOM~1\RENV_C~1\v5\R-3.6\X86_64~1\PRETTY~1\11~1.1\95EF91~1": The system cannot find the file specified
Traceback (most recent calls last):
18: renv::init()
17: hydrate(project = project, library = library)
16: renv_hydrate_link_packages(packages, library)
15: enumerate(packages, cache, library = library)
14: lapply(idx, callback)
13: FUN(X[[i]], ...)
12: f(n[[i]], x[[i]], ...)
11: f(...)
10: renv_file_copy(location, cache)
 9: renv_file_copy_dir(source, target)
 8: renv_tempfile(".renv-copy-", tmpdir = tmpdir)
 7: renv_file_normalize(path, winslash = "/")
 6: renv_path_normalize(dirname(path), winslash = winslash, mustWork = mustWork)
 5: normalizePath(path, winslash = winslash, mustWork = mustWork)
 4: .signalSimpleWarning("path[1]=\"N:\\LOCAT~1\\CUSTOM~1\\RENV_C~1\\v5\\R-3.6\\X86_64~1\\PRETTY~1\\11~1.1\\95EF91~1\": The system cannot find the file specified", 
        base::quote(normalizePath(path.expand(path), winslash, mustWork)))
 3: withRestarts({
        .Internal(.signalCondition(simpleWarning(msg, call), msg, 
            call))
        .Internal(.dfltWarn(msg, call))
    }, muffleWarning = function() NULL)
 2: withOneRestart(expr, restarts[[1L]])
 1: doWithOneRestart(return(expr), restart)
```

**Comment by kevinushey** [comment] 2020-12-02 18:45
Interesting -- thanks!

I wonder if the issue here then is that the attempting normalization of the short path fails:

```
 5: normalizePath(path, winslash = winslash, mustWork = mustWork)
 4: .signalSimpleWarning("path[1]=\"N:\\LOCAT~1\\CUSTOM~1\\RENV_C~1\\v5\\R-3.6\\X86_64~1\\PRETTY~1\\11~1.1\\95EF91~1\": The system cannot find the file specified", 
        base::quote(normalizePath(path.expand(path), winslash, mustWork)))
```

That is, when R tries to normalize that path, it produces a path that is too long?

Can you confirm the output of the following?

```
path <- "N:\\LOCAT~1\\CUSTOM~1\\RENV_C~1\\v5\\R-3.6\\X86_64~1\\PRETTY~1\\11~1.1\\95EF91~1"
file.exists(path)
dir.create(path, recursive = TRUE)
file.exists(path)
normalizePath(path)
```

I wonder if the use of `normalizePath()` here is the culprit. Perhaps we should avoid normalizing paths in some cases, to avoid generating overly-long paths?

FWIW, the maximum path length handled on Windows (by default) is 260 characters. Can you confirm is the normalized path length (the true location of the cache) is indeed longer than that?

**Comment by al-obrien** [comment] 2020-12-02 19:53
### For the first test:
I had to start with a new initialization due to how I was testing earlier.
```
options(warn = 2)
options(error = renv:::renv_error_handler_call())
renv::init()
```
The result, as we expect was similar to before:
```
* Initializing project ...
* Discovering package dependencies ... Done!
* Copying packages into the cache ... [79/177] Error: source file 'M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32/viridis' does not exist
Traceback (most recent calls last):
16: renv::init()
15: hydrate(project = project, library = library)
14: renv_hydrate_link_packages(packages, library)
13: enumerate(packages, cache, library = library)
12: lapply(idx, callback)
11: FUN(X[[i]], ...)
10: f(n[[i]], x[[i]], ...)
 9: f(...)
 8: renv_file_link(cache, target, overwrite = TRUE)
 7: renv_file_copy(source, target, overwrite = overwrite)
 6: renv_file_preface(source, target, overwrite)
 5: renv_file_backup(target)
 4: renv_file_move(path, tempfile)
 3: renv_file_preface(source, target, overwrite)
 2: stopf("source file '%s' does not exist", source)
 1: stop(sprintf(fmt, ...), call. = call.)
```

I then ran this code with the results below:
```
path <- "M:/MY/NETWORK/PATH/PROJECT/renv/library/R-3.6/x86_64-w64-mingw32/viridis"
file.exists(path)
[1] FALSE
dir.create(path, recursive = TRUE)
file.exists(path)
[1] TRUE
normalizePath(path)
"M:\\MY\\NETWORK\\PATH\\PROJECT\\renv\\library\\R-3.6\\x86_64-w64-mingw32\\viridis"
```


### For the second:
From the top of the file tree for the network drive, it is:
- ~200 characters to the project renv\renv\library\R-3.6\x86_64-w64-mingw32
- ~180 characters to the cache directory

However, I (usually) try to use a mount point downstream from the top of the file tree to avoid the character max limit. As such, I tend to access my projects through a file path typically of a length <100 characters: eg) N:/Myprojects/R/work-report/renv/...  instead of M:/VERY/VERY/VERY/VERY/SUPER/LONG/FOLDER/PATH/TO/Myprojects/R/work-report/renv/...

**Comment by hadley** [comment] 2023-04-28 12:54
@al-obrien is this still a problem for you?

**Comment by hadley** [comment] 2023-04-28 14:02
Thanks, in that case I'll close this issue. The issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2023-04-28 14:02 UTC
Labels: reprex
