### ISSUE TITLE
"Fatal error: cannot create 'R_TempDir'" when using renv with Rscript in LSF batch jobs

### ISSUE THREAD

**Issue by brettellebi** [rstudio/renv#680] opened 2021-03-12 10:40 UTC
Hi,

Thanks for creating this awesome package.

When I run the following on our RHEL cluster through LSF batch job submission:

```r
Rscript --no-save --no-restore --no-environ --no-site-file $script $arg1 $arg2
```
I get the following error **for ~3% of jobs**:

```r
Fatal error: cannot create 'R_TempDir'
```

This occurs when I call R from either a conda environment or a Singularity container.

Any suggestions for a workaround?

Cheers,

Ian

**Comment by kevinushey** [comment] 2021-03-12 17:25
Sorry, I don't have any great ideas. Maybe set `TMP` or `TEMPDIR` to a different, more reliable temporary working directory? Or just have your job launcher detect this specific error and attempt to re-run the job if it fails in this way?

**Comment by kevinushey** [comment] 2021-03-16 02:05
I'm going to close this because I think the issue is most likely independent of `renv` -- that is, I imagine you can still reproduce this issue even if you're not using `renv` when running your R scripts. If you find this is not the case, please re-open with a reproducible example.

**Closed by kevinushey** 2021-03-16 02:05 UTC
