### ISSUE TITLE
Failed to download CRAN packages

### ISSUE THREAD

**Issue by fernandomayer** [rstudio/renv#333] opened 2020-02-06 02:39 UTC
Hi,

I'm trying to restore a very simple (example) project, available [here](https://github.com/fernandomayer/reco/blob/master/misc/renv_basico.zip). This project contains:

- `renv/activate.R`
- `.Rprofile`
- `renv.lock`
- `script.R`

All files (except `script.R`) were generated after a `renv::snapshot()`. So I was trying to restore this project in another machine, but when I run R in `renv_basico` directory I get this:

```
Failed to find installation of renv -- attempting to bootstrap...
* Downloading renv 0.9.2-33 ... Done!
* Installing renv 0.9.2-33 ... Done!
Successfully installed and loaded renv 0.9.2-33.
* Project '~/Downloads/renv_basico' loaded. [renv 0.9.2-33]
```

The latest version of renv was already installed, but that's not the issue. When I run `renv::restore()` I get this:

```
> renv::restore()
The following package(s) will be updated:

# CRAN ===============================
- mvtnorm   [* -> 1.0-12]

# GitHub =============================
- renv      [ref: 0.9.2-33 -> master]

Do you want to proceed? [y/N]: y
Retrieving 'https://api.github.com/repos/rstudio/renv/tarball/137a85feb93f6ad7a90379e3e6b119acc2d01f02' ...
	OK [downloaded 202.7 Kb in 0.7 secs]
Retrieving 'http://cran-r.c3sl.ufpr.br/src/contrib/Archive/mvtnorm/mvtnorm_1.0-12.tar.gz' ...
Error: failed to retrieve package 'mvtnorm'
In addition: Warning messages:
1: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/home/mayer/tmp/RtmpKxJz7L/renv-tempdir-13d13341b042/renv-download-config-13d16763aacc' 2>&1' had status 22
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
3: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/home/mayer/tmp/RtmpKxJz7L/renv-tempdir-13d13341b042/renv-download-config-13d11ccb761c' 2>&1' had status 22
4: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 Not Found
Traceback (most recent calls first):
8: renv::restore()
7: renv_restore_run_actions(project, diff, current, lockfile)
6: renv_retrieve(packages)
5: handler(package, renv_retrieve_impl(package))
4: renv_retrieve_impl(package)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
```

It seem like renv is trying to install a package (`mvtnorm` in this case) from package Archive, but if you go to http://cran-r.c3sl.ufpr.br/src/contrib/Archive/mvtnorm the latest version really isn't there. This happens with other packages and other mirrors as well.

So, is renv looking at the wrong place or am I doing something wrong?

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.9.0
LAPACK: /usr/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] renv_0.9.2-33   lattice_0.20-38

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    grid_3.6.2   
```

Thanks.

**Comment by kevinushey** [comment] 2020-02-06 05:30
`renv` tries to make sure that it's installed in the project's own private library (as opposed to just loaded from your user library or elsewhere), hence why you see the initial bootstrapping  step.

Otherwise, the behavior you're seeing is, I think, a bug in `renv` caused by projects containing un-named repositories. That is, you probably set your R repositories with something like:

```
options(repos = "http://cran-r.c3sl.ufpr.br")
```

whereas `renv` currently requires them to be named, e.g.

```
options(repos = c(CRAN = "http://cran-r.c3sl.ufpr.br"))
```

I'd recommend changing the repositories to ensure that they're named, and then calling `renv::snapshot()` to update the lockfile. Let me know if that makes a difference.

**Comment by kevinushey** [comment] 2020-02-06 17:25
Should be fixed up on master. Please feel free to re-open if you're still having trouble. Thanks for reporting!

**Closed** 2020-02-06 17:25 UTC

**Comment by fernandomayer** [comment] 2020-02-07 00:31
> renv tries to make sure that it's installed in the project's own private library (as opposed to just loaded from your user library or elsewhere), hence why you see the initial bootstrapping step.

Ah ok, fair enough.

> Otherwise, the behavior you're seeing is, I think, a bug in renv caused by projects containing un-named repositories.

That's exactly how it was. Changing to

```
options(repos = c(CRAN = "http://cran-r.c3sl.ufpr.br"))
```

solved the problem. Anyway I'll update and test the new version.

Thank you very much for this package!
