### ISSUE TITLE
renv sometimes fails to restore project library

### ISSUE THREAD

**Issue by karawoo** [rstudio/renv#196] opened 2019-09-23 22:31 UTC
When I clone a project from GitHub onto our Shiny Pro server, `renv::restore()` fails to restore the project's dependencies to the project library in `renv/library/`. I don't experience this issue when I clone the project to a new location on my laptop, however.

Steps to reproduce (though seems to be system-dependent):

```
$ git clone https://github.com/Sage-Bionetworks/dccvalidator.git && cd dccvalidator
$ R
```

The R session finds the project's .Rprofile, and it installs renv and claims to load the project. This is what I see on startup:

```r
#> Failed to find installation of renv -- attempting to bootstrap...
#> * Downloading renv 0.7.0-99 ... Done!
#> * Installing renv 0.7.0-99 ... Done!
#> Successfully installed and loaded renv 0.7.0-99.
#> * Project '~/ShinyApps/test2/dccvalidator' loaded. [renv 0.7.0-99]
#> Warning message:
#> Project requested R version '3.6.0' but '3.4.1' is currently being used
```

However `.libPaths()` doesn't find the project library:

```r
.libPaths()
#> [1] "/home/kwoo/R/x86_64-pc-linux-gnu-library/3.4"
#> [2] "/tmp/Rtmpsrv1T4/renv-system-library"
renv::paths$library() # should be in .libPaths()
#> [1] "/home/kwoo/ShinyApps/test2/dccvalidator/renv/library/R-3.4/x86_64-pc-linux-gnu"
```

Running `renv::restore()` ought to install the dependencies within `renv/library/`, but as this isn't in `.libPaths()` it doesn't. (I guess I've installed all the dependencies already in the locations that _are_ in `.libPaths()`).

```r
renv::restore()
#> * The library is already synchronized with the lockfile.
```

Calling `renv::load()` explicitly adds the project library to `.libPaths()`, and after that `renv::restore()` will update the project library.

```r
renv::load()
#> * Project '~/ShinyApps/test2/dccvalidator' loaded. [renv 0.7.0-99]
#> Warning message:
#> Project requested R version '3.6.0' but '3.4.1' is currently being used
.libPaths()
#> [1] "/home/kwoo/ShinyApps/test2/dccvalidator/renv/library/R-3.4/x86_64-pc-linux-gnu"
#> [2] "/tmp/Rtmpsrv1T4/renv-system-library"
renv::restore()
#> The following package(s) will be updated:
#> [long list all of them]
```

If I close the R session and open a new one, `.libPaths()` has forgotten about the project library again.

<details>
<summary>Session info</summary>
<pre>
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1    renv_0.7.0-99
</pre>
</details>

**Comment by kevinushey** [comment] 2019-09-23 23:55
Thanks for the bug report + reproducible example!

It looks like this was caused by `renv` erroneously handling the `.First` function in the `.Rprofile`. The intention was that we'd double-check that the code in `.First` would not mutate the library paths after execution. Unfortunately, it looks like I wasn't doing this check properly, and so after the `.Rprofile`'s `.First()` function was executed, the wrong library paths were restored. Doh.

Should hopefully be fixed in master now.

**Closed** 2019-09-24 17:09 UTC

**Comment by karawoo** [comment] 2019-09-24 17:33
Thanks @kevinushey! This worked with a fresh clone of the repo.
