### ISSUE TITLE
"Dry run" restore?

### ISSUE THREAD

**Issue by krlmlr** [rstudio/renv#1038] opened 2022-07-01 00:39 UTC
Is there a way to check if an `renv::restore()` is likely to succeed, without actually touching the library? Optionally, ignoring any caches?

Scenario:

- In a long-running project, I want to lift all packages to the latest and greatest
- I'm not sure the code will work after I upgrade, so I'd like to be able to revert and get my code back to a running state
- Also, I'd like to see if my collaborators will be able to restore

Some of that could be achieved with profiles, I guess. Would that be the recommended approach?

**Comment by kevinushey** [comment] 2022-09-09 17:50
Unfortunately not right now. Currently, the `renv` "solver" (I use that term loosely because the solver is quite primitive) works during restore / install, and package requirements are checked dynamically as packages are installed.

To accommodate this, I think we'd need a proper `solve()` function that could take a list of packages / package records, and then solve for their dependencies in some sensible way, and then infer if their dependencies (e.g. system requirements, package requirements) appear to be available / installable on the current platform.

**Comment by kevinushey** [comment] 2022-09-09 17:51
Down the road, it would probably be better if `renv` could lean on `pak` and its dependencies for package installation / solving and that sort of thing, I think.

**Comment by krlmlr** [comment] 2022-09-10 05:23
For now, a good workflow might be:

- Create a new temporary profile
- Switch to that profile
- Copy `renv.lock` (if needed)
- Perform whatever changes I want to test
- Test
- If fail, go back to old profile
- If success, snapshot, copy renv.lock to old profile, switch profile, restore
- Scrap temporary profile

Would this be a good addition to renv's docs? Where?

**Comment by kevinushey** [comment] 2022-09-12 17:24
Maybe something worth adding to the Profiles vignette? https://github.com/rstudio/renv/blob/main/vignettes/profiles.Rmd

**Comment by hadley** [comment] 2023-05-01 22:26
Duplicate of #145

**Closed by hadley** 2023-05-01 22:26 UTC
Labels: feature, restore :magic_wand:
