### ISSUE TITLE
cannot open file 'renv/activate.R': No such file or directory

### ISSUE THREAD

**Issue by vladimir-obucina** [rstudio/renv#981] opened 2022-04-12 09:58 UTC
I'm experiencing issue similar to this one: https://github.com/rstudio/renv/issues/374, when trying to build package which has renv in project. I've tried reinstalling renv, removing .Rprofile file, removing all the data as stated here: https://rstudio.github.io/renv/articles/renv.html#uninstalling-renv, but nothing works. Only thing that's working right now for building package from project that is using renv is to set **package directory** in build tools to be **full path to the project**. This is not desired behaviour and I'm not sure what happened or what I've changed for this to happen. I've been using renv for almost two years, and nothing similar happened before. Can anyone help me with this?

Here is whole message I get:
`Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted`

**Comment by vladimir-obucina** [comment] 2022-04-12 15:34
Btw, now my whole system is generating that message whenever rsession is started. I don't know what happened but this is causing major issues to my development, I can't even build package from rstudio.

**Comment by kevinushey** [comment] 2022-04-12 17:47
Are you able to share a reproducible example?

Does this happen in all package projects using renv, or just this one?

Did you somehow end up with `source("renv/activate.R")` within your user profile, at `~/.Rprofile`?

Are you using devtools to build your package?

**Comment by vladimir-obucina** [comment] 2022-04-13 08:50
Yes, that was the problem, I don't know how that happened? I haven't changed it myself, is it known bug with renv.

**Comment by Tartomas** [comment] 2022-05-24 16:36
Hi @vladimir-obucina 

I had the same problem and it's related with the _.Rprofile_ configurations on your default R system. On a clumsy way I installed
 `renv::init()` in my default R and not in a project itself. I managed to resolve it using this function and edit the _.Rprofile_ file. 

```
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
> usethis::edit_r_profile()
• Modify '/home/tarto/.Rprofile'
• Restart R for changes to take effect
```
Then I open ` /home/tarto/.Rprofile` with _nano_ and remove source call of `source('renv/activate.R.')`

This resolve the situation.

**Comment by tfalcs** [comment] 2022-11-30 21:00
Let me second @Tartomas , I was having this issue every time I opened an RStudio session. Using Notepad++ to open the .Rprofile file in 'C:/Users/<username>/Documents' and deleting the line "source('renv/activate.R')' solved my issue related to the above error message.

**Comment by hadley** [comment] 2023-04-26 12:51
Might be worth checking that we're not in the home directory when adding `.Rprofile`

**Comment by kevinushey** [comment] 2023-04-26 16:52
`renv` normally tries to prevent this, e.g.

```
> renv::init()
Error: refusing to initialize project in home directory -- use renv::init(force = TRUE) to override
Traceback (most recent calls last):
4: renv::init()
3: renv_init_validate_project(project, force)
2: stopf(msg)
1: stop(sprintf(fmt, ...), call. = call.)
```

So either users are ignoring this warning, or some separate `renv` API is erroneously updating the home directory `.Rprofile`.

**Comment by hadley** [comment] 2023-04-26 20:53
Ok, in that case, I'll close this issue since it doesn't give us a sense of where the problem is.

**Closed by hadley** 2023-04-26 20:53 UTC
Labels: feature, init :zap:
