### ISSUE TITLE
Safely restore packages from lockfile

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/renv#937] opened 2022-02-11 12:33 UTC
Currently, when `renv::restore()` is executed all packages (less those specified in `exclude = `) in the lock file are installed from their original source. However, if any of those installations fail, `renv::restore()` fails and none of the installed packages make it into the renv project. 

Example of error:

```
Installing pkgload [1.0.2] ...
	FAILED
Error installing package 'pkgload':
...
Execution halted
ERROR: loading failed
* removing ‘/Users/josiahparry/github/parry-site/renv/staging/1/pkgload’
Error: install of package 'pkgload' failed [error code 1]
```

Desired alternative:

Rather than erroring out and stopping restoration, it would be desired if packages could be installed safely, errors caught and returned to the user if necessary.

This issue arose when trying to restore a [lockfile](https://gist.github.com/JosiahParry/1ba42b9f4e3fcdde6b370feff1416506) that was created with R 3.6.1. My current machine's info below 

```
>  sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.2  fastmap_1.1.0   cli_3.1.0       htmltools_0.5.2 tools_4.1.2     yaml_2.2.1     
 [7] rmarkdown_2.11  knitr_1.36      xfun_0.28       digest_0.6.28   renv_0.15.1     rlang_0.4.12   
[13] evaluate_0.14  
```

**Comment by hadley** [comment] 2023-04-26 13:01
Duplicate of #1109

**Closed by hadley** 2023-04-26 13:01 UTC
