### ISSUE TITLE
renv local sources not working?

### ISSUE THREAD

**Issue by kendonB** [rstudio/renv#252] opened 2019-11-19 02:00 UTC
To test this I:

1. Set up a minimal renv project with `.Renviron`:
```
RENV_PATHS_LOCAL="../../packages"
```
2. Build a package to tar using `devtools::build("../../packages/mypackage", args = "--md5")`
3. run `renv::init()`
4. restart R
4. run `install.packages("../../packages/mypackage_0.1.tar.gz")`
5. Add a file `test.R` containing `library(mypackage)`
6. Delete the `renv` cache folder (to simulate sharing the lockfile with a colleague)
7. restart R and run `renv::init()`
8. restart R and run `renv::restore()`
I get:
```
* Project '/media/bellk/DATADRIVE/Dropbox/projects_ac/renv_test' loaded. [renv 0.8.3]
> renv::restore()
The following package(s) were installed from an unknown source:
             _
  mypackage   [0.1]

renv will install the latest version(s) from your R package repositories instead.

Do you want to proceed? [y/N]: y
The following package(s) will be updated:

# CRAN ===============================
- Rcpp           [* -> 1.0.3]
- RcppParallel   [* -> 4.4.4]

# (Unknown Source) ===================
- mypackage     [* -> 0.1]

Do you want to proceed? [y/N]: y
* Querying repositories for available source packages ... Done!
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/mypackage/mypackage_0.1.tar.gz' ...
Error: failed to retrieve package 'mypackage'
In addition: Warning messages:
1: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
Traceback (most recent calls first):
9: renv::restore()
8: renv_restore_run_actions(project, diff, current, lockfile)
7: renv_retrieve(packages)
6: handler(package, renv_retrieve_impl(package))
5: renv_retrieve_impl(package)
4: renv_retrieve_unknown_source(record)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
> 
```

**Comment by kevinushey** [comment] 2019-11-19 03:08
Does it work if you provide an absolute path for RENV_PATHS_LOCAL?

**Comment by kevinushey** [comment] 2019-11-19 20:17
Presuming the issue was caused by the usage of a relative path in the environment variable, this should be fixed now in the development version.

**Closed by kevinushey** 2019-11-19 20:17 UTC

**Comment by kendonB** [comment] 2019-11-20 00:16
Still doesn't seem to work for me:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

* Project '/media/bellk/DATADRIVE/Dropbox/projects_ac/renv_test' loaded. [renv 0.8.3-35]
> renv:::renv_paths_local()
[1] "/media/bellk/DATADRIVE/Dropbox/packages"
> renv::restore()
The following package(s) were installed from an unknown source:
             _
  mypackage   [0.1]

renv will install the latest version(s) from your R package repositories instead.

Do you want to proceed? [y/N]: y
The following package(s) will be updated:

# CRAN ===============================
- renv           [rstudio/renv -> 0.8.3]
- RcppParallel   [* -> 4.4.4]

# (Unknown Source) ===================
- mypackage     [* -> 0.1]

Do you want to proceed? [y/N]: y
* Querying repositories for available source packages ... Done!
Retrieving 'https://cloud.r-project.org/src/contrib/renv_0.8.3.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cloud.r-project.org/src/contrib/Archive/mypackage/mypackage_0.1.tar.gz' ...
Error: failed to retrieve package 'mypackage'
In addition: Warning messages:
1: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
Traceback (most recent calls first):
9: renv::restore()
8: renv_restore_run_actions(project, diff, current, lockfile)
7: renv_retrieve(packages)
6: handler(package, renv_retrieve_impl(package))
5: renv_retrieve_impl(package)
4: renv_retrieve_unknown_source(record)
3: renv_retrieve_repos(record)
2: stopf("failed to retrieve package '%s'", record$Package)
1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by kendonB** [comment] 2019-11-20 00:16
@kevinushey

**Comment by kendonB** [comment] 2019-11-20 00:27
How did you test your fix?

**Comment by kevinushey** [comment] 2019-11-20 01:02
This is explicitly tested for in the testthat tests:

https://github.com/rstudio/renv/blob/master/tests/testthat/test-retrieve.R#L153-L173

And here's a standalone example:

``` r

# so that reprex works
library(reprex)

# create project
project <- file.path(tempdir(), "project")
dir.create(project)
setwd(project)
renv::init(settings = list(use.cache = FALSE), restart = FALSE)
#> * Discovering package dependencies ... Done!
#> * Copying packages into the library ... Done!
#> * Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/Rtmp2hrQFB/project/renv.lock'.

# use and install digest
writeLines("library(digest)", con = "deps.R")
renv::install("digest")
#> Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/digest_0.6.22.tgz' ...
#>  OK [file is up to date]
#> Installing digest [0.6.22] ...
#>  OK [installed binary]
renv::snapshot(confirm = FALSE)
#> The following package(s) will be updated in the lockfile:
#> 
#> # CRAN ===============================
#> - digest   [* -> 0.6.22]
#> - renv     [* -> 0.8.3-35]
#> 
#> * Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/Rtmp2hrQFB/project/renv.lock'.

# set up local packages folder with digest
local <- file.path(tempdir(), "local")
Sys.setenv(RENV_PATHS_LOCAL = local)
dir.create(local)
dir.create(file.path(local, "digest"))
download.packages("digest", destdir = file.path(local, "digest"))
#>      [,1]    
#> [1,] "digest"
#>      [,2]                                                                                            
#> [1,] "/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T//Rtmp2hrQFB/local/digest/digest_0.6.22.tar.gz"

# unset repositories and try to restore
renv::remove("digest")
#> * Removing package(s) from project library ...
#> Removing package 'digest' ... Done!
renv::restore(repos = character())
#> The following package(s) will be updated:
#> 
#> # CRAN ===============================
#> - digest   [* -> 0.6.22]
#> 
#> * Package digest [0.6.22] will be installed from local sources rather than Repository.
#> Installing digest [0.6.22] ...
#>  OK [built from source]
#> The dependency tree was repaired during package installation:
#>          _
#>   digest   [0.6.22]
#> 
#> Call `renv::snapshot()` to capture these dependencies in the lockfile.
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment] 2019-11-20 01:25
Do you have a standalone example working that actually uses a local package originally installed from a local source? In the lockfile, for example, I see `"Source": "unknown"` whereas in the above example it's `"Source": "Repository"`

**Comment by kevinushey** [comment] 2019-11-20 01:34
``` r
# so that reprex works
library(reprex)

# create project
project <- file.path(tempdir(), "project")
dir.create(project)
setwd(project)
renv::init(settings = list(use.cache = FALSE), restart = FALSE)
#> * Discovering package dependencies ... Done!
#> * Copying packages into the library ... Done!
#> * Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/RtmpyZy5eA/project/renv.lock'.

# use and install digest
writeLines("library(digest)", con = "deps.R")
renv::install("digest")
#> Retrieving 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/digest_0.6.22.tgz' ...
#>  OK [file is up to date]
#> Installing digest [0.6.22] ...
#>  OK [installed binary]
renv::snapshot(confirm = FALSE)
#> The following package(s) will be updated in the lockfile:
#> 
#> # CRAN ===============================
#> - digest   [* -> 0.6.22]
#> - renv     [* -> 0.8.3-35]
#> 
#> * Lockfile written to '/private/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T/RtmpyZy5eA/project/renv.lock'.

# set up local packages folder with digest
local <- file.path(tempdir(), "local")
Sys.setenv(RENV_PATHS_LOCAL = local)
dir.create(local)
dir.create(file.path(local, "digest"))
download.packages("digest", destdir = file.path(local, "digest"))
#>      [,1]    
#> [1,] "digest"
#>      [,2]                                                                                            
#> [1,] "/var/folders/b4/2422hswx71z8mgwtv4rhxchr0000gn/T//RtmpyZy5eA/local/digest/digest_0.6.22.tar.gz"

# force unknown source
lockfile <- renv:::renv_lockfile_read("renv.lock")
lockfile$Packages$digest$Source <- "unknown"
lockfile$Packages$digest$Repository <- NULL
lockfile$Packages$digest$Hash <- NULL
renv:::renv_lockfile_write(lockfile, "renv.lock")

# print lockfile to confirm
writeLines(readLines("renv.lock"))
#> {
#>   "R": {
#>     "Version": "3.5.3",
#>     "Repositories": [
#>       {
#>         "Name": "CRAN",
#>         "URL": "https://cran.rstudio.com"
#>       }
#>     ]
#>   },
#>   "Packages": {
#>     "digest": {
#>       "Package": "digest",
#>       "Version": "0.6.22",
#>       "Source": "unknown"
#>     },
#>     "renv": {
#>       "Package": "renv",
#>       "Version": "0.8.3-35",
#>       "Source": "Repository",
#>       "Repository": "CRAN",
#>       "Hash": "96d01a4a9901c8d7d3301bc448e0f685"
#>     }
#>   }
#> }

# unset repositories and try to restore
renv::remove("digest")
#> * Removing package(s) from project library ...
#> Removing package 'digest' ... Done!
renv::restore(repos = character())
#> The following package(s) were installed from an unknown source:
#>          _
#>   digest   [0.6.22]
#> 
#> renv will install the latest version(s) from your R package repositories instead.
#> 
#> The following package(s) will be updated:
#> 
#> # (Unknown Source) ===================
#> - digest   [* -> 0.6.22]
#> 
#> * Package digest [0.6.22] will be installed from local sources.
#> Installing digest [0.6.22] ...
#>  OK [built from source]
#> The dependency tree was repaired during package installation:
#>          _
#>   digest   [0.6.22]
#> 
#> Call `renv::snapshot()` to capture these dependencies in the lockfile.
```

<sup>Created on 2019-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kendonB** [comment] 2019-11-20 02:21
A bit annoying that I wasn't able to get `reprex` to work here. Apologies for that. I have worked out the problem. It would be good if renv looked for sources inside `local` and not just `local/package_name`. `devtools::build` by default plonks the tarball next to the source folder, not inside it.

The below simulates a workflow using `devtools::build` subbing in `R CMD build` from the right folder to save installing `devtools`.

The lockfile also identifies the source as CRAN when it probably shouldn't.

```r
>   project <- file.path(tempdir(), "project")
>   dir.create(project)
>   setwd(project)
>   renv::init(settings = list(use.cache = FALSE), restart = FALSE)
* Discovering package dependencies ... Done!
* Copying packages into the library ... Done!
* Lockfile written to '/tmp/Rtmpz3Y1pw/project/renv.lock'.
>   
>   local <- file.path(tempdir(), "local")
>   Sys.setenv(RENV_PATHS_LOCAL = local)
>   dir.create(local)
>   system(paste0("git clone https://github.com/eddelbuettel/digest ", file.path(local, "digest")))
Cloning into '/tmp/Rtmpz3Y1pw/local/digest'...
>   
>   owd <- getwd()
>   setwd(file.path(local))
>   # This outputs the file in the same place that devtools::build would
>   system(paste0("R CMD build --no-build-vignettes ", file.path(local, "digest")))
* checking for file ‘/tmp/Rtmpz3Y1pw/local/digest/DESCRIPTION’ ... OK
* preparing ‘digest’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘digest_0.6.22.3.tar.gz’

>   setwd(owd)
>   # The tar.gz is in local
>   list.files(file.path(local))
[1] "digest"                 "digest_0.6.22.3.tar.gz"
>   
>   # use and install digest
>   writeLines("library(digest)", con = "deps.R")
>   renv::install(file.path(local, "digest_0.6.22.3.tar.gz"))
Installing digest [0.6.22.3] ...
	OK [built from source]
>   
>   # digest doesn't get put into the lock file 
>   renv::snapshot(confirm = FALSE)  
The following package(s) will be updated in the lockfile:

# CRAN ===============================
- digest   [* -> 0.6.22.3]

# GitHub =============================
- renv     [* -> rstudio/renv]

* Lockfile written to '/tmp/Rtmpz3Y1pw/project/renv.lock'.
>   
>   lockfile <- renv:::renv_lockfile_read("renv.lock")
>   renv:::renv_lockfile_write(lockfile, "renv.lock")
>   # Source shows as CRAN - mistake?
>   writeLines(readLines("renv.lock"))
{
  "R": {
    "Version": "3.6.1",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "digest": {
      "Package": "digest",
      "Version": "0.6.22.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e935670ed583fdf6922a3627cf14ecbb"
    },
    "renv": {
      "Package": "renv",
      "Version": "0.8.3-35",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "renv",
      "RemoteUsername": "rstudio",
      "RemoteRef": "master",
      "RemoteSha": "47cc0f5ef7fc68d870f21df0bc5b84edac7314a6",
      "Hash": "df130c0cbb63441e13e6ff6f4745420e"
    }
  }
}
>   
>   renv::remove("digest")
* Removing package(s) from project library ...
Removing package 'digest' ... Done!
>   Sys.getenv("RENV_PATHS_LOCAL")
[1] "/tmp/Rtmpz3Y1pw/local"
>   
>   # Doesn't work as the tar.gz is outside of the digest folder
>   renv::restore(repos = character(), confirm = FALSE)
The following package(s) will be updated:

# CRAN ===============================
- digest   [* -> 0.6.22.3]

Retrieving 'https://cloud.r-project.org/src/contrib/Archive/digest/digest_0.6.22.3.tar.gz' ...
Error: failed to retrieve package 'digest'
In addition: Warning messages:
1: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
>   
>   # Move it inside the digest folder
>   file.copy(file.path(local, "digest_0.6.22.3.tar.gz"), file.path(local, "digest", "digest_0.6.22.3.tar.gz"))
[1] TRUE
>   
>   # Now it works
>   renv::restore(repos = character(), confirm = FALSE)
The following package(s) will be updated:

# CRAN ===============================
- digest   [* -> 0.6.22.3]

* Package digest [0.6.22.3] will be installed from local sources rather than Repository.
Installing digest [0.6.22.3] ...
	OK [built from source]
The dependency tree was repaired during package installation:
         _
  digest   [0.6.22.3]

Call `renv::snapshot()` to capture these dependencies in the lockfile.
```

**Comment by kendonB** [comment] 2019-11-20 02:22
Did you have to use any tricks to get `reprex` to work on yours?

**Comment by kendonB** [comment] 2019-11-20 02:41
For now (or if renv doesn't take my suggestion) googlers should use
```
devtools::build("<package_path>", path = "<package_path>")
```

**Comment by kevinushey** [comment] 2019-11-20 05:34
I had to explicitly load reprex with `library(reprex)` at the top of the script; otherwise I was seeing an error.

**Comment by moritzkoerber** [comment] 2020-04-20 13:49
I have a similar issue using `renv_0.9.3-79`. I have been continuing to work on an R project on a different computer. After `renv::restore()`, I received a missing in cache warning:

```
The following package(s) have broken symlinks into the cache:

	foreign

Consider re-installing these packages.
```

First of all, there seems to be two different wordings for the same problem: Whenever I open the project, a warning tells me 
```
The following package(s) are missing entries in the cache:

	foreign

These packages will need to be reinstalled.
```

"Need to be" or "consider" do not seem to imply the need for action to the same degree to me. Is it obligatory or optional? 

However, both `renv::install("foreign")` and `install.packages("foreign")` return

```
1: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/private/var/folders/z8/hcytzhfx41n8lzl81sbv0jmh0000gn/T/Rtmp61dsDq/renv-tempdir-48133c8af4bf/renv-download-config-4813533e56f5' 2>&1' had status 22
2: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
3: In system2("curl", args$data(), stdout = TRUE, stderr = TRUE) :
  running command ''curl' --config '/private/var/folders/z8/hcytzhfx41n8lzl81sbv0jmh0000gn/T/Rtmp61dsDq/renv-tempdir-48133c8af4bf/renv-download-config-48139247c12' 2>&1' had status 22
4: In downloader(url, destfile, type, request, headers) :
  curl: (22) The requested URL returned error: 404 
```

**Comment by kevinushey** [comment] 2020-04-21 18:10
This appears to be a bug in `renv`, related to the in-progress release of R 4.0.0. Please use `utils::install.packages()` in the interim and I'll try to fix this ASAP.

**Comment by moritzkoerber** [comment] 2020-04-21 18:35
Thanks for the fast reply and keep up the great work!

**Comment by kevinushey** [comment] 2020-04-21 18:55
Thanks -- I believe this should now be fixed on master. If you're still having trouble please file a new issue.

To answer your question:

> "Need to be" or "consider" do not seem to imply the need for action to the same degree to me. Is it obligatory or optional?

This basically means that your project has `foreign` installed in your project library, but the link into the cache was somehow broken and so if you tried to load or use `foreign` that would likely fail. (Or, more likely, the version in your system library would be used instead, if any)
