### ISSUE TITLE
download file method auto not handled

### ISSUE THREAD

**Issue by cderv** [rstudio/renv#67] opened 2019-04-16 12:09 UTC
https://github.com/rstudio/renv/blob/9c9c057346a7b55ddc815469e4d3165c0b299566/R/download.R#L277-L292

This function does not deal with default method `"auto"`. 
However, it is used later 
https://github.com/rstudio/renv/blob/9c9c057346a7b55ddc815469e4d3165c0b299566/R/download.R#L75-L85
Where `"auto"` is not an option in the `switch`

And this is why I get this error
```r
> renv::upgrade()
Error: download failed [could not find function "downloader"]
```

I think `"auto"` should be dealt with here, or download method determined as it was in [remotes ](https://github.com/r-lib/remotes/blob/1f657ec067088add76adedfcc9a0ea2a45aac9e9/R/download.R#L88) without the auto option.

Currently I need to set a `download.file.method` option for this to work either on `curl` or `wget`. In my office windows PC I have neither. I'll check on my windows at home why it works. I must have one of them.

**Comment by kevinushey** [comment] 2019-04-16 15:33
Newer installations of Windows 10 come pre-packaged with `curl`, so that's likely why it works. Right now `renv` requires one of `curl` or `wget` to work as expected, but I can look at how `remotes` handles things like custom headers when using the R internal downloader.

**Comment by cderv** [comment] 2019-04-16 17:04
Yes it is that. I have `curl` on the PC at home. I worked on remote's download method so I know a little bit how it works. 
Basically , 
* if an option is provided we use it
* if R was built with libcurl capabilities we use libcurl, on windows or linux (`capabilities("libcurl")` is TRUE)
* On windows before R 3.3, "wininet" is forced
* else "auto" is used, as R makes a good job now. On windows, it basically falls back to wininet. 

I can work on something if you want to add windows support. As currently I cannot test further on my project at works, I have a good motivation to do so !

**Comment by kevinushey** [comment] 2019-04-17 19:36
I've made some changes to support `libcurl` as a backend, and it should now be selected on Windows when available. Note that `wininet` isn't supported as it doesn't give us a way to set arbitrary headers, whereas we can sneak in support for that when using the `libcurl` downloader.

**Comment by cderv** [comment] 2019-04-19 07:09
I am not sure everything is clear for me. 

You are talking about `headers`. I see it is passed in`download.file()` often in renv. is it why you need header support ? 

I asked because this header thing is [new feature in R 3.6.0](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html). Does that means that renv depends on R >= 3.6.0 ? 

I could also be for`renv_download_headers` but  `libcurl` does not appears in there
https://github.com/rstudio/renv/blob/1c8191bef730614d719585895c62059e83bd8fbb/R/download.R#L321-L326
so I am not sure where the libcurl header support is sneaked in. it currently defaults to 
`renv_download_default`.

For example, `renv::upgrade()` does not work with libcurl. I get an error maybe related with header. (needs to dig a little bit) 
```r
> renv::upgrade()
Error: download failed [cannot open URL 'https://raw.githubusercontent.com/rstudio/renv/{"sha":"5f649c97b44c601d755461f540304c412d4ea98a","node_id":"MDY6Q29tbWl0MTU5NTYwMzg5OjVmNjQ5Yzk3YjQ0YzYwMWQ3NTU0NjFmNTQwMzA0YzQxMmQ0ZWE5OGE=","commit":{"author":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"committer":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"message":"further refine handling of virtualenvs","tree":{"sha":"ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d","url":"https://api.github.com/repos/rstudio/renv/git/trees/ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d"},"url":"https://api.github.com/repos/rstudio/renv/git/commits/5f649c97b44c601d755461f540304c412d4ea98a","comment_count":0,"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}},"url":"https://api.github.com/repos/rstudio/renv/commits/5f649c97b44c601d755461f540304c412d4ea98a","html_url":"https://github.com/rstudio/renv/commit/5
In addition: Warning message:
In download.file(url = url, destfile = destfile, method = "auto",  :
  cannot open URL 'https://raw.githubusercontent.com/rstudio/renv/{"sha":"5f649c97b44c601d755461f540304c412d4ea98a","node_id":"MDY6Q29tbWl0MTU5NTYwMzg5OjVmNjQ5Yzk3YjQ0YzYwMWQ3NTU0NjFmNTQwMzA0YzQxMmQ0ZWE5OGE=","commit":{"author":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"committer":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"message":"further refine handling of virtualenvs","tree":{"sha":"ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d","url":"https://api.github.com/repos/rstudio/renv/git/trees/ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d"},"url":"https://api.github.com/repos/rstudio/renv/git/commits/5f649c97b44c601d755461f540304c412d4ea98a","comment_count":0,"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}},"url":"https://api.github.com/repos/rstudio/renv/commits/5f649c97b44c601d755461f540304c412d4ea98a","html_url":"https://github.com/rstudio/renv/commit/5f649c97b44c601d755461f540 [... truncated]
```

Sorry to ask all that, I try to get a better understanding in order to better test and report what is working or not. As I am on windows, I can easily work on that if you want once I correctly understand how it should work.


> Note that wininet isn't supported as it doesn't give us a way to set arbitrary headers

I don't know how many windows environment have not libcurl support `capabilities("libcurl") == FALSE`, but this means that renv won't be supported on those environments. It could be important to explain that somewhere (in the README ?). However, as `headers` are a 3.6.0 features,  `wininet` could be supported for R < 3.6.0 on windows. 

FWIW, I tried wininet for CRAN package and it works. So there could be at least a limited support

**Comment by kevinushey** [comment] 2019-04-19 15:07
> I asked because this header thing is new feature in R 3.6.0. Does that means that renv depends on R >= 3.6.0 ?

Nope, because we can set headers in other ways. It's simple for `curl` and `wget` downloaders, but requires a bit of a hack for older versions of R with libcurl:

https://github.com/rstudio/renv/blob/5f649c97b44c601d755461f540304c412d4ea98a/R/download.R#L105-L135

IIUC `libcurl` is supported back to R 3.2.x, although with a variety of bug fixes since then. What version of R are you using?

In theory a limited version of `renv` could work without headers, but it will then mean that things like authentication will not be supported. I think I'd rather provide some helper function for installing `curl` and putting it on the PATH (with user consent, of course)

**Comment by cderv** [comment] 2019-04-19 15:29
> requires a bit of a hack for older versions of R with libcurl

Ok - now that you point me too it, I understand this lines of code. It was cryptic the first time.

> What version of R are you using?

3.5.3 - recent one. The issue I have may not be related to header. I will investigate.

> I think I'd rather provide some helper function for installing curl and putting it on the PATH (with user consent, of course)

I don't really know what it implies to install curl. Not sure it will be easy inside corporate network, with possible limitations from corporate environment. But libcurl support should be enough to cover all this. 
And, hoping new windows will arrive soon in corporate environment, this would not be required anymore. 
However, we are currently migrating to Windows 10 and we don't have curl available.

**Comment by cderv** [comment] 2019-04-19 15:45
And if fact the error is with the second built url that should download the package based on the sha
https://github.com/rstudio/renv/blob/bbbb0be2cfc52c119efbcb8f9c40631e51bc3562/R/remotes.R#L55-L67
you can see above in the error the url is build with the second `%s` being the `sha` but it is a json string not parsed. Instead, you are expected on the sha. I believe this is what the header is there for 
` headers <- c(Accept = "application/vnd.github.v2.sha")` 

So a json string is received, containing the sha but either it needs to be parsed or something went wrong with libcurl and the header was not correctly pass through using the hack. 

Is it enough clear ? 
I think to reproduce you should get an error with this 

``` r
Sys.setenv(RENV_DOWNLOAD_FILE_METHOD="libcurl")
renv:::renv_remotes_parse_github("rstudio/renv")
#> Warning in download.file(url = url, destfile = destfile, method =
#> "auto", : cannot open URL 'https://raw.githubusercontent.com/rstudio/renv/
#> {"sha":"5f649c97b44c601d755461f540304c412d4ea98a","node_id":"MDY6Q29tbWl0MTU5NTYwMzg5OjVmNjQ5Yzk3YjQ0YzYwMWQ3NTU0NjFmNTQwMzA0YzQxMmQ0ZWE5OGE=","commit":
#> {"author":{"name":"Kevin
#> Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"committer":
#> {"name":"Kevin
#> Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"message":"further
#> refine handling of virtualenvs","tree":
#> {"sha":"ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d","url":"https://
#> api.github.com/repos/rstudio/renv/git/trees/
#> ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d"},"url":"https://
#> api.github.com/repos/rstudio/renv/git/commits/
#> 5f649c97b44c601d755461f540304c412d4ea98a","comment_count":0,"verification":
#> {"verified":false,"reason":"unsigned","signature":null,"payload":null}},"url":"https://
#> api.github.com/repos/rstudio/renv/commits/
#> 5f649c97b44c601d755461f540304c412d4ea98a","html_url":"https://github.com/
#> rstudio/renv/commit/5f649c97b44c601d755461f540 [... truncated]
#> Error: download failed [cannot open URL 'https://raw.githubusercontent.com/rstudio/renv/{"sha":"5f649c97b44c601d755461f540304c412d4ea98a","node_id":"MDY6Q29tbWl0MTU5NTYwMzg5OjVmNjQ5Yzk3YjQ0YzYwMWQ3NTU0NjFmNTQwMzA0YzQxMmQ0ZWE5OGE=","commit":{"author":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"committer":{"name":"Kevin Ushey","email":"kevinushey@gmail.com","date":"2019-04-18T23:17:50Z"},"message":"further refine handling of virtualenvs","tree":{"sha":"ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d","url":"https://api.github.com/repos/rstudio/renv/git/trees/ec8d10dfb90a92b9a7aa25dc6a398b03b8fd983d"},"url":"https://api.github.com/repos/rstudio/renv/git/commits/5f649c97b44c601d755461f540304c412d4ea98a","comment_count":0,"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}},"url":"https://api.github.com/repos/rstudio/renv/commits/5f649c97b44c601d755461f540304c412d4ea98a","html_url":"https://github.com/rstudio/renv/commit/5f649c97b44c601d755461f54]
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I am on windows and R 3.5.3

**Comment by kevinushey** [comment] 2019-04-19 16:11
I just made some changes that should better handle this case, but the fact that you're getting a JSON blob instead of just the SHA means that the `Accept` header is not being sent. I'll see if I can reproduce on my machine as well.

**Comment by cderv** [comment] 2019-04-19 16:25
This is working as expected now with "libcurl" 
``` r
packageVersion("renv")
#> [1] '0.3.0.46'
Sys.setenv(RENV_DOWNLOAD_FILE_METHOD="libcurl")
renv:::renv_remotes_parse_github("rstudio/renv")
#> $Package
#> [1] "renv"
#> 
#> $Version
#> [1] "0.3.0-46"
#> 
#> $Source
#> [1] "GitHub"
#> 
#> $RemoteUsername
#> [1] "rstudio"
#> 
#> $RemoteRepo
#> [1] "renv"
#> 
#> $RemoteRef
#> [1] "master"
#> 
#> $RemoteSha
#> [1] "c0aa8f51505ac56911f0862afe77c3172be96d02"
#> 
#> $RemoteHost
#> [1] "api.github.com"
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, I wonder if libcurl is really used or not as method because 
https://github.com/rstudio/renv/blob/c0aa8f51505ac56911f0862afe77c3172be96d02/R/download.R#L88-L101
the method set in `download.file` is "auto". 

In R, it will default to `wininet` unless ftps url and libcurl available (from_ `download.file()` source code)
```r
if (method == "auto") {
    if (length(url) != 1L || typeof(url) != "character") 
      stop("'url' must be a length-one character vector")
    method <- if (grepl("^ftps:", url) && capabilities("libcurl")) 
      "libcurl"
    else "wininet"
  }
```

So it may be possible that wininet is used here. Could be why the header is not passed. If I correctly understood what you said about wininet not supporting header. 

Is the `download.file` method argument should use the `renv:::renv_download_file_method()` ?

**Comment by kevinushey** [comment] 2019-04-19 16:37
I just made that change as well 🙂

**Comment by cderv** [comment] 2019-04-19 17:11
This is working now. But even with the `method` change in `download.file` the seems to not be accepted with libcurl as I don't get the sha directly but a json string. 

The parsing workaround is still required. It may be interesting to decide if it is better for user to install renv extsoft to have curl, or rely on libcurl, and explain this in documentation. 

However, `renv::equip()` does not work on a corporate environment because we can't install in C:/ here. 
I find it a bit invasive to install for the user some binaries in C: drive without asking or warning (unless you read the doc). From the value and the doc, I understand this should be the same dir as where Rtools is install ? Currently, my Rtools installation is not in there as I can't install anything in C:/Rbuildtools.

Why note use `%APPDATA%/renv` for curl exe like in the [doc ](https://rstudio.github.io/renv/reference/paths.html) or windows ? 

I tried quicky to change `RENV_PATHS_EXTSOFT` to a writable location, but it is not taken into account by `renv::equip()` it seems.

https://github.com/rstudio/renv/blob/b3dbec5982cf5227040081f7df9e577143ce5132/R/paths.R#L148-L152

I'll dig a bit into this later, in another issue maybe.

This issue was about not being able to upgrade renv on a computer with windows and not curl or wget, and now it is ok.

**Comment by kevinushey** [comment] 2019-04-19 17:23
That's a good idea re: moving the installation for these tools. I originally made this choice because RStudio does the same thing when installing Rtools.

**Comment by cderv** [comment] 2019-04-19 17:31
> because RStudio does the same thing when installing Rtools.

Oh I know! You may remember that we dealt with some issue in the IDE regarding this path already and the fact cran rtools use another path 😊

I find that using the user APPDATA folder on windows is more and more a clever choice as : 
* it is writable 
* you can refer to it quickly with an env variable. 

For the time being, I can't equip my windows computer at work using `renv::equip`.

**Comment by kevinushey** [comment] 2019-04-19 18:03
Okay, I've made a number of changes now to ensure that extsoft gets installed into the renv root folder alongside the other renv state components, and `RENV_PATHS_EXTSOFT` should be respected as well. If you have a chance to give it a test-drive, let me know how it goes!

**Comment by cderv** [comment] 2019-04-20 08:47
> If you have a chance to give it a test-drive, let me know how it goes!

I'll do that next week on my corporate computer - that is where I have the most issue. Looking at the change I believe this should go well. I'll let you know. Thanks

**Comment by kevinushey** [comment] 2019-04-22 17:33
I believe the download-related issues have now been resolved, so I'm going to close this -- please re-open if you're still having trouble, or please open a separate issue if you have trouble with `equip()`. Thanks!

**Closed by kevinushey** 2019-04-22 17:33 UTC

**Comment by cderv** [comment] 2019-04-23 09:13
I can confirm now that this is working fine ! Thanks !
