### ISSUE TITLE
Install package from local CRAN-like HTTP Repo results in "unknown source"

### ISSUE THREAD

**Issue by de-mim-1974** [rstudio/renv#402] opened 2020-04-22 16:37 UTC
I have created a CRAN-like repository for our department and the employees, which can be accessed via http (Hosted by IIS). The goal is to provide our own packages centrally for our employees via an internal URL.
```
> getOption("repos")
CRAN                      LOCALCOMPANY
"http://cran.rstudio.com" "http://local.cran.company.internal:7013"

> renv::install("MYPACKAGE")
Retrieving 'http://local.cran.company.internal:7013/bin/windows/contrib/3.5/MYPACKAGE_0.1.zip'...
OK [file is up to date]
Installing MYPACKAGE [0.1] ...
OK (linked cache)

Unfortunately, the source for the package is not saved and is always 
set to "Source: unknown" in the renv.lock file.

> renv::snapshot()
The following package (s) were installed from an unknown source:

MYPACKAGE

renv may be unable to restore these packages in the future.
Consider re-installing these packages from a known source (e.g. CRAN).

Do you want to proceed? [y / N]:
```

Renv.lock file:
```
{
  "R": {
    "Version": "3.5.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "http://cran.rstudio.com"
      },
      {
        "Name": "LOCALCOMPANY",
        "URL": "http://local.cran.company.internal:7013"
      }
    ]
  },
  "Packages": {
    ...
    "MYPACKAGE": {
      "Package": "MYPACKAGE",
      "Version": "0.1",
      "Source": "unknown",
      "Hash": "80ed6b8262cc9143c7700d62a68b646d"
    },
   ....
}
```
I usually expect the following entry in the renv.lock file:
```
     "MYPACKAGE": {
       "Package": "MYPACKAGE",
       "Version": "0.1",
       "Source": "Repository",
       "Repository": "LOCALCOMPANY",
       "Hash": "80ed6b8262cc9143c7700d62a68b646d"
     },
```
Unfortunately, it also doesn't work if I enter these values manually here.

I would like to implement this solution with HTTP(S) because "network drive shares" are outdated. 

What do I have to do to make this solution work?

**Comment by kevinushey** [comment] 2020-04-22 19:32
`renv` tries to infer the source for an installed package based on the `DESCRIPTION` file. You can see the logic here:

https://github.com/rstudio/renv/blob/be27a7fc7051832730025e386f28eb24937130c9/R/snapshot.R#L602-L632

I think the check here needs to check both the binary + source repositories, since I suspect in your case that the package is only available from the binary repository.

The other solution would be to explicitly set a `Repository: LOCALCOMPANY` entry within the package's `DESCRIPTION` file.

**Comment by kevinushey** [comment] 2020-04-22 21:28
I believe this should now be fixed in the latest development version of `renv` -- are you able to give it a shot?

```
renv::upgrade(version = "master")
```

**Comment by de-mim-1974** [comment] 2020-04-23 10:16
Thank you Kevin for your Feedback.

I've installed the latest developement version of renv with the command you give me.

If I'm now execute:

```
> renv::remove("MYPACKAGE")
* Removing package(s) from project library ...
Removing package 'MYPACKAGE' ... Done!
> renv::snapshot()
The following package(s) will be updated in the lockfile:

# Repository =========================
- MYPACKAGE [0.1 -> *]

Do you want to proceed? [y/N]: y
* Lockfile written to 'C:/path/test.renv/renv.lock'.

> renv::install("MYPACKAGE")
Installing MYPACKAGE [0.1] ...
	OK (linked cache)

> renv::snapshot()
The following package(s) will be updated in the lockfile:

# Repository =========================
- MYPACKAGE [* -> 0.1]

Do you want to proceed? [y/N]: y
* Lockfile written to 'C:/path/test.renv/renv.lock'.
```
... the renv.lock entry is:

```
    "MYPACKAGE": {
      "Package": "MYPACKAGE",
      "Version": "0.1",
      "Source": "Repository",
      "Repository": null,
      "Hash": "80ed6b8262cc9143c7700d62a68b646d"
    },
```

The following thinks are changed:

This messages are **not** print out:
```
Unfortunately, the source for the package is not saved and is always 
set to "Source: unknown" in the renv.lock file.

and

The following package (s) were installed from an unknown source:

MYPACKAGE

renv may be unable to restore these packages in the future.
Consider re-installing these packages from a known source (e.g. CRAN).
```


On `renv:install("MYPACKAGE")` this message is **not** print out:
```
Retrieving 'http://local.cran.company.internal:7013/bin/windows/contrib/3.5/MYPACKAGE_0.1.zip'...
OK [file is up to date]
```
Why? I like to see where the packages come from.

Why is in my renv.lock file now "Repository": null,", I expected that it will set to `"Repository": "LOCALCOMPANY"`

All this I've done it two times. One Time with `Repository: LOCALCOMPANY` entry within the package's DESCRIPTION file. One Time without that entry. But both cases have the same result. Why is the Repository field used, with the background that the repositories in renv are listed in the renv.lock file?

**Comment by de-mim-1974** [comment] 2020-04-23 14:01
Also I had try to install my package to use it in a other package ...

Upgrade renv to latest development version:
```
renv::install(version = "master")
Error in get(Info[i, 1], envir = env) : 
  lazy-load database 'C:/path/packages/Examples/SampleRDevPackage/renv/library/R-3.5/x86_64-w64-mingw32/renv/R/renv.rdb' is corrupt
```
After it was possible to install the latest development version, I was try to install MYPACKAGE:
```
> renv::install("MYPACKAGE")
Retrieving 'http://local.cran.company.internal:7013/src/contrib/MYPACKAGE_0.0.2.tar.gz' ...
	OK [file is up to date]
Installing MYPACKAGE [0.0.2] ...
	FAILED
Error installing package 'MYPACKAGE':
==========================================

at R CMD INSTALL
Error: install of package 'MYPACKAGE' failed
```
By the command  renv::install("MYPACKAGE") a Dos windows open and close automaticliy, so I can't read the messages. After this I get the Information that 1) "FAILED" 2) "Error installing package 'MYPACKAGE'" and 3) "Error: install of package 'MYPACKAGE' failed". So I can't see any Informations for that "Error".

**Comment by kevinushey** [comment] 2020-04-23 16:06
> Why? I like to see where the packages come from.

See the install output:

```
> renv::install("MYPACKAGE")
Installing MYPACKAGE [0.1] ...
	OK (linked cache)
```

`renv` detected it already has a version of MYPACKAGE 0.1 in its global package cache, and so used that in lieu of attempting to download and reinstall the package from your package repository. (Normally, you should bump the version of your package whenever making new changes and uploading them to a public package repository.)

I don't have any good ideas for why the second install attempt is failing. Does a plain:

```
utils::install.packages("MYPACKAGE")
```

work without issue?

**Comment by francoisluc** [comment] 2020-11-05 19:18
Hi,  I had similar experience, I looked-up the code and changed only "Name" for "Repository" at : 
https://github.com/rstudio/renv/blob/master/R/snapshot.R#L670

`entry` is a list without any element named "Name".

The lockfile now look like 

```
"MYPACKAGE": {
      "Package": "MYPACKAGE",
      "Version": "0.1",
      "Source": "Repository",
      "Repository": "LOCAL_REPO",
      "Hash": "80ed6b8262cc9143c7700d62a68b646d"
    },
```

I really hope it helps. 

Btw, good job for this package, it is really useful.

**Comment by slodge** [comment] 2020-11-06 05:45
We've seen intermittent issues with this - can't really point to reproducing it.

In the end I went through all of our local packages and added a line to each of their DESCRIPTION files like:

```
Repository: LOCAL_REPO_NAM
```

I couldn't see this line documented (e.g. not on https://r-pkgs.org/description.html) but it seems to have helped with this issue.

**Comment by francoisluc** [comment] 2020-11-06 13:14
@slodge 

I cannot create a branch to propose the changes but I was able to make it work on my computer. I traced the function with 

```
trace(renv:::renv_snapshot_description_source, edit = T)
```
I don't know if you are familiar with `trace` but it basically alter the code of the loaded function until the session restarts.


And change the code to (changes highlighted in bold)

```
type <- dcf[["RemoteType"]]
  if (!is.null(type))
    return(list(Source = renv_alias(type)))

  if (!is.null(dcf[["Repository"]]))
    return(list(Source = "Repository", Repository = dcf[["Repository"]]))

  if (!is.null(dcf[["biocViews"]]))
    return(list(Source = "Bioconductor"))

  package <- dcf[["Package"]]
  if (is.null(package))
    return(list(Source = "unknown"))

  entry <- local({
    renv_scope_options(renv.verbose = FALSE)
    catch(renv_available_packages_latest(package))
  })

  if (!inherits(entry, "error"))
    return(list(Source = "Repository", Repository = entry[["**Repository**"]]))

  location <- catch(renv_retrieve_local_find(dcf))
  if (!inherits(location, "error"))
    return(list(Source = "Local"))

  list(Source = "unknown")

```

And it works without adding the repository in the description. We have multiple packages at my cie and multiple users so adding the Repository tag in the description files was not ideal. Tracing the function is not the best too but I'm pretty sure it will be fixed soon.

**Comment by kevinushey** [comment] 2020-11-06 20:03
Thanks everyone! I think this is now fixed via https://github.com/rstudio/renv/commit/0ddba503a31c580fa333ca63c7ea71410fb91818.

**Closed by kevinushey** 2020-11-06 20:03 UTC
