### ISSUE TITLE
`dependencies()` does not honor .renvignore file

### ISSUE THREAD

**Issue by mlell** [rstudio/renv#439] opened 2020-05-26 09:57 UTC
I tried to limit the scope of snapshotting in my project because it contains a folder with an RStudio instance. Thats a lot of R files that I want to exclude from snapshotting. However, the process does not seem to be like stated in the documentation. From `?renv::dependencies`:

> By default, renv will read your project's .gitignores (if any) to determine whether certain files or folders should be included when traversing directories. If preferred, you can also create a .renvignore file (with entries of the same format as a standard .gitignore file) to tell renv which files to ignore within a directory

Below is a minimal example with my results that show that  `dependencies` does in fact traverse excluded files and folders:

```
packageVersion("renv")
## [1] ‘0.10.0.42’
## 
dir.create("exclude")
## 
writeLines("*","exclude/.gitignore")
## 
writeLines("library(data.table)", "exclude/test.R")
## 
print(renv::dependencies())
## Finding R package dependencies ... Done!
##                                           Source    Package Require Version   Dev
## 1 C:/Users/user/Desktop/renv-test/exclude/test.R data.table                 FALSE
## 
print(renv::diagnostics())
## Diagnostics Report -- renv [0.10.0-42]
## ======================================
## 
## # Session Info =======================
## R version 3.6.0 (2019-04-26)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17763)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
## [1] compiler_3.6.0 renv_0.10.0-42
## 
## # Project ============================
## Project path: "C:/Users/user/Desktop/renv-test"
## 
## # Status =============================
## * This project has not yet been initialized.
## 
## # Packages ===========================
## This project has not yet been snapshotted: 'renv.lock' does not exist.
## The project library "C:/Users/user/Desktop/renv-test/renv/library/R-3.6/x86_64-w64-mingw32" does not exist.
##              Library Source Lockfile Source Path Dependency
## KernSmooth   2.23-15   CRAN     <NA>   <NA>  [2]       <NA>
## MASS        7.3-51.4   CRAN     <NA>   <NA>  [2]       <NA>
## Matrix        1.2-17   CRAN     <NA>   <NA>  [2]       <NA>
## boot          1.3-22   CRAN     <NA>   <NA>  [2]       <NA>
## class         7.3-15   CRAN     <NA>   <NA>  [2]       <NA>
## cluster        2.0.8   CRAN     <NA>   <NA>  [2]       <NA>
## codetools     0.2-16   CRAN     <NA>   <NA>  [2]       <NA>
## data.table      <NA>   <NA>     <NA>   <NA> <NA>     direct
## foreign       0.8-71   CRAN     <NA>   <NA>  [2]       <NA>
## lattice      0.20-38   CRAN     <NA>   <NA>  [2]       <NA>
## mgcv          1.8-28   CRAN     <NA>   <NA>  [2]       <NA>
## nlme         3.1-139   CRAN     <NA>   <NA>  [2]       <NA>
## nnet          7.3-12   CRAN     <NA>   <NA>  [2]       <NA>
## remotes        2.1.1   CRAN     <NA>   <NA>  [1]       <NA>
## renv       0.10.0-42 GitHub     <NA>   <NA>  [1]       <NA>
## rpart         4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
## spatial       7.3-11   CRAN     <NA>   <NA>  [2]       <NA>
## survival    2.44-1.1   CRAN     <NA>   <NA>  [2]       <NA>
## 
## [1]: C:/Users/user/Documents/R/win-library/3.6
## [2]: C:/Program Files/R/R-3.6.0/library       
## 
## # User Profile =======================
## [no user profile detected]
## 
## # Settings ===========================
## List of 6
##  $ external.libraries       : chr(0) 
##  $ ignored.packages         : chr(0) 
##  $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
##  $ snapshot.type            : chr "implicit"
##  $ use.cache                : logi TRUE
##  $ vcs.ignore.library       : logi TRUE
## 
## # Options ============================
## List of 1
##  $ renv.verbose: logi TRUE
## 
## # Environment Variables ==============
## HOME        = C:\Users\user\Documents
## LANG        = <NA>
## R_LIBS      = <NA>
## R_LIBS_SITE = <NA>
## R_LIBS_USER = C:\Users\user\Documents/R/win-library/3.6
## 
## # PATH ===============================
## - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
## - C:\Windows\system32
## - C:\Windows
## - C:\Windows\System32\Wbem
## - C:\Windows\System32\WindowsPowerShell\v1.0\
## - C:\Windows\System32\OpenSSH\
## - C:\Program Files (x86)\PuTTY\
## - C:\Users\lell\AppData\Local\Microsoft\WindowsApps
## 
## # Cache ==============================
## There are a total of 0 package(s) installed in the renv cache.
## Cache path: "C:/Users/user/AppData/Local/renv/cache/v5/R-3.6/x86_64-w64-mingw32"
## 
## NULL


```

According to the documentation, `data.table` should not be found as a dependency, right?

**Comment by kevinushey** [comment] 2020-05-26 20:44
The issue here, I believe, is that `renv` isn't able to determine the project root in this scenario. The issue is resolved if you create a `.git` folder; e.g.

```
setwd(tempdir())

dir.create(".git")
dir.create("exclude")
writeLines("*","exclude/.gitignore")
writeLines("library(data.table)", "exclude/test.R")
print(renv::dependencies())
```

I see:

```
> setwd(tempdir())
> 
> dir.create(".git")
> dir.create("exclude")
> writeLines("*","exclude/.gitignore")
> writeLines("library(data.table)", "exclude/test.R")
> print(renv::dependencies())
Finding R package dependencies ... Done!
NULL
```

**Comment by mlell** [comment] 2020-05-27 09:11
@kevinushey That's very interesting! Indeed, it works also for other special files. 

For example, if you create an empty file "renv.lock", the issue is resolved as well!

On the other hand, I tried to call `renv::snapshot(project =".")`, that didn't change the behaviour (I was speculating that maybe I can explicitly set the project root with this)

I'm quite new to renv, is this expected behaviour or should there be an error generated in such a case?

**Comment by kevinushey** [comment] 2020-05-27 16:52
Thanks! You're absolutely correct; this looks like a bug / oversight in `renv`. This should now be fixed on master -- thanks for the bug report!

**Closed** 2020-05-27 16:52 UTC

**Comment by mlell** [comment] 2020-05-27 18:47
thanks for your work!
