### ISSUE TITLE
Error when trying to install package: install of package failed, does not exist

### ISSUE THREAD

**Issue by isaactpetersen** [rstudio/renv#672] opened 2021-03-07 20:01 UTC
I receive an error when trying to install a package when using `renv`.  Here's my code and output:

```
> renv::install("usethis")
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/usethis_2.0.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/cli_2.3.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/glue_1.4.2.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/clipr_0.7.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/crayon_1.4.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/curl_4.3.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/src/contrib/desc_1.3.0.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/R6_2.5.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rprojroot_2.0.2.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/fs_1.5.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/gert_1.2.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/askpass_1.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/sys_3.4.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/credentials_1.3.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/openssl_1.4.3.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/jsonlite_1.7.2.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rstudioapi_0.13.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/zip_2.1.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/gh_1.2.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/gitcreds_0.1.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/httr_1.4.2.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/mime_0.10.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/ini_0.3.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/lifecycle_1.0.0.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rlang_0.4.10.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/purrr_0.3.4.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/magrittr_2.0.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rappdirs_0.3.3.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/whisker_0.4.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/withr_2.4.1.zip' ...
	OK [file is up to date]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/yaml_2.2.1.zip' ...
	OK [file is up to date]
Installing glue [1.4.2] ...
	FAILED
Error installing package 'glue':
================================

* installing to library 'C:/R/Packages'
package 'glue' successfully unpacked and MD5 sums checked
Error: install of package 'glue' failed ["~/GitHub/petersenlab/renv/staging/1/glue" does not exist]
```

Here's the `traceback()`
```
> traceback()
12: stop(error)
11: r_exec_error(package, output, "install", installpath)
10: r_cmd_install(package, path)
9: renv_install_package_local_impl(package, path)
8: renv_install_package_local(record)
7: withCallingHandlers(renv_install_package_local(record), error = function(e) {
       vwritef("\tFAILED")
       writef(e$output)
   })
6: renv_install_impl(record)
5: handler(package, renv_install_impl(record))
4: renv_install_default(records)
3: renv_install_staged(records)
2: renv_install(records)
1: renv::install("usethis")
```

Here's the outcome of diagnostics:
```
> renv::diagnostics()
Diagnostics Report [renv 0.13.0]
================================

# Session Info =======================
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2    renv_0.13.0    fortunes_1.5-4

# Project ============================
Project path: "~/GitHub/petersenlab"

# Status =============================
* The project is already synchronized with the lockfile.
The following package(s) are used in the project, but are not installed:

	digest

Consider installing these packages, and then using `renv::snapshot()`
to record these packages in the lockfile.


# Packages ===========================
            Library Source Lockfile Source Path Dependency
KernSmooth  2.23-18   CRAN     <NA>   <NA>  [2]       <NA>
MASS       7.3-53.1   CRAN     <NA>   <NA>  [2]       <NA>
assertthat    0.2.1   CRAN     <NA>   <NA>  [1]       <NA>
boot         1.3-27   CRAN     <NA>   <NA>  [2]       <NA>
class        7.3-18   CRAN     <NA>   <NA>  [2]       <NA>
cluster       2.1.1   CRAN     <NA>   <NA>  [2]       <NA>
codetools    0.2-18   CRAN     <NA>   <NA>  [2]       <NA>
devtools       <NA>   <NA>     <NA>   <NA> <NA>     direct
digest         <NA>   <NA>     <NA>   <NA> <NA>     direct
foreign      0.8-81   CRAN     <NA>   <NA>  [2]       <NA>
lattice     0.20-41   CRAN     <NA>   <NA>  [2]       <NA>
mgcv         1.8-34   CRAN     <NA>   <NA>  [2]       <NA>
nlme        3.1-152   CRAN     <NA>   <NA>  [2]       <NA>
nnet         7.3-15   CRAN     <NA>   <NA>  [2]       <NA>
renv         0.13.0   CRAN   0.13.0   CRAN  [1]     direct
roxygen2       <NA>   <NA>     <NA>   <NA> <NA>     direct
rpart        4.1-15   CRAN     <NA>   <NA>  [2]       <NA>
spatial      7.3-13   CRAN     <NA>   <NA>  [2]       <NA>
survival      3.2-7   CRAN     <NA>   <NA>  [2]       <NA>
tools          <NA>   <NA>     <NA>   <NA>  [2]     direct
utils          <NA>   <NA>     <NA>   <NA>  [2]   indirect

[1]: D:/Documents/GitHub/petersenlab/renv/library/R-4.0/x86_64-w64-mingw32
[2]: C:/Users/Isaac/AppData/Local/Temp/RtmpuQbZrv/renv-system-library     

# User Profile =======================
[no R packages referenced in user profile

# Settings ===========================
List of 7
 $ external.libraries       : chr(0) 
 $ ignored.packages         : chr(0) 
 $ package.dependency.fields: chr [1:3] "Imports" "Depends" "LinkingTo"
 $ r.version                : chr(0) 
 $ snapshot.type            : chr "implicit"
 $ use.cache                : logi TRUE
 $ vcs.ignore.library       : logi TRUE

# Options ============================
List of 6
 $ defaultPackages     : chr [1:6] "datasets" "utils" "grDevices" "graphics" ...
 $ download.file.method: chr "wininet"
 $ download.file.extra : NULL
 $ repos               : Named chr "https://cran.r-project.org"
  ..- attr(*, "names")= chr "CRAN"
 $ renv.consent        : logi TRUE
 $ renv.verbose        : logi TRUE

# Environment Variables ==============
HOME                        = D:\Documents
LANG                        = <NA>
R_LIBS                      = <NA>
R_LIBS_SITE                 = <NA>
R_LIBS_USER                 = D:/Documents/GitHub/petersenlab/renv/library/R-4.0/x86_64-w64-mingw32;C:/Users/Isaac/AppData/Local/Temp/RtmpuQbZrv/renv-system-library
RENV_DEFAULT_R_ENVIRON      = <NA>
RENV_DEFAULT_R_ENVIRON_USER = <NA>
RENV_DEFAULT_R_LIBS         = <NA>
RENV_DEFAULT_R_LIBS_SITE    = <NA>
RENV_DEFAULT_R_LIBS_USER    = C:\Program Files\R\Packages
RENV_DEFAULT_R_PROFILE      = <NA>
RENV_DEFAULT_R_PROFILE_USER = <NA>
RENV_PROJECT                = D:/Documents/GitHub/petersenlab

# PATH ===============================
- C:\rtools40\usr\bin
- C:\rtools40\usr\bin
- C:\R\R-4.0.2\bin\x64
- C:\WINDOWS\system32
- C:\WINDOWS
- C:\WINDOWS\System32\Wbem
- C:\WINDOWS\System32\WindowsPowerShell\v1.0\
- C:\WINDOWS\System32\OpenSSH\
- C:\Program Files\MiKTeX 2.9\miktex\bin\x64\
- C:\Program Files\PuTTY\
- C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
- C:\Program Files\dotnet\
- C:\Program Files\MiKTeX\miktex\bin\x64\
- C:\Program Files\MATLAB\R2020b\runtime\win64
- C:\Program Files\MATLAB\R2020b\bin
- C:\Program Files\MATLAB\R2020a\runtime\win64
- C:\Program Files\MATLAB\R2020a\bin
- C:\Program Files\Mplus\
- C:\Program Files\ffmpeg\bin
- C:\Program Files\Git\cmd
- C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\
- C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\
- C:\Program Files\Java\jre1.8.0_231\bin\server
- C:\Program Files (x86)\Common Files\Oracle\Java\javapath
- C:\Program Files\MATLAB\R2016b\runtime\win64
- C:\Program Files\MATLAB\R2016b\bin
- C:\Users\Isaac\AppData\Local\Microsoft\WindowsApps
- C:\Users\Isaac\AppData\Local\Microsoft\WindowsApps
- C:\Users\Isaac\AppData\Local\GitHubDesktop\bin
- C:\Users\Isaac\AppData\Roaming\TinyTeX\bin\win32

# Cache ==============================
There are a total of 0 package(s) installed in the renv cache.
Cache path: "C:/Users/Isaac/AppData/Local/renv/cache/v5/R-4.0/x86_64-w64-mingw32"
```

Here are the contents of my lock file:
```
{
  "R": {
    "Version": "4.0.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cran.r-project.org"
      }
    ]
  },
  "Packages": {
    "renv": {
      "Package": "renv",
      "Version": "0.13.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9f10d9db5b50400c348920c5c603385e"
    }
  }
}
```

I'm new to `renv` so your help would be greatly appreciated. I wonder if it has to do with `RENV_DEFAULT_R_LIBS_USER    = C:\Program Files\R\Packages`. My packages are saved in `C:/R/Packages` (not in `C:\Program Files\R\Packages`). Thanks!

**Comment by kevinushey** [comment] 2021-03-09 02:43
Is this reproducible on every attempt to install the "glue" package? What happens if you call `renv::install("glue")`? Or `utils::install.packages("glue")`?

Alternatively, try again with:

```
options(renv.config.install.staged = FALSE)
renv::install("usethis")
```

**Comment by isaactpetersen** [comment] 2021-03-09 14:30
I tried creating a fresh R project for the package in Rstudio (File -> New Project -> New Directory -> R Package), and called it `mypackage`.

Here's my output when trying to install `usethis`:

```
> renv::install("usethis")
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/assertthat_0.2.1.zip' ...
	OK [downloaded 53.7 Kb in 1 secs]
Installing assertthat [0.2.1] ...
	FAILED
Error installing package 'assertthat':
======================================

* installing to library 'C:/R/Packages'
package 'assertthat' successfully unpacked and MD5 sums checked
Error: install of package 'assertthat' failed ["~/GitHub/mypackage/renv/staging/1/assertthat" does not exist]
> renv::install("glue")
Installing glue [1.4.2] ...
	OK [linked cache]
> renv::install("asssertthat")
Error: package 'asssertthat' is not available
```

`usethis` fails to install because it can't install `assertthat`. However, `glue` installs correctly. I tried those suggestions with `assertthat` (now that I have `glue` installed):

```
> utils::install.packages("assertthat")
Installing package into ‘D:/Documents/GitHub/mypackage/renv/library/R-4.0/x86_64-w64-mingw32’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/bin/windows/contrib/4.0/assertthat_0.2.1.zip'
Content type 'application/zip' length 54945 bytes (53 KB)
downloaded 53 KB

package ‘assertthat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Isaac\AppData\Local\Temp\RtmpcjQUSL\downloaded_packages
> renv::install("asssertthat")
Error: package 'asssertthat' is not available
```

This command you suggested appears to work for installing `usethis`:
```
> options(renv.config.install.staged = FALSE)
> renv::install("usethis")
Installing cli [2.3.1] ...
	OK [linked cache]
Installing clipr [0.7.1] ...
	OK [linked cache]
Installing crayon [1.4.1] ...
	OK [linked cache]
Installing curl [4.3] ...
	OK [linked cache]
Installing R6 [2.5.0] ...
	OK [linked cache]
Installing rprojroot [2.0.2] ...
	OK [linked cache]
Installing desc [1.3.0] ...
	OK [linked cache]
Installing fs [1.5.0] ...
	OK [linked cache]
Installing sys [3.4] ...
	OK [linked cache]
Installing askpass [1.1] ...
	OK [linked cache]
Installing openssl [1.4.3] ...
	OK [linked cache]
Installing jsonlite [1.7.2] ...
	OK [linked cache]
Installing credentials [1.3.0] ...
	OK [linked cache]
Installing rstudioapi [0.13] ...
	OK [linked cache]
Installing zip [2.1.1] ...
	OK [linked cache]
Installing gert [1.2.0] ...
	OK [linked cache]
Installing gitcreds [0.1.1] ...
	OK [linked cache]
Installing mime [0.10] ...
	OK [linked cache]
Installing httr [1.4.2] ...
	OK [linked cache]
Installing ini [0.3.1] ...
	OK [linked cache]
Installing gh [1.2.0] ...
	OK [linked cache]
Installing rlang [0.4.10] ...
	OK [linked cache]
Installing lifecycle [1.0.0] ...
	OK [linked cache]
Installing magrittr [2.0.1] ...
	OK [linked cache]
Installing purrr [0.3.4] ...
	OK [linked cache]
Installing rappdirs [0.3.3] ...
	OK [linked cache]
Installing whisker [0.4] ...
	OK [linked cache]
Installing withr [2.4.1] ...
	OK [linked cache]
Installing yaml [2.2.1] ...
	OK [linked cache]
Installing usethis [2.0.1] ...
	OK [linked cache]
```

So that works! However, when I try applying that approach to the installation of other packages, I get an error:

```
> options(renv.config.install.staged = FALSE)
> renv::install("brms")
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/brms_2.14.4.zip' ...
	OK [downloaded 5.6 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rstan_2.21.2.zip' ...
	OK [downloaded 5 Mb in 2.2 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/inline_0.3.17.zip' ...
	OK [downloaded 125.7 Kb in 1.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/RcppParallel_5.0.3.zip' ...
	OK [downloaded 5 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/loo_2.4.1.zip' ...
	OK [downloaded 1.5 Mb in 1.7 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/matrixStats_0.58.0.zip' ...
	OK [downloaded 1.5 Mb in 1.6 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/V8_3.4.0.zip' ...
	OK [downloaded 8.8 Mb in 2.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/StanHeaders_2.21.0-7.zip' ...
	OK [downloaded 2.3 Mb in 1.9 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/RcppEigen_0.3.3.9.1.zip' ...
	OK [downloaded 2.7 Mb in 1.9 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rstantools_2.1.1.zip' ...
	OK [downloaded 156.8 Kb in 1.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/bayesplot_1.8.0.zip' ...
	OK [downloaded 4.7 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/ggridges_0.5.3.zip' ...
	OK [downloaded 2.2 Mb in 1.9 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/plyr_1.8.6.zip' ...
	OK [downloaded 1.4 Mb in 1.6 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/reshape2_1.4.4.zip' ...
	OK [downloaded 795 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/shinystan_2.5.0.zip' ...
	OK [downloaded 1.3 Mb in 1.9 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/colourpicker_1.1.0.zip' ...
	OK [downloaded 1.8 Mb in 1.7 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/miniUI_0.1.1.1.zip' ...
	OK [downloaded 35.7 Kb in 0.8 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/shiny_1.6.0.zip' ...
	OK [downloaded 5.2 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/httpuv_1.5.5.zip' ...
	OK [downloaded 1.6 Mb in 1.7 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/sourcetools_0.1.7.zip' ...
	OK [downloaded 675.2 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/bslib_0.2.4.zip' ...
	OK [downloaded 3.6 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/sass_0.3.1.zip' ...
	OK [downloaded 2.3 Mb in 1.7 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/jquerylib_0.1.3.zip' ...
	OK [downloaded 512.5 Kb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/shinyjs_2.0.0.zip' ...
	OK [downloaded 1.1 Mb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/dygraphs_1.1.1.6.zip' ...
	OK [downloaded 431.5 Kb in 1.2 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/zoo_1.8-8.zip' ...
	OK [downloaded 1 Mb in 1.5 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/xts_0.12.1.zip' ...
	OK [downloaded 921.8 Kb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/gtools_3.8.2.zip' ...
	OK [downloaded 328.1 Kb in 1.2 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rsconnect_0.8.16.zip' ...
	OK [downloaded 632.9 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/packrat_0.5.0.zip' ...
	OK [downloaded 445.4 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/shinythemes_1.2.0.zip' ...
	OK [downloaded 967.3 Kb in 1.5 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/threejs_0.3.3.zip' ...
	OK [downloaded 926.1 Kb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/igraph_1.2.6.zip' ...
	OK [downloaded 8.9 Mb in 2.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/projpred_2.0.2.zip' ...
	OK [downloaded 1.2 Mb in 1.5 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/lme4_1.1-26.zip' ...
	OK [downloaded 5.1 Mb in 2.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/minqa_1.2.4.zip' ...
	OK [downloaded 835.1 Kb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/nloptr_1.2.2.2.zip' ...
	OK [downloaded 1.2 Mb in 1.6 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/statmod_1.4.35.zip' ...
	OK [downloaded 275.1 Kb in 1.2 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/optimx_2020-4.2.zip' ...
	OK [downloaded 817 Kb in 1.4 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/numDeriv_2016.8-1.1.zip' ...
	OK [downloaded 113.3 Kb in 1.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/rngtools_1.5.zip' ...
	OK [downloaded 76 Kb in 1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/gamm4_0.2-6.zip' ...
	OK [downloaded 56.5 Kb in 1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/RcppArmadillo_0.10.2.1.0.zip' ...
	OK [downloaded 2.5 Mb in 1.7 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/bridgesampling_1.0-0.zip' ...
	OK [downloaded 1.2 Mb in 1.5 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/Brobdingnag_1.2-6.zip' ...
	OK [downloaded 466.6 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/coda_0.19-4.zip' ...
	OK [downloaded 315.2 Kb in 1.2 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/nleqslv_3.3.2.zip' ...
	OK [downloaded 153.2 Kb in 1.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/abind_1.4-5.zip' ...
	OK [downloaded 62.3 Kb in 1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/future_1.21.0.zip' ...
	OK [downloaded 625.7 Kb in 1.3 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/globals_0.14.0.zip' ...
	OK [downloaded 93.5 Kb in 0.9 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/listenv_0.8.0.zip' ...
	OK [downloaded 104.1 Kb in 1.1 secs]
Retrieving 'https://cran.r-project.org/bin/windows/contrib/4.0/parallelly_1.23.0.zip' ...
	OK [downloaded 212.2 Kb in 1.1 secs]
Installing inline [0.3.17] ...
	FAILED
Error installing package 'inline':
==================================

* installing to library 'C:/R/Packages'
package 'inline' successfully unpacked and MD5 sums checked
Error: install of package 'inline' failed ["~/GitHub/mypackage/renv/library/R-4.0/x86_64-w64-mingw32/inline" does not exist]
```

**Comment by sstoeckl** [comment] 2021-05-31 15:07
I have exactly the same problem: I can install using `utils::install.package()` but not using renv:

```
> renv::install("tinytest")
Retrieving 'http://cran.rstudio.com/bin/windows/contrib/4.0/tinytest_1.2.4.zip' ...
	OK [file is up to date]
Installing tinytest [1.2.4] ...
	FAILED
Error installing package 'tinytest':
====================================

* installing to library 'C:/R/library'
Paket 'tinytest' erfolgreich entpackt und MD5 Summen überprüft
Fehler: install of package 'tinytest' failed ["C:/R/tinytest/renv/staging/1/tinytest" does not exist]
> options(renv.config.install.staged = FALSE)
> renv::install("tinytest")
Retrieving 'http://cran.rstudio.com/bin/windows/contrib/4.0/tinytest_1.2.4.zip' ...
	OK [file is up to date]
Installing tinytest [1.2.4] ...
	FAILED
Error installing package 'tinytest':
====================================

* installing to library 'C:/R/library'
Paket 'tinytest' erfolgreich entpackt und MD5 Summen überprüft
Fehler: install of package 'tinytest' failed ["C:/R/tinytest/renv/library/R-4.0/x86_64-w64-mingw32/tinytest" does not exist]
```

**Comment by kevinushey** [comment] 2021-06-01 18:46
Do you have an antivirus or something similar installed that could be interfering here? I don't have a great idea as to what could be causing this and also cannot reproduce locally.

**Comment by isaactpetersen** [comment] 2021-06-01 18:57
My R packages are installed in a nonstandard directory for Windows. My packages are installed in `C:R\Packages\` instead of `C:\Program Files\R\R-[version]/library`. I use `.libPaths("C:/R/Packages")` in `Rprofile.site` to change where R looks for my packages. By default, however, `renv` had the following setting according to `renv::diagnostics()`: `RENV_DEFAULT_R_LIBS_USER = C:\Program Files\R\Packages`. Thus, `renv` was not looking in the correct location. I updated this by setting `Sys.setenv(R_LIBS_USER = "C:/R/Packages")` in `Rprofile.site`. I don't remember if this solved that problem or not.

**Comment by sstoeckl** [comment] 2021-06-08 21:54
Thanks, that was exactly my issue (packags installed at `C:\R\library`). So I manually set `R_LIBS_USER` and `RENV_DEFAULT_R_LIBS_USER` to this path and everything works fine (I originally let R know in the global `Rprofile.site` via `.libPaths("C:\R\library")` but somehow `renv` ignores this and looks for packages in some users-directory.

**Comment by isaactpetersen** [comment] 2021-07-13 23:26
Yes, that's my approach, as well--I set the `.libPaths` in the `Rprofile.site` file. It's odd that the default R installation path on Windows is `C:\Program Files\R\` even though R's own documentation suggests installing it in a path without spaces: https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-install-R-for-Windows_003f. Is it necessary for {renv} to hardcode `RENV_DEFAULT_R_LIBS_USER = C:\Program Files\R\Packages`? (especially when the default path is not ideal according to R's installations instructions for Windows). Perhaps `{renv}` could set the `RENV_DEFAULT_R_LIBS_USER` variable based on the value of `.libPaths()` so that users do not need to set the `RENV_DEFAULT_R_LIBS_USER` value, especially if they are using a non-default path for libraries?

**Comment by pedrobtz** [comment] 2022-02-25 20:43
I observe the same behaviour as describe in the issue, even using options

```
options(renv.config.install.transacrional=FALSE)
options(renv.config.cache.symlinks=FALSE)
```

```
Error installing package 'ps':
================================

* installing to library 'c:/R/library'
package 'ps' successfully unpacked and MD5 sums checked
Error: install of package 'ps' failed ["<project/renv/library/R-3.6/x86_64-w64-mingw32>" does not exist]
```

After this line in the code

https://github.com/rstudio/renv/blob/2ed94de452c2efcfaf8b8fc6f4450136508ac6bf/R/r.R#L16

```r
Sys.getenv("R_LIBS_USER") # return ""
```

but

```r
system2(R(), c("--vanilla", "-e Sys.getenv('R_LIBS_USER')")). # returns 'c:/R/library'
```

Maybe it would be easier to set the library path with 'R CMD INSTALL -l lib'.

**Comment by kevinushey** [comment] 2022-02-25 20:50
That change has been made in the development version of `renv`, and I'm currently waiting for CRAN to accept the submission. Unfortunately, it's been held up by test failures in a dependent package.

**Comment by kevinushey** [comment] 2022-04-06 18:03
This should now be fixed on CRAN.

**Closed by kevinushey** 2022-04-06 18:03 UTC
