### ISSUE TITLE
can I generate a dockerfile from renv

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/renv#548] opened 2020-10-01 06:21 UTC
There is a docker section on the website available, I read it but it was hard for docker beginners to get through.

I was wondering if there is a function in renv that can produce the dockerfile. since it already has all the information necessary to produce one?

**Comment by matthewstrasiotto** [comment] 2020-10-02 08:47
`renv` doesn't implement any functionality that would generate a dockerfile, and I'm not sure if that would actually be useful. 

I wouldn't really say renv has **all** the information needed to produce a dockerfile, either- It covers the `R` environment side of things, but you're still going to need your container to take care of runtime dependencies, libraries, etc.

I'd say that best-case, it might be feasible to generate  a rough "template" for a dockerfile, that might help bootstrap the recorded R version (installing old versions of R via package managers is surprisingly tedious), and copy the lockfile into the container, but even then, R installation varies distro-to-distro & it wouldn't be much better than building your own.


Your best bet is probably to find a more generic dockerfile for your R version, place that in your project dir, & use that as a starting point- usually the best way to understand virtualization spec files is to just work through modifiying one & trial & error it (with the documentation open on your other screen)

**Comment by vikram-rawat** [comment] 2020-10-02 13:19
I am good. I created my own dockerfile. It wasn't hard though. I was just wondering if there is such a function. or if you could add that as a feature request. because renv records everything about R env. But then again it's entirely up to you...

Thanks for replying so quickly though

**Comment by kevinushey** [comment] 2020-10-03 01:19
It would probably be worthwhile for `renv` to include some (annotated?) Dockerfiles, that users could copy + paste and modify as a template. Or even link to Dockerfiles in the wild that successfully use `renv`.

**Comment by vikram-rawat** [comment] 2020-10-06 12:07
```

FROM rocker/r-base

### install dependencies using RUN command for linux system
# RUN apt-get update && apt-get install -y libpq-dev 

### set env variable that you can use during docker run command
# ENV RENV_PATHS_CACHE=/renv/cache

### to install the packages for R add more command you wish to run like `shiny::runApp()`
RUN R -e "install.packages('Rserve', repos = 'http://www.rforge.net/', type = 'source'); \
    install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org')); \
    Sys.setenv(RENV_PATHS_CACHE = '/renv/cache'); \
    install.packages('renv', repos = c(CRAN = 'https://cloud.r-project.org')); \
    renv::restore();"


WORKDIR /RProject
COPY . .

# EXPOSE 9090
# CMD ["Rscript", "-e", "source('app.R');"]

```

something like this would surely help. You may add more info from the thing renv records.

**Comment by hadley** [comment] 2023-04-28 13:02
Looks like a duplicate of #599

**Closed by hadley** 2023-04-28 13:02 UTC
