### ISSUE TITLE
Error installing/restoring DevOps package

### ISSUE THREAD

**Issue by mkoohafkan** [rstudio/renv#1042] opened 2022-07-05 18:13 UTC
I can install packages from my organization's DevOps platform using `remotes::install_git()`, and it even shows up in my `renv` lockfile:

```
...
    "mypackage": {
      "Package": "mypackage",
      "Version": "1.0-1",
      "Source": "Git",
      "RemoteType": "xgit",
      "RemoteUrl": "http://MyDevOps/tfs/My%20Collection/MyProject/_git/mypackage",
      "RemoteSha": "f28345bb09a853e0871ce925a3bafcc0bc104e94",
      "Hash": "66b83b02b1927afbb0a94a0aa985d1eb",
      "Requirements": [
        "dplyr",
        "glue",
        "odbc",
        "purrr",
        "sf"
      ]
    },
...
```
However, I get an error when I try to restore my environment:

```r
renv::remove("mypackage")
renv::restore()
#> The following package(s) will be updated:
#> 
#> # Git ================================
#> - mypackage   [* -> 1.0-1]
#> 
#> Do you want to proceed? [y/N]: y
#> Cloning 'http://MyDevOps/tfs/My%20Collection/MyProject/_git/mypackage' ...
#> error: remote origin already exists.
#> Error: error cloning 'mypackage' from 'http://MyDevOps/tfs/My%20Collection/MyProject/_git/mypackage' [status code 3]
#> Traceback (most recent calls last):
#> 9: renv::restore()
#> 8: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
#> 7: retrieve(packages)
#> 6: handler(package, renv_retrieve_impl(package))
#> 5: renv_retrieve_impl(package)
#> 4: renv_retrieve_git(record)
#> 3: renv_retrieve_git_impl(record, path)
#> 2: stopf(fmt, package, url, status)
#> 1: stop(sprintf(fmt, ...), call. = call.)
```

**Comment by kevinushey** [comment] 2022-07-05 19:58
What version of `renv` are you using, and what version of `git`? What operating system?

**Comment by kevinushey** [comment] 2022-07-05 20:01
For reference, you can see how `renv` tries to clone packages here:

https://github.com/rstudio/renv/blob/main/R/retrieve.R#L342-L404

Presumedly, the call to `git remote add origin` is failing for some reason, but I don't have a good idea as to why that could fail on an empty git repository.

**Comment by mkoohafkan** [comment] 2022-07-05 21:05
Huh, it works on my regular desktop:
- Windows 10
- R 4.2.0
- renv 0.15.4
- Git 2.36.0.windows.1

But it consistently fails on my server box (which also has a slightly older version of Git):
- Windows Server 2016
- R 4.2.0
- renv 0.15.4
- Git 2.33.1.windows.1

I unfortunately can't test if the Git version is the culprit as I can't risk disrupting the server box at this time. Using `remotes::install_git()` is a decent workaround for now. 

My use case is that I am cloning a DevOps git repository (we'll call it "anotherpackage", and the renv lockfile includes a reference to a second repository containing "mypackage" (also on DevOps). Perhaps there is an issue with trying to provide two different definitions of the a remote named "origin"? And perhaps that is resolved in newer git versions.

```
$ git remote -v
origin  http://MyDevOps/tfs/My%20Collection/MyProject/_git/anotherpackage (fetch)
origin  http://MyDevOps/tfs/My%20Collection/MyProject/_git/anotherpackage (push)
```

**Comment by kevinushey** [comment] 2022-07-07 17:35
You can see the steps that `renv` is trying to run here:

https://github.com/rstudio/renv/blob/main/R/retrieve.R#L362-L368

Can you reproduce a similar error by hand on your server box? Does changing the remote name make a difference?

The error is weird to me as we're just initializing a "bare" repository and then setting a remote for that.

**Comment by jabenninghoff** [comment] 2022-12-22 19:10
I experienced a very similar error using `setup-renv@v2` from https://github.com/r-lib/actions. When using the following code in my `renv.lock`, I get an error:

```
    "USAboundariesData": {
      "Package": "USAboundariesData",
      "Version": "0.4.0",
      "Source": "Repository",
      "RemoteType": "repository",
      "RemoteUrl": "https://github.com/ropensci/USAboundariesData",
      "RemoteRef": "main",
      "RemoteSha": "064cdbcbb283f867493f81d0fff9b9ec9d9a6b08",
      "Hash": "7ad0c28cb4dd15e7a1ece4c392c21785",
      "Requirements": []
    },
```

[Errors](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595) with:

```
Cloning 'https://github.com/ropensci/USAboundariesData' ...
[392](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:398)
error: remote origin already exists.
[393](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:399)
Warning: Warning: failed to find binary for 'USAboundariesData 0.4.0' in package repositories
[394](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:400)
Warning: Warning: failed to find source for 'USAboundariesData 0.4.0' in package repositories
[395](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:401)
Error: Error: failed to retrieve package 'USAboundariesData@0.4.0'
[396](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:402)
In addition: Warning messages:
[397](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:403)
1: curl: (22) The requested URL returned error: 404 
[398](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:404)
2: error cloning 'USAboundariesData' from 'https://github.com/ropensci/USAboundariesData' [status code 3] 
[399](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:405)
Traceback (most recent calls last):
[400](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:406)
8: renv::restore()
[401](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:407)
7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
[402](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:408)
6: retrieve(packages)
[403](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:409)
5: handler(package, renv_retrieve_impl(package))
[404](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:410)
4: renv_retrieve_impl(package)
[405](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:411)
3: renv_retrieve_repos(record)
[406](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:412)
2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
[407](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:413)
1: stop(sprintf(fmt, ...), call. = call.)
[408](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:414)
Execution halted
[409](https://github.com/jabenninghoff/rtraining/actions/runs/3759719830/jobs/6389623595#step:5:415)
Error: Process completed with exit code 1.
```

Notably, this only fails on Windows, the macOS GitHub action worked fine.

Reinstalling the package as a GitHub repository fixes the problem. Using:

```
    "USAboundariesData": {
      "Package": "USAboundariesData",
      "Version": "0.4.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "ropensci",
      "RemoteRepo": "USAboundariesData",
      "RemoteRef": "main",
      "RemoteSha": "064cdbcbb283f867493f81d0fff9b9ec9d9a6b08",
      "Hash": "a2fff0d88decd1c8055e2505bf5842bf",
      "Requirements": []
    },
```

Works [as expected](https://github.com/jabenninghoff/rtraining/actions/runs/3760247189/jobs/6390743973).

**Comment by hadley** [comment] 2023-04-28 12:46
Is this still a problem for y'all?

**Comment by hadley** [comment] 2023-05-15 12:09
Since it's been a couple of weeks and we haven't anything more, I'm going to close this issue.

**Closed** 2023-05-15 20:25 UTC
Labels: reprex
