### ISSUE TITLE
create lockfile from subset of package requirements

### ISSUE THREAD

**Issue by kevinushey** [rstudio/renv#507] opened 2020-08-05 16:27 UTC
For my workflow I try to disregard the global package library as soon as renv gets involved. As soon as a project switches to renv, it is tied to a stable RSPM snapshot and should get all packages from there, no matter what I might have installed in the global package library (which I tend to keep up-to-date-ish).

For users who have very few (or just one) project they're working on and who want to switch to renv, the current implementation (=consulting the local library) is better, because this avoid surprises when switching to renv. My objective is to minimize the set of package universes I'm using across all my projects, this is more important than exact replication of the current state of the package library. I might install GitHub packages on a case-by-case basis.

Ideally, for starting use of renv in a particular project, I'd do a variant of:

- `init(bare = TRUE, repos = c(RSPM = "https://packagemanager.rstudio.com/all/301"))` (bare-bones infrastructure with empty library and repo pointing to latest snapshot I've used in other projects)
- `record()` (auto-detect and record dependencies)
- `restore()` (to check if `restore()` will work on my colleague's machines)
- Run tests on the project (to check if any problems arise from potentially different package versions)

From time to time, I'd lift a project to a more recent RSPM snapshot:

- Edit `renv.lock`
- `update()`

Does this make sense?

_Originally posted by @krlmlr in https://github.com/rstudio/renv/issues/469#issuecomment-668976971_

**Comment by krlmlr** [comment] 2020-08-18 16:55
Today I successfully ran the following with CRAN renv:

```r
renv::init(bare = TRUE)
renv::snapshot() # necessary to create .lock file
# Edit renv.lock to include RSPM snapshot and remove bogus installation of MASS (!?!)
renv::install("rmarkdown")
deps <- renv::dependencies()$Package
avail <- available.packages()
renv::record(as.list(avail[intersect(deps, rownames(avail)), "Version"]))
renv::restore()
renv::snapshot()
```

Works for me, of course a simpler (and less manual) approach would be great.

**Comment by hadley** [comment] 2023-04-28 13:45
I _think_ this is a snapshot feature because I'd be cool if you could write `renv::snapshot(date = "2020-01-01")` and it would use the CRAN packages from that date.

**Comment by kevinushey** [comment] 2023-04-28 18:23
FWIW the way I imagine this working would be something like:

```
# download and install packages from some snapshot
renv::checkout(date = "2020-01-01")

# call snapshot to update the lockfile
renv::snapshot()
```

This is because `renv::snapshot()`'s job normally is to save the state of your library paths, which implies that you'd need to first install packages into the library paths.

In theory we could side-step that, in which case the workflow would be reversed like:

```
# create a lockfile for a snapshot
renv::snapshot(date = "2020-01-01")

# call restore to install those packages
renv::restore()
```

But that feels backwards somehow to me. (But I also see the utility of being able to generate a lockfile without needing to install all of the packages required.)

**Comment by hadley** [comment] 2023-04-28 19:59
Oh yeah, because you do want to try out your code with the new versions before you commit them to the lockfile.

**Comment by hadley** [comment] 2023-05-01 22:05
I now believe that this is a duplicate of #413

**Closed by hadley** 2023-05-01 22:05 UTC
Labels: feature, checkout :checkered_flag:
