### ISSUE TITLE
renv::install(type = "binary") error when package max binary version is less than max source version

### ISSUE THREAD

**Issue by James-CAU** [rstudio/renv#461] opened 2020-06-24 14:29 UTC
I am developing a package, and I am trying to install dependant packages using renv::install(type = "binary").  I am getting an error when it tries to install "odbc". I think the reason for this is the maximum binary odbc version is 1.2.2, but the maximum source is 1.2.3. I think renv tries to find a binary version 1.2.3 and fails. 

Note, renv::install("odbc@1.2.2", type = "binary") works, however, if I re-run renv::install(type = "binary") to install the other dependencies it will try and install the 1.2.3 version and fail. 

I have also tried installing the source version of odbc, however, I am getting a compiling error because R is installed in Program Files which has a space (as explained [here](https://stackoverflow.com/questions/22782537/error-after-running-build-to-create-r-package-in-rstudio)). This is on a remote machine so it is not easy to change. 

Any help would be much appreciated! 

### repex:
library(renv)
renv::activate()
renv::install("odbc", type = "binary")

Even though the maximum binary version is 1.2.2, it will try to install version 1.2.3.

**Comment by James-CAU** [comment] 2020-06-24 15:02
A potentially quick fix for me would be a way of specifying packages to _not_ install using renv::install. That way I could install version 1.2.2 of odbc, then make sure I don't get an error from renv::install.

**Comment by kevinushey** [comment] 2020-06-25 22:42
Thank you for the bug report! I've reproduced this locally and believe this should now be fixed in the development version of `renv` (soon to be on CRAN).

Please feel free to re-open if you're still having issues.

**Closed by kevinushey** 2020-06-25 22:42 UTC

**Comment by James-CAU** [comment] 2020-06-26 08:20
Thank you for taking a look at this so quickly! Unfortunately, I am still getting an error so please can you reopen the issue? 

It seems to be fixed now for install.packages(), however, I am still running into the error when I run renv::install(packages = c("odbc"), type = "binary"). If you could have another look, that would be much appreciated!

**Comment by kevinushey** [comment] 2020-06-26 16:01
I think I might need more information. The following works for me:

```
> renv::install(packages = c("odbc"), type = "binary")
Retrieving 'https://mran.microsoft.com/snapshot/2020-06-24/bin/macosx/contrib/4.0/odbc_1.2.3.tgz' ...
	OK [downloaded 1.9 Mb in 0.6 secs]
Installing odbc [1.2.3] ...
	OK [installed binary]
```

Can you provide more information? What is the output of `sessionInfo()`?

**Comment by James-CAU** [comment] 2020-06-26 17:06
I have just tried again using the new CRAN version (0.11.0) and it now works! Previously I was just trying your interim GitHub version and was still getting the error, but it looks like I just had to be patient. 

Thanks again for all your help!

**Comment by kevinushey** [comment] 2020-06-26 21:30
Phew! Very glad to hear it. Thanks for the bug report!
