### ISSUE TITLE
json parsing error for a github repo on r-devel

### ISSUE THREAD

**Issue by tjmahr** [rstudio/renv#956] opened 2022-03-03 16:42 UTC
I've been trying R-devel (Windows UCRT) out and I run into the following error:

```
> renv::install("gadenbuie/cleanrmd")
Error in parse(text = text, keep.source = FALSE, srcfile = NULL) : 
  failed to resolve remote 'gadenbuie/cleanrmd' -- 1:23: unexpected input
1: list("id"=202610256,""
```
That last box  is one of the `\032` insertions. 

I can trace the problem all the way down to `renv:::renv_json_read()` where it seems to be converting a json string into an R list.

This code works on 4.1.2. 

```
> sessionInfo()
R Under development (unstable) (2022-03-02 r81842 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0    rlang_1.0.1    renv_0.15.4
```

**Comment by kevinushey** [comment] 2022-03-03 20:54
Thanks for the bug report -- I've been able to reproduce this as well. I'll take a look.

**Comment by kevinushey** [comment] 2022-03-03 21:14
It looks like this could be a bug in R's default regular expression engine on Windows. I've filed a bug here:

https://bugs.r-project.org/show_bug.cgi?id=18311

Fortunately we should be able to work around this.

**Comment by kevinushey** [comment] 2022-03-03 21:34
Should be fixed by https://github.com/rstudio/renv/commit/f9b4daebd349b889c55afc7792f526cafb4e808b -- thanks for the report!

**Closed by kevinushey** 2022-03-03 21:34 UTC
