### ISSUE TITLE
Issue with BPCells Package Installation via renv

### ISSUE THREAD

**Issue by GischD** [rstudio/renv#1941] opened 2024-07-04 17:12 UTC
A package that I previously installed with renv (BPCells) is returning the following error:

```
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
```
Tracheback
```
Traceback (most recent calls last):
12: renv::install("bnprks/BPCells/r")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
```
The package has been moved from its original GitHub directory "bnprks/BPCells" to "bnprks/BPCells/r", and I believe this caused the error. As I'm installing it via renv, this folder exchange may affect the package installation process.

Please help me understand this error and how I might work around the problem. Any guidance on how to report this issue to BPCells or any potential solutions would be greatly appreciated.

Thank you,
Debora

**Comment by bnprks** [comment] 2024-07-08 19:53
Hi renv team, I'm the author of the BPCells repository, and I've narrowed things down to a pretty easy reproducible example. The core problem here is that with nested R packages, renv seems to be unable to install the package in the subdirectory.

My demo repository setup is here: https://github.com/bnprks/renv.test/

Running `renv::install("bnprks/renv.test:r")` will fail while running the `configure` file from the root directory (not sure why it would ever run this when it's supposed to install from a subdir).

However, if we run from a commit where there aren't R package-related files in the root dir everything is fine: `renv::install("bnprks/renv.test:r@ba11467")`

I've included a few more details in the linked repository, but hopefully this will help with your debugging - I've cut things down to just 5 minimal files in that repository.

**Comment by kevinushey** [comment] 2024-07-09 03:50
Thanks @bnprks -- I think this should be resolved via https://github.com/rstudio/renv/commit/80f6bef489f2733c081b8da2ba27f1aeda13caf0; would you be able to test?

**Comment by bnprks** [comment] 2024-07-09 05:43
Yep, everything seems to be working with that commit, thanks @kevinushey!

**Comment by kevinushey** [comment] 2024-07-09 08:21
Great, thank you for confirming!

**Closed by kevinushey** 2024-07-09 08:21 UTC

**Comment by josh-gree** [comment] 2024-07-29 21:27
Hi, I am hitting this issue and I thought I could install the dev version of renv and it would be fixed? I am in a Dockerfile;

```
FROM r-base:4.4.1

RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv')"
```

the BPcells section of my lock looks like this;

```
    "BPCells": {
      "Package": "BPCells",
      "Version": "0.2.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "BPCells",
      "RemoteUsername": "bnprks",
      "RemoteRef": "HEAD",
      "RemoteSha": "b78bc8321db802c6ebf29edc2296394f2e8587c6",
      "RemoteSubdir": "r",
      "Requirements": [
        "Matrix",
        "R",
        "RColorBrewer",
        "Rcpp",
        "RcppEigen",
        "dplyr",
        "ggplot2",
        "ggrepel",
        "grDevices",
        "hexbin",
        "lifecycle",
        "magrittr",
        "methods",
        "patchwork",
        "readr",
        "rlang",
        "scales",
        "scattermore",
        "stringr",
        "tibble",
        "tidyr",
        "vctrs"
      ],
      "Hash": "919f33ce16f0d4d0b581bbbfe79c5dc0"
    },
```


And I get the following error on `RUN R -e "renv::restore()"`

```
1212.2 
1212.2 * installing *source* package ‘BPCells.installation.moved’ ...
1212.2 ** using staged installation
1212.2 
1212.2 
1212.2 ################################################
1212.2 Error: BPCells installation location has moved.
1212.2 
1212.2 To install from the new location, please run:
1212.2 
1212.2     remotes::install_github("bnprks/BPCells/r")
1212.2 
1212.2 ################################################
1212.2 
1212.2 
1212.2 ERROR: configuration failed for package ‘BPCells.installation.moved’
1212.2 * removing ‘/project/renv/staging/1/BPCells.installation.moved’
1212.2 install of package 'BPCells' failed [error code 1]
1212.2 FAILED
1212.2 Traceback (most recent calls last):
1212.2 13: renv::restore()
1212.2 12: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
1212.2 11: renv_install_impl(records)
1212.2 10: renv_install_staged(records)
1212.2  9: renv_install_default(records)
1212.2  8: handler(package, renv_install_package(record))
1212.2  7: renv_install_package(record)
1212.2  6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
1212.2  5: renv_install_package_impl(record)
1212.2  4: r_cmd_install(package, path)
1212.2  3: r_exec_error(package, output, "install", status)
1212.2  2: abort(all)
1212.2  1: stop(fallback)
1212.2 Execution halte
```

Any help would be appreciated?

**Comment by bnprks** [comment] 2024-08-01 00:11
Hi @josh-gree, have you checked what version of renv is present in your lockfile? I suspect if you have an old version listed you may wind up downgrading your `renv` version prior to other package installs when you run `renv::restore()`.

I have gotten the correct behavior from within the `r-base:4.4.1` docker image with an renv.lock section as shown below:

(In my setup I didn't have libhdf5 installed so the build ultimately failed, but it was at least building from the right subdirectory)

<details>
<summary> renv.lock (expand for details) </summary>

```
    "renv": {
      "Package": "renv",
      "Version": "1.0.7.9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "renv",
      "RemoteRef": "main",
      "RemoteSha": "0cf1760bcb97d5bbd5d8cb0ac8d5aafdba864fa4",
      "Requirements": [
        "utils"
      ],
      "Hash": "413f86671dfb0dcc3bfe39cb12abba46"
    },
```
and 
```
    "BPCells": {
      "Package": "BPCells",
      "Version": "0.2.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "bnprks",
      "RemoteRepo": "BPCells",
      "RemoteSubdir": "r",
      "RemoteRef": "main",
      "RemoteSha": "f6a84e1485225d7fc2094daf48908b964c7ccde1",
      "Requirements": [
        "Matrix",
        "R",
        "RColorBrewer",
        "Rcpp",
        "RcppEigen",
        "dplyr",
        "ggplot2",
        "ggrepel",
        "grDevices",
        "hexbin",
        "lifecycle",
        "magrittr",
        "methods",
        "patchwork",
        "readr",
        "rlang",
        "scales",
        "scattermore",
        "stringr",
        "tibble",
        "tidyr",
        "vctrs"
      ],
      "Hash": "7008367a370d10bd5797bef05fee2bfa"
    },

```

</details>

**Comment by kevinushey** [comment] 2024-10-16 17:35
Seems like an issue in the BPCells package. You should contact the package maintainer.

**Comment by GischD** [comment] 2024-10-17 15:33
Hi @kevinushey

The @josh-gree is the BPCells maintainer; the issue was fixed after this ticket.
Thank you all for the effort you put into fixing the issue.
