### ISSUE TITLE
Fallback on other repository if MRAN is not available or a specific package from it can't be installed

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/renv#957] opened 2022-03-04 16:46 UTC
It seems like some packages are not available for MRAN, or maybe the whole service is currently down:
```
* Querying repositories for available binary packages ... Done!
Retrieving 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.cache_0.15.0.tgz' ...
* Querying repositories for available source packages ... Done!
Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/R.cache_0.15.0.tar.gz' ...
	OK [downloaded 33.8 Kb in 0.3 secs]
Retrieving 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.methodsS3_1.8.1.tgz' ...
Retrieving 'https://packagemanager.rstudio.com/all/latest/src/contrib/Archive/R.cache/R.cache_0.15.0.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.oo_1.24.0.tgz' ...
Warning: Warning: failed to find binary for 'R.cache 0.15.0' in package repositories
Warning: Warning: failed to retrieve 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.cache_0.15.0.tgz' [error code 22]
Warning: Warning: failed to find binary for 'R.methodsS3 1.8.1' in package repositories
Warning: Warning: failed to retrieve 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.methodsS3_1.8.1.tgz' [error code 22]
Warning: Warning: failed to find binary for 'R.oo 1.24.0' in package repositories
Warning: Warning: failed to retrieve 'https://mran.microsoft.com/snapshot/2021-12-08/bin/macosx/contrib/4.1/R.oo_1.24.0.tgz' [error code 22]
Error: Error: failed to retrieve package 'R.cache@0.15.0'
```
From https://github.com/lorenzwalthert/precommit/runs/5425193681?check_suite_focus=true.

Clicking on an MRAN URL in a browser yields `The specified CGI application encountered an error and the server terminated the process.`.

Can there be a fallback if a package is not installable from MRAN?

**Comment by kevinushey** [comment] 2022-03-04 17:15
Thanks -- I'll take a look.

**Comment by hadley** [comment] 2023-04-26 12:56
Now duplicate of #1179

**Closed by hadley** 2023-04-26 12:56 UTC
