### ISSUE TITLE
Problem moving 12.x to 13.0 - Error in startsWith(contriburl, "file:") : non-character object(s)

### ISSUE THREAD

**Issue by slodge** [rstudio/renv#724] opened 2021-04-20 07:39 UTC
I'm trying to debug an issue in our CI system at present.

This CI system uses a container to build our R packages. Each R package project is wrapped in its own renv environment and this system has been working well.

The CI build script basically does a `devtools::build` and then afterwards does a `install.packages` to check that the package actually is built and installable.

```
message("Building ", packageToBuild, " into ", packagePath)
built_path <- devtools::build(packageToBuild, path = packagePath, vignettes = FALSE)

message("Built path was ", built_path)

message("Build complete - now let's install the package")
built_packages <- list.files(path = packagePath, pattern = "*.tar.gz", full.names = TRUE)
message("Found built packages: ", built_packages)
message("Installing...")
install.packages(built_packages, repos=NULL, type="source")
message("Installed... but did it really... let's check if it worked")
```

This code has been working well under 12.x.

However, after upgrading renv to 13.0 (or later - have tried 13.1 and 13.2), then we see an error of `Error in startsWith(contriburl, "file:") : non-character object(s)`

```
Built path was /__w/180/a/package/P.DetailReport_0.4.34.tar.gz
Build complete - now let's install the package
Found built packages: /__w/180/a/package/P.DetailReport_0.4.34.tar.gz
Installing...
Installing package into ‘/__w/180/s/P.DetailReport/renv/library/R-4.0/x86_64-pc-linux-gnu’
(as ‘lib’ is unspecified)
Error in startsWith(contriburl, "file:") : non-character object(s)
Calls: install.packages ... delegate -> eval -> eval -> <Anonymous> -> startsWith
Execution halted
```

Looking around it feels like this might be caused in a base R `available.packages` call somewhere - see  `localcran <- startsWith(repos, "file:")` in https://svn.r-project.org/R/trunk/src/library/utils/R/packages.R 

I've fixed our build to use `renv::install` instead - that succeeds without the error - but thought I'd report this as it might help others who come across a similar problem...

I've looked through the release notes on https://rstudio.github.io/renv/news/index.html and not seen what might have caused this.... but am still reading...

**Comment by kevinushey** [comment] 2021-04-20 16:13
Thanks; I was able to reproduce locally as well. It looks like this is a problem with the `renv` shim.

```
> install.packages("~/r/pkg/renv", repos = NULL, type = "source")
Installing package into '/Users/kevinushey/scratch/blk/renv/library/macos/R-4.0/x86_64-apple-darwin17.0'
(as 'lib' is unspecified)
Error in startsWith(contriburl, "file:") : non-character object(s)
```

I'll see if I can figure out what's going on.

**Comment by slodge** [comment] 2021-04-20 16:16
Thanks - there's no hurry from us on this - switching to `renv::install()` seems to be working well 👍

**Comment by kevinushey** [comment] 2021-04-20 16:23
Thanks again for the bug report! Should be fixed in the development version of `renv`.

**Closed by kevinushey** 2021-04-20 16:23 UTC

**Comment by slodge** [comment] 2021-04-20 19:57
Tested... and yes - it works!

Thanks 👍
