### ISSUE TITLE
`renv::restore()` returns `Error in if (source %in% c("git2r", "xgit")) source <- "git" :`

### ISSUE THREAD

**Issue by jyotishkarc** [rstudio/renv#1710] opened 2023-10-05 19:17 UTC
I tried writing `renv::status()`, and it returned
```
The following package(s) are missing:

The following package(s) are missing:

 package     installed recorded used
 BiocVersion n         y        ?   
 ondisc      n         n        y   
 OneR        n         y        y   
 Rhdf5lib    n         y        ?   

See ?renv::status() for advice on resolving these issues.
```

As per the official documentation, I wrote `renv::restore()` first, but it returned the following error:
```
Error in if (source %in% c("git2r", "xgit")) source <- "git" : 
  argument is of length zero
```

Please let me know if this is a machine-specific problem or a bug. Thanks!

**Comment by kevinushey** [comment] 2023-10-05 19:39
It sounds like a bug, but without more information it's unlikely I'll be able to fix it. Any chance you can try and share a reproducible example? What are the contents of your `renv.lock` lockfile?

**Comment by jyotishkarc** [comment] 2023-10-05 23:10
Here's a copy of my `renv.lock` file: [renv.lock](https://drive.google.com/file/d/1sUjMaFuRKdwPDHpnZSpAFDHXDptcCzvh/view?usp=drive_link)

Somehow, I have a hunch that there might be something wrong with the package `forcats`. Could someone please help?

**Comment by kevinushey** [comment] 2023-10-06 16:17
Did you edit this lockfile by hand? It looks like it's corrupt:

```
    "forcats": {
      "Package": "forcats",
      "Version": "1.0.0",
    "fontawesome": {
      "Package": "fontawesome",
    < ... >
```

Note that there is no closing bracket for the "forcats" entry.

If not, do you know how it was generated?

**Comment by jyotishkarc** [comment] 2023-10-14 12:01
Thanks for your message. You're right. I probably made some errors while removing the auto-generated lines (such as `<<<<<<HEAD`). I have fixed it though.

**Closed** 2023-10-14 14:35 UTC
