### ISSUE TITLE
renv::status() has no issues, but R CMD build package will fail?

### ISSUE THREAD

**Issue by sysilviakim** [rstudio/renv#1758] opened 2023-11-19 12:03 UTC
![Screenshot 2023-11-19 at 8 44 41 PM](https://github.com/rstudio/renv/assets/20317183/95dbb04c-7192-4a73-9cd5-8097f5ac640a)

Hello everyone,

I have a weird issue. I've recently started working across operating systems, and a package that I'm building will show no issues in 

1. renv::status()
2. Windows build

but fail to build in a MacOS Sonoma 14.1.1. It will build without any issues with a ctrl shift b (R CMD INSTALL --preclean --no-multiarch --with-keep.source packagename) but spectacularly fail with an R CMD build, claiming that the packages recorded in the lockfile are not installed. They are! 

I'm not entirely sure what's going on. In the Mac, I have nothing in the `~/.R/`, and my .Rprofile is

```
source("renv/activate.R")

options(
  repos = c(RSPM = "https://packagemanager.rstudio.com/all/latest",
            CRAN = "https://cran.rstudio.com/"),
  renv.config.auto.snapshot = TRUE
)

# Since RSPM does not provide Mac binaries, always install packages from CRAN
# on mac or windows, even if renv.lock specifies they came from RSPM
if (Sys.info()[["sysname"]] %in% c("Darwin", "Windows")) {
  options(renv.config.repos.override = c(
    CRAN = "https://cran.rstudio.com/",
    INLA = "https://inla.r-inla-download.org/R/testing"))
} else if (Sys.info()[["sysname"]] == "Linux") {
  options(renv.config.repos.override = c(
    RSPM = "https://packagemanager.rstudio.com/all/latest",
    INLA = "https://inla.r-inla-download.org/R/testing"))
}
```

`.libPaths()` gives me 
```
[1] "/Users/sskim1/Library/Caches/org.R-project.R/R/renv/library/ranking-410df1bc/R-4.3/aarch64-apple-darwin20"
[2] "/Users/sskim1/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.3/aarch64-apple-darwin20/ac5c2659" 
```

When restarted, `sessionInfo()` gives me

```
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Asia/Seoul
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2    tools_4.3.2       rstudioapi_0.15.0
[4] renv_1.0.3  
```

It's my first time using a Mac, so I might be missing something obvious, but it's weird that it builds fine in a Windows and not on a Mac. Anybody have ideas as to why this might be? 

Thank you very much.

**Comment by kevinushey** [comment] 2023-11-20 17:49
Thanks for the bug report -- I'll try to see if we can figure out what's going on here.

**Comment by kevinushey** [comment] 2023-12-04 21:05
Sorry for the delay; however, I'm not able to reproduce locally. Are you able to provide any other details?

**Comment by mjkallen** [comment] 2024-01-10 08:58
I am experiencing the same problem on a Linux-based system (Ubuntu 20.04.1) and it happens only when running `R CMD build` on a package with at least one vignette and `VignetteBuilder: knitr` in the DESCRIPTION file. Adding `--no-build-vignettes` to `R CMD build` obviously resolves the issue, but then the vignettes aren't built.

Hope this additional information helps!

**Comment by kevinushey** [comment] 2024-01-10 17:56
Ah! Thank you very much; I'm able to reproduce locally now.

**Comment by kevinushey** [comment] 2024-01-10 18:13
I think this should be fixed in the development version of `renv`. If you'd like to test, you can use:

```
renv::upgrade(version = "main")
```

If you need to roll back, you can use:

```
renv::upgrade(version = "1.0.3")
```

**Comment by mjkallen** [comment] 2024-01-12 09:24
Hi Kevin and thanks for looking into this. I have upgraded to the main branch as you suggested and gave it a try, but it now fails because it doesn't seem to bootstrap `renv` anymore when I execute `R CMD build`. It just immediately fails due to a missing dependency. Does this give you enough information to look into the issue?

**Comment by kevinushey** [comment] 2024-01-12 19:03
Hmm... the intention here was that bootstrapping `renv` should not be necessary; as long as the requisite packages are installed into the current library paths, those should also be visible when the package is built.

Can you provide some more details, just so I can be sure I fully understand the issue? I was able to get this to work locally, so I must be missing something.

**Comment by kevinushey** [comment] 2024-01-16 23:31
> However, now renv::status() tells me that the package from my local CRAN-like repository isn't installed.

To confirm, are you seeing this output on startup?

```
- Project '<projectDir>' loaded. [renv 1.0.3.9000]
```

Is that package installed? If so, is it installed into your project library, or into an alternate library path? The output of `renv::diagnostics()` might be helpful here.

It sort of sounds like the `renv` autoloader is not running for some reason in your specific configuration.

**Comment by mjkallen** [comment] 2024-01-18 10:00
Hi Kevin, thanks for your comment. It does look like my setup was not in a good state. Reloading the project in RStudio seems to have resolved the problem, but I cannot tell you what that problem was. In any case, your fix has resolved this issue for me.

**Comment by kevinushey** [comment] 2024-01-18 17:00
Strange! I'm glad to hear things are now sorted on your end -- thanks for reporting back.

**Closed by kevinushey** 2024-01-18 17:00 UTC
Labels: bug
