### ISSUE TITLE
use.cache disregarded by renv::restore()

### ISSUE THREAD

**Issue by colearendt** [rstudio/renv#159] opened 2019-08-21 13:28 UTC
Tried to force `renv` to not use cache, but the cache still seems to be utilized on `renv::restore()`. Does `use.cache` just mean whether or not it creates a symlink vs. a copy?

```
> renv::restore()
The following package(s) will be installed:
         _             
  digest   [0.6.20]    
  sass     [0.1.0.9000]

Do you want to proceed? [y/N]: y
Installing digest [0.6.20] ...
	OK (copied cache)
Installing sass [0.1.0.9000] ...
	OK (copied cache)
> renv::settings$use.cache()
[1] FALSE
```

renv.lock
```
{
  "renv": {
    "Version": "0.6.0-120"
  },
  "R": {
    "Version": "3.5.3",
    "Repositories": [
      {
        "Name": "RSPM_DEV",
        "URL": "https://demo.rstudiopm.com/internal/latest"
      },
      {
        "Name": "RSPM_PROD",
        "URL": "https://demo.rstudiopm.com/cran/latest"
      }
    ]
  },
  "Packages": {
    "digest": {
      "Package": "digest",
      "Version": "0.6.20",
      "Source": "CRAN",
      "Hash": "ee526dc5fbf649c15ce452a474543a4c"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.1.0.9000",
      "Source": "CRAN",
      "Hash": "52edb896205596f125e4ce5055d8c3be"
    }
  }
}
```

**Comment by kevinushey** [comment] 2019-08-21 17:25
This is the intended behavior, but perhaps the option name is misleading. `use.cache` really means "use symlinks to the cache"; if that setting is off then packages are copied instead of linked, as you are seeing:

```
Installing sass [0.1.0.9000] ...
	OK (copied cache)
```

I think we should have separate options for:

1. Enabling / disabling the cache,
2. Copying vs. linking from the cache.

**Comment by kevinushey** [comment] 2019-08-21 17:51
It also seems like this should be a user configuration option rather than a project setting, since multiple people working on the same project might have different preferences on how the cache is used.

**Comment by kevinushey** [comment] 2019-08-23 15:57
Should be fixed via https://github.com/rstudio/renv/commit/79b26d353e5b2fba01d52b4307c7cebfff302a4e.

Will leave user preferences around how the cache is used for a separate issue.

**Closed by kevinushey** 2019-08-23 15:57 UTC

**Comment by cole-brokamp** [comment] 2019-11-26 19:55
Hello, has there been a separate issue created for how a user can prefer copying versus symlinking packages from the cache?  Is this possible in the current version?

I have been trying to use the newer [docker buildkit features](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache) to mount renv's cache in between builds, but this is only possible if the project _copies_, rather than symlinks, the packages to the project library upon running `renv::restore()`

**Comment by cole-brokamp** [comment] 2019-11-26 19:59
The Dockerfile looks something like this:

```sh
# syntax=docker/dockerfile:1.1-experimental
FROM rocker/r-ver:3.5.3

WORKDIR /code

ENV RENV_VERSION 0.8.3-50
RUN echo "options(renv.consent = TRUE)" >> .Rprofile
RUN R --quiet -e "install.packages('renv', repos = 'https://cran.rstudio.com')"
RUN R --quiet -e "renv:::renv_activate_impl(project = '.', version = '${RENV_VERSION}', restart = FALSE, quiet = FALSE)"

COPY renv.lock .

# installs all packages from lockfile (using caching from buildkit; set DOCKER_BUILDKIT=1 to activate)
ENV RENV_PATHS_CACHE=/renv_cache
RUN --mount=type=cache,target=/renv_cache R --quiet -e "renv::restore()"

COPY . .

CMD ["R", "--quiet"]
```

and could be a solution to the problem stated in the [renv docker article](https://rstudio.github.io/renv/articles/docker.html), which states that using the renv cache is only possible if a project is activated on run time, not build time

**Comment by kevinushey** [comment] 2019-11-26 20:12
You can set the R option:

```
options(renv.settings.use.cache = FALSE)
```

to force `renv` not use the cache (really, to copy from the cache as opposed to symlink).

You can also explicitly set this as a project option before restore, with e.g.

```
renv::settings$use.cache(FALSE)
```

**Comment by cole-brokamp** [comment] 2019-11-26 20:15
Great, I will try that.  `options(renv.settings = list(use.cache = FALSE))` didn't seem to be working as expected. Thanks.

**Comment by kevinushey** [comment] 2019-11-26 20:18
> RUN R --quiet -e "renv:::renv_activate_impl(project = '.', version = '${RENV_VERSION}', restart = FALSE, quiet = FALSE)"

Note that this step will also activate the project, which implies writing out project-specific structure -- including the `renv/settings.dcf`, where project settings are normally written. These project settings will override anything that might be specified as an R option, so using the explicit API (with `renv::settings$use.cache(FALSE)`) is probably what you want.

**Comment by cole-brokamp** [comment] 2019-11-26 20:20
Thanks for digging deeper!! I was wondering why it wasn't taking...

**Comment by cole-brokamp** [comment] 2019-11-26 20:36
Hi Kevin,  to follow up on a couple of things:

1. `renv:::renv_activate_impl()` does not create a `renv/settings.dcf` file for me, so setting renv options in a project specific `.Rprofile` seems to do the trick.

2. When using `renv::restore()` in a Docker environment where the global renv cache is empty, renv appears to install the packages directly to the project library rather than installing them to the global cache and then copying them to the project library. I can verify this by looking inside the global cache and seeing that it remains empty. Is there a way to force renv to use the global cache and then copy them to the project library in this case?

**Comment by cole-brokamp** [comment] 2019-11-26 20:39
>     1. `renv:::renv_activate_impl()` does not create a `renv/settings.dcf` file for me, so setting renv options in a project specific `.Rprofile` seems to do the trick.

Regarding this behavior, is it to be expected?  From the code here https://github.com/rstudio/renv/blob/4f7352f4898e7818e4fc010f0f0a9895326c6f2e/R/infrastructure.R#L3-L10 it seems that it is not.

**Comment by Sofie8** [comment] 2020-05-10 12:32
Hi,

I wanted to come back to disabling cache, it is not working for me.
I did:

```
renv::settings$use.cache(FALSE)  # disable cache
renv::init(
  project = "/vsc-hard-mounts/leuven-data/314/vsc31426/scripts/1.amplicon_pipeline/Dada2G",
  settings = list(use.cache = FALSE),
  bare = FALSE,
  force = FALSE,
  restart = interactive()
)
```

Then it says, it will make a local cache in:
'/vsc-hard-mounts/leuven-user/314/vsc31426/.local/share/renv'

I don't want this, because I am running on a server with different people, and different conda R environments. Setting the path to:
Sys.setenv('RENV_PATHS_CACHE'="/vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/R35/renv_cache")
also doesn't work, it says path is changed, and then still installs it in ./local/share/renv

My sessionInfo:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/R35/lib/R/lib/libRblas.so
LAPACK: /vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/envs/R35/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base

loaded via a namespace (and not attached):
 [1] BiocManager_1.30.10 compiler_3.5.1      htmltools_0.3.6
 [4] tools_3.5.1         yaml_2.2.0          Rcpp_1.0.2
 [7] rmarkdown_1.16      knitr_1.25          xfun_0.10
[10] digest_0.6.21       renv_0.9.3-63       evaluate_0.14
```

Any fix to this please?

Thanks!

**Comment by kevinushey** [comment] 2020-05-10 19:46
I think there's some misunderstanding here (and this is probably the fault of documentation in `renv`). The global package cache maintained by `renv` does indeed live within the folder customized via `RENV_PATHS_CACHE`, but `renv` does also store some extra state within the `RENV_PATHS_ROOT` folder as well.

Most of this is documented in `?renv::paths`, but I should probably document some of the other pieces (and make it easier to more explicitly disable those).

**Comment by kevinushey** [comment] 2020-05-10 19:46
In other words: the `renv` package cache is indeed disabled for that project, but other `renv` "stuff" is still being written into `RENV_PATHS_ROOT`.
