### ISSUE TITLE
renv.rdb corrupt

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/renv#600] opened 2020-12-21 13:50 UTC
Hi @kevinushey m

Hope you are well!

I just wanted to report a problem we've been having to you and to see if you had any ideas on why this might be. 

I've had a build pipeline setup with renv for a while that works really well. Steps are basically as follows:

```r
# Install latest renv each time
print("")
print("Installing latest version of renv")
print("")

install.packages("renv", lib = custom_lib, type = "source")

# If packrat project then convert
if (file.exists("packrat/packrat.lock")) {

	print("")
	print("Converting packrat project to renv")
	print("")

	packrat::repos_set("CRAN" = "https://cran.microsoft.com/")

	packrat::set_lockfile_metadata(repos = c("CRAN" = "https://cran.microsoft.com/"))

	renv::migrate()

}

print("")
print("Restoring renv environment")
print("")

# Restore environment
renv::activate()
renv::upgrade()
renv::activate()
print(getOption("repos"))
renv::restore(repos = c(CRAN = "https://cran.rstudio.com"))

if (Sys.getenv("skip_run") == 1) {
  
  print("run.R script skipped as requested.")
  
} else {
  
  # Stage 3 - Run run script ------------------------------------------------
  print("")
  print("Running run.R")
  print("")
  
  source('run.R')
  
}
```

As of late the renv::upgrade step seems to be throwing corruption errors for the lock file. See below.

Each pipeline run is a fresh clone in an empty directory and removing the renv::upgrade lets it work.

I would like to use renv::upgrade as older projects work better when upgraded. 

Any ideas why this might be?

```
2020-12-21T12:25:51.9373838Z [1] ""
2020-12-21T12:25:51.9374453Z [1] "Restoring renv environment"
2020-12-21T12:25:51.9374924Z [1] ""
2020-12-21T12:25:56.0148869Z A new version of the renv package will be installed:
2020-12-21T12:25:56.0149648Z 
2020-12-21T12:25:56.0162937Z # CRAN ===============================
2020-12-21T12:25:56.0163723Z - renv   [0.12.0 -> 0.12.3]
2020-12-21T12:25:56.0163986Z 
2020-12-21T12:25:56.0165970Z This project will use the newly-installed version of renv.
2020-12-21T12:25:56.0166410Z 
2020-12-21T12:25:56.0670709Z Installing renv [0.12.3] ...
2020-12-21T12:25:56.0695539Z 	OK [linked cache]
2020-12-21T12:25:56.3959165Z                       CRAN 
2020-12-21T12:25:56.3959830Z "https://cran.rstudio.com" 
2020-12-21T12:25:56.4498380Z Error in get(method, envir = home) : 
2020-12-21T12:25:56.4499274Z   lazy-load database 'C:/Agents/machine/_work/170/s/renv/library/R-3.6/x86_64-w64-mingw32/renv/R/renv.rdb' is corrupt
2020-12-21T12:25:56.4499806Z Calls: source ... loadNamespace -> registerS3methods -> .registerS3method -> get
2020-12-21T12:25:56.4500149Z In addition: Warning messages:
2020-12-21T12:25:56.4500452Z 1: In get(method, envir = home) : internal error -3 in R_decompress1
2020-12-21T12:25:56.4500859Z 2: In h(simpleError(msg, call)) : internal error -3 in R_decompress1
2020-12-21T12:25:56.4501173Z 3: In eval(handler$expr, handler$envir) :
2020-12-21T12:25:56.4501441Z   internal error -3 in R_decompress1
2020-12-21T12:25:56.4501768Z 4: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
2020-12-21T12:25:56.4502085Z   restarting interrupted promise evaluation
2020-12-21T12:25:56.4502399Z 5: In get(method, envir = home) :
2020-12-21T12:25:56.4502656Z   restarting interrupted promise evaluation
2020-12-21T12:25:56.4502955Z 6: In get(method, envir = home) : internal error -3 in R_decompress1
2020-12-21T12:25:56.4503745Z Execution halted
2020-12-21T12:25:56.7297544Z ##[error]PowerShell exited with code '1'.
2020-12-21T12:25:56.8008217Z ##[section]Finishing: PowerShell Script
```

Thanks for your help,

Adam

**Comment by adamrobinson361** [comment] 2020-12-21 16:08
Note i get the error if i just clone locally, open in R Studio and run `renv::upgrade()` too. 

Seems to work all fine after a restart. Should the upgrade function be forcing a restart somehow?

**Comment by kevinushey** [comment] 2020-12-21 18:54
This is a bug in R caused by attempts to unload and reload a package in the same session. Fortunately, it can be worked around -- I'll see if I can add that workaround to `renv`.

**Comment by kevinushey** [comment] 2020-12-21 19:28
Should be fixed in the latest development version of `renv`. If you need a workaround for now, you can just ensure `renv` is updated in a separate earlier R process.

**Closed by kevinushey** 2020-12-21 19:28 UTC
