### ISSUE TITLE
Install from BSPM

### ISSUE THREAD

**Issue by ginolhac** [rstudio/renv#519] opened 2020-08-13 11:10 UTC
Hi,
`renv` is great, and I am using it in all projects now. Even in a gitlab-CI to build a website with docker-in-docker.
I'd like to optimize a bit and use [BSPM](https://github.com/Enchufa2/bspm) to get at least some packages in binary format.
in a container, it works nicely with `install.packages()` but not for `renv::install()`. See below and example after
`docker run -ti rocker/r-bspm:20.04 /bin/bash`

```
> system.time(renv::install("Rcpp"))
Retrieving 'https://cloud.r-project.org/src/contrib/Rcpp_1.0.5.tar.gz' ...
	OK [downloaded 2.8 Mb in 0.3 secs]
Installing Rcpp [1.0.5] ...
	OK [built from source]
* Copying 'Rcpp' into the cache ... Done!
   user  system elapsed 
 25.265   1.069  26.612 
> system.time(install.packages("Rcpp"))
Install system packages as root...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Hit http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease                                                                              
Hit http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                  
Hit http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                          
Hit http://ppa.launchpad.net/chromium-team/beta/ubuntu bionic InRelease                                                                               
Hit http://archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                        
Hit http://ppa.launchpad.net/edd/r-4.0/ubuntu focal InRelease                                                                                         
Hit http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                        
Hit http://ppa.launchpad.net/marutter/rrutter4.0/ubuntu focal InRelease                                                                               
Fetched 0 B in 0s (0 B/s)                                                                                                                             
Reading package lists... Done    
Building dependency tree          
Reading state information... Done
Get:1 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal/main amd64 r-cran-rcpp amd64 1.0.5-1cran1.2004.0 [2050 kB]                           
Fetched 2050 kB in 0s (0 B/s)                                                                                                                         
Selecting previously unselected package r-cran-rcpp.
(Reading database ... 36107 files and directories currently installed.)
Preparing to unpack .../r-cran-rcpp_1.0.5-1cran1.2004.0_amd64.deb ...
Unpacking r-cran-rcpp (1.0.5-1cran1.2004.0) ...
Setting up r-cran-rcpp (1.0.5-1cran1.2004.0) ...
   user  system elapsed 
  2.720   0.337   3.491
```

`renv` is not fetching the binary version of `Rcpp`, so it takes 25 sec of compilation instead of 2.7 without. Would it possible to use binary when available? Or checking the version is too much of a hassle?
Many thanks again for such a nice tool

**Comment by mihem** [comment] 2021-12-18 08:33
Thanks for this great package!
I would also love to install binaries (using bspm) with `renv::install()`. Seems to be working for Windows and MRAN?
@kevinushey  ?

**Comment by kevinushey** [comment] 2021-12-18 18:33
@Enchufa2, is there a straightforward way to implement this in `renv`? If I understand correctly, the main thing I need is a way to ask bspm whether a particular package + version combination is available from bspm, and then a way to install that package.

**Comment by Enchufa2** [comment] 2021-12-19 19:33
Currently, there's no way to ask about specific versions. It's technically possible to implement such a feature, but system repos rarely preserve old package versions anyway. I think we are talking different purposes here. System repos (and, by extension, BSPM) are about staying up-to-date, while `renv` is about reproducibility. RSPM is a better match for that.

**Comment by jcpsantiago** [comment] 2021-12-20 07:42
To me the point of also having BSPM via renv in docker is to reduce build times. My R containers, which are fairly simple, take around 25-30min to build. My main application written in Clojure takes 5. I don't want to release something to a production environment with the latest versions by default (I got burned before doing that) and I also need a way to  colleagues to share the same environment as me when working on the same project. {renv} fixes both those problems, but the cost of source compilation is a hard pill to swallow :/

**Comment by Enchufa2** [comment] 2021-12-20 10:11
> To me the point of also having BSPM via renv in docker is to reduce build times.

Which you would achieve in a CI workflow where package versions do not matter: you just want the latest available. But if you are fixed in older versions, it's very unlikely that BSPM would find any version you require. You have much much better chances of finding those older versions via RSPM.

_Technically_, we _could_ maintain several versions per package in the system repos. But _practically_, we are volunteers maintaining large projects such as [cran2deb4ubuntu](https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+), [cran2obs](https://build.opensuse.org/project/show/devel:languages:R:autoCRAN) or [cran2copr](https://copr.fedorainfracloud.org/coprs/iucar/cran/), and we do not have the resources nor the time to maintain n versions per package.

**Comment by jcpsantiago** [comment] 2021-12-20 11:00
I understand. Makes sense, I thought there was some sort of technical problem. If it's like you say, then we'll just live with 20min build times. More time for looking at memes 😂

**Comment by Enchufa2** [comment] 2022-11-24 23:56
This is possible since v0.4.0 (on CRAN now) using the new method `bspm::available_sys()` (see https://github.com/Enchufa2/bspm/pull/47). This returns a matrix, similar to `available.packages()`, of packages with versions. The only shortcoming is that the row names of that matrix may or may not be in lower case. So it's best to force lower case to perform the match. For reference, [this](https://github.com/Enchufa2/bspm/blob/0366f0cfd5e0c4e34b571dec1ffa0bf5d409a791/R/integration.R#L59-L66) is how we do it internally to compare binary vs. source versions.

**Comment by kevinushey** [comment] 2023-01-09 07:07
Note to self: we append the renv cellar as a local CRAN-like repository here:

https://github.com/rstudio/renv/blob/eb308fe1692f82582077d49bde44cef30932466b/R/available-packages.R#L280-L285

so we could probably do something similar with BPSM?

**Comment by warnes** [comment] 2023-04-13 23:02
Any progress on this?

**Comment by hadley** [comment] 2023-04-28 13:42
You can use [PPPM](https://packagemanager.rstudio.com/client/#/) for this today. Adding BSPM support will take some additional engineering effort.

**Comment by ginolhac** [comment] 2023-05-23 11:44
Hello,

thanks a lot for the feedback and action,  I am trying the PPPM with this config on a Ubuntu 22.04 machine (with Docker) 

```
options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
```

and it seems to work very nicely! See example with `stringi` install

``` r
> renv::install("stringi")
Retrieving 'https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/stringi_1.7.12.tar.gz' ...
        OK [downloaded 3.1 Mb in 1.4 seconds]
Installing stringi [1.7.12] ...
        OK [installed binary in 1.1 seconds]
Moving stringi [1.7.12] into the cache ...
        OK [moved to cache in 4.7 milliseconds]
* Installed 1 package in 2.9 seconds.
```

I observed a lag between CRAN and the PPPM latest (for example `targets` is 1.1.2 on CRAN, 1.0.0 on PPPM latest) but seems very nice feature and free of charge. Thanks again a lot Hadley!

**Comment by hadley** [comment] 2023-06-09 19:44
We've looked into this in more detail, and are not going to consider it further for now. It'll take considerable work to add support for BSPM, and it would largely solve the same problem as PPPM.

**Closed by hadley** 2023-06-09 19:44 UTC
Labels: feature, install :basket:
