### ISSUE TITLE
`renv::init()`  and `renv::snapshot()` throw same error: Error in !deps$Dev : invalid argument type

### ISSUE THREAD

**Issue by NanisTe** [rstudio/renv#401] opened 2020-04-21 15:07 UTC
__*Problem:*__
`renv::init()`  and `renv::snapshot()` throw same error and `renv::init()` does not write `environment.yml ` when `renv::use_python(type="conda")` is being used if:
* a R file is in the project folder which includes the following lines:
```r
library("pacman")
pacakge.list <- c("dyplr","stringr")
p_load(char = package.list)
```

Running the `renv::init` and `renv::snapshot` throws the same error.
```r
> renv::snapshot()
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In node[["char"]][-1L] : object of type 'symbol' is not subsettable
```

The line `p_load(char = package.list)` causes the problem.

__*Error message:*__
```r
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In node[["char"]][-1L] : object of type 'symbol' is not subsettable
```

__*Traceback:*__
Traceback of the error shows: `renv_dependencies_discover_impl()` which is used in `renv::dependencies()` which is used in `renv::init()` creates unexpected output `dep` in the above case.

```r
> test <- renv::dependencies()
Finding R package dependencies ... Done!
Error in !deps$Dev : invalid argument type
In addition: Warning message:
In node[["char"]][-1L] : object of type 'symbol' is not subsettable
```

**Comment by NanisTe** [comment] 2020-04-21 15:09
I would suggest to not scan files since there can always be an issue like this. Better depend on one file where loading libraries is expected. E.g. an install.R file or similar.

**Comment by kevinushey** [comment] 2020-04-21 21:59
Please see the documentation in `?renv::snapshot` -- you likely want to set

```
options(renv.config.snapshot.type = "all")
```

which basically states "capture all packages in my project library, without scanning my project for dependencies".

**Comment by kevinushey** [comment] 2020-04-21 22:00
That said, this issue:

> Error in !deps$Dev : invalid argument type

should already be fixed on master, and

> In addition: Warning message:
> In node[["char"]][-1L] : object of type 'symbol' is not subsettable

could reasonably be fixed on the `renv` side as well.

**Comment by NanisTe** [comment] 2020-04-22 11:04
My options are not set at all:
```r
> options("renv.config.snapshot.type")
$renv.config.snapshot.type
NULL
```

Anything I missed there? Do we have to set this option actively before using renv?

**Comment by NanisTe** [comment] 2020-04-22 13:59
setting the file with .renvignore in relative path does not work either.

> Error in !deps$Dev : invalid argument type
>
> should already be fixed on master, and

means it is not on CRAN yet?

**Comment by kevinushey** [comment] 2020-04-22 16:56
Right, the associated fix is not yet on CRAN.

FWIW, the issue is caused by empty / blank fields in the DESCRIPTION file. You probably have something like:

```
Depends: ,
    package1,
    package2
```

Note the initial command delimiting an empty field. Removing that fixes the problem.

**Comment by kevinushey** [comment] 2020-04-22 16:58
Yes, that's correct. (Sorry, deleted an earlier incorrect diagnosis of the issue)

**Closed** 2023-04-28 17:34 UTC
