### ISSUE TITLE
Cannot install from bitbucket into cache - (or missing documentation?)

### ISSUE THREAD

**Issue by amarquard** [rstudio/renv#449] opened 2020-06-04 20:05 UTC
I want to install an internal package from bitbucket. I can manage to do that with devtools::install_bitbucket(), but that doesn't seem to put the package in my renv library cache, as I was intending to. I cannot get renv::install() to work for a bitbucket repo, and perhaps the documentation for using renv::install for a bitbucket repo could have some more detail on the arguments to give?

This installs successfully, but does not save the package in the cache:
`devtools::install_bitbucket("amarquard/acme-cap", auth_user = "amarquard", password = <app password>)`

To use renv::install, I have added these two to my project .Renviron file:
`BITBUCKET_USER = "amarquard"`
`BITBUCKET_PASSWORD = <app password>`

 And I have also set my repo to "public" just in case. None of the following commands succeed.

`renv::install("https://api.bitbucket.org/2.0/repositories/amarquard/acme-cap/src/master/")`
`tar: Error opening archive: Unrecognized archive format
tar: Error opening archive: Unrecognized archive format
Error: archive '~/Library/Application Support/renv/source/url/85c40c53695ce55a3feb82a20b1e69b3.tar.gz' does not appear to contain a DESCRIPTION file`

`renv::install("https://amarquard@bitbucket.org/amarquard/acme-cap/src/master/")`
`renv::install("https://amarquard@bitbucket.org/amarquard/acme-cap/")`
`renv::install("amarquard/acme-cap")`
`Error: download failed [error code 22]
In addition: Warning messages:
1: curl: (22) The requested URL returned error: 400  
2: curl: (22) The requested URL returned error: 400  `

Thanks so much in advance

**Comment by kevinushey** [comment] 2020-06-08 22:48
You should be able to install with:

```
renv::install("bitbucket::amarquard/acme-cap")
```

Does that work? (I should document this explicitly within `?install`.)

**Comment by amarquard** [comment] 2020-08-20 14:25
Dear Kevin, thanks for suggesting this answer. Unfortunately it doesn't
seem to work. I get this:

> renv::install('bitbucket::amarquard/acme-cap')
Retrieving 'https://api.bitbucket.org/2.0/amarquard/acme-cap/get/0edef6c5d8557e6b686c450406d3502a212c3961.tar.gz'
...
Warning messages:
1: curl: (22) The requested URL returned error: 404 Not Found
2: curl: (22) The requested URL returned error: 404 Not Found

**Comment by kevinushey** [comment] 2020-08-20 18:59
Thanks! I believe this was a bug in `renv` that should ultimately be fixed in the development version. Can you try updating to the latest version of `renv` and see if it works for you?

```
> packageVersion("renv")
[1] '0.11.0.24'
> renv::install('bitbucket::amarquard/acme-cap')
Retrieving 'https://bitbucket.org/amarquard/acme-cap/get/0edef6c5d8557e6b686c450406d3502a212c3961.tar.gz' ...
        OK [downloaded 55.8 Kb in 0.5 secs]
Retrieving 'https://cran.rstudio.com/bin/macosx/contrib/4.0/openxlsx_4.1.5.tgz' ...
        OK [downloaded 3 Mb in 0.2 secs]
Retrieving 'https://cran.rstudio.com/src/contrib/zip_2.1.0.tar.gz' ...
        OK [downloaded 110.2 Kb in 0.1 secs]
Installing zip [2.1.0] ...
        OK [built from source]
* Copying 'zip' into the cache ... Done!
Installing openxlsx [4.1.5] ...
        OK [installed binary]
* Copying 'openxlsx' into the cache ... Done!
Installing acmecap [0.0.0.9000] ...
        OK [built from source]
* Copying 'acmecap' into the cache ... Done!
```

**Comment by amarquard** [comment] 2020-09-01 07:29
Thanks Kevin, this fixed it for us!
We are very happy with renv, thanks for working on this.
Except we do look forward to one day being able to have the package cache on a different drive than the working directory. Sorry for mixing this question into this issue thread, but if you do have a moment to just comment on whether this is something we may dare to hope for, or whether there are no plans to do that. Would be very helpful to know.
Thanks again
- Andrea

**Comment by kevinushey** [comment] 2020-09-01 15:56
> Except we do look forward to one day being able to have the package cache on a different drive than the working directory.

The directory used for the package cache (and other paths) can be adjusted via environment variable -- see `?renv::paths` for more details. In particular, the global package cache's path can be set via `RENV_PATHS_CACHE`.

**Comment by amarquard** [comment] 2020-09-01 18:43
Thank you Kevin. We’ve explored this previously (in the way you mention), but we need it to be on a separate disk (because of how our setup is at work) and that seems not possible at the moment. We were trying to setup the cache on a dropbox-kind-of shared location, and it seems renv cant access this and instead begins to install packages locally for each project. 
If you think this is unintended I could open a new issue on it. If you think this is intended, I will leave it at that and hope this becomes possible in the future.

**Comment by kevinushey** [comment] 2020-09-01 18:54
Can you file another issue with more context?

I wonder if the issue here is that the symlinks used (or junction points, if you're on Windows) don't work across disks in this case. Either way, a separate issue with more information about how you're using `renv` would be helpful. Thanks!

**Comment by RoelRotti** [comment] 2021-01-11 15:31
Hi! I'm having similar problems. I tried the above (running at > packageVersion("renv") [1] ‘0.12.3.73’) but I can't seem to get a download from bitbucket.

I believe the issue is that I am not the owner of the repository. Therefore when I clone the repository I use the following line: git clone https://<username>@bitbucket.org/<namerepository>.  When I use this format with renv::install however I get:
Error: failed to parse remote

I can install it with 'devtools::install_bitbucket("<namerepository>", auth_user = "<username>", password = "<password>")'. But using this same format with renv::install results in:

> renv::install("bitbucket::<namerepository>")
Error: failed to parse remote 'bitbucket::<namerepository>' -- download failed [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 401 Unauthorized 

When I use <namerepository>/src/master I get: 
> renv::install("bitbucket::<namerepository>/scr/master")
Error: failed to parse remote 'bitbucket::<namerepository>/src/master' -- download failed [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 403 Forbidden 

Any clue on how I can pull this repository? Thanks in advance! Cheers

**Comment by kevinushey** [comment] 2021-01-11 17:45
The following works for me, with a Bitbucket repository hosted here:

https://bitbucket.org/kevinushey/skeleton/src/master/

```
> renv::install("bitbucket::kevinushey/skeleton", rebuild = TRUE)
Retrieving 'https://bitbucket.org/kevinushey/skeleton/get/958296dbbbf7f1d82f7f5dd1b121c7558604809f.tar.gz' ...
        OK [downloaded 785 bytes in 1.7 secs]
Installing skeleton [1.0.1] ...
        OK [built from source]
Copying skeleton [1.0.1] into the cache ...
        OK [copied 15 files in 0.016 seconds]
```

**Comment by RoelRotti** [comment] 2021-01-12 13:09
Hi Kevin,

Thanks a lot for reaching out! Unfortunately I again get this:
Error: failed to parse remote 'bitbucket::' -- download failed [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 401 Unauthorized

I tried it with my account name and e-mail address for username. Also tried it with :
renv::install("bitbucket::vustudentanalytics/vusa", rebuild = TRUE, auth_user = "", password = "")
and like:
renv::install("bitbucket::vustudentanalytics/vusa", rebuild = TRUE) + BITBUCKET_USER = "", BITBUCKET_PASSWORD = ""

Sadly all of the above options lead to the same result: 401 Unauthorized

**Comment by RoelRotti** [comment] 2021-01-25 14:17
Hi Kevin, would you have any clue what causes the above problems? Cheers,
Roel

**Comment by kevinushey** [comment] 2021-01-25 19:01
I just tried with my own private Bitbucket project and the following worked for me:

```
Sys.setenv(BITBUCKET_USER = "kevinushey")
Sys.setenv(BITBUCKET_PASS = "<...>")

renv::install(
  "bitbucket::kevinushey/renv",
  library = tempdir()
)
```

`BITBUCKET_PASS` was set to an app password with repository access, as per https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/.

**Comment by RoelRotti** [comment] 2021-02-04 08:07
Hi Kevin, thanks so much for you effort. this is indeed what solved it. Thanks a bunch!

**Comment by kevinushey** [comment] 2021-02-04 18:46
Awesome! I'm glad to hear it.

**Closed by kevinushey** 2021-02-04 18:46 UTC
