### ISSUE TITLE
Downloading files w/o curl

### ISSUE THREAD

**Issue by robertdj** [rstudio/renv#301] opened 2019-12-12 09:57 UTC
Hi

I have had trouble restoring on Windows Server. Unlike Windows 10 there is no `curl` on Windows Server. 

The function `renv_download_impl` *should* figure this out with `renv_donwload_file_method`, but it returns `curl` even though `curl` is not available. 

My log looks something like this:

> Querying repositories for available binary packages ... Done! 
> ...
> Error: failed to retrieve package <name>
> ...
> InternetOpenUrl failed: 'The requested header was not found' 

The first query is listed as successful, but it doesn't receive anything. However, the problem is not discovered until `renv` tries to download the first (source) package and fails. 

One suggestion is more information when setting the download method. It took quite a bit of digging to realize that the download method was not set correctly.

**Comment by kevinushey** [comment] 2019-12-12 17:57
We do document this in the introduction vignette:

https://rstudio.github.io/renv/articles/renv.html#downloads

However, I believe you're mistaken on the error: it looks like `renv` is trying to use the default ("wininet") download method, and that is failing. (`InternetOpenUrl` is a routine provided by the `wininet` module; see https://docs.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetopenurla)

Either way, I would strongly recommending downloading `curl` and using that instead for downloads. You can download a recent version of `curl` with `renv::equip()`.

**Comment by robertdj** [comment] 2019-12-13 08:27
Ooops -- sorry! I should have RTFM... 

Despite the log indicating `wininet`  `renv::restore` *is* trying to use `curl`:
```
> renv:::renv_download_file_method()
[1] "curl"
```
(The output is from before running `renv::equip`). 
When restoring:
```
> renv::restore()
...
exiting from: renv_download_impl(url = url, destfile = file, type = type, request = "HEAD", 
    headers = headers)
	OK [downloaded 169.2 Kb in 1 secs]
Retrieving 'CRAN/askpass_1.1.zip' ...
curl: (6) Could not resolve host: CRAN
curl: (6) Could not resolve host: CRAN
Retrieving 'CRAN/askpass_1.1.tar.gz' ...
curl: (6) Could not resolve host: CRAN
curl: (6) Could not resolve host: CRAN
Retrieving 'https://mran.microsoft.com/snapshot/2019-07-04/src/contrib/Archive/askpass/askpass_1.1.tar.gz' ...
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
```

`renv::equip` downloads `curl` and updates `~/.R/Makevars`, but I get the same behavior when `restore`ing.

**Comment by kevinushey** [comment] 2019-12-13 16:18
That new output would indeed imply that you're using `curl`.

> Retrieving 'CRAN/askpass_1.1.zip' ...

What is the output of `getOption("repos")`? This would seem to imply that you have a repository URL literally called `CRAN`, which would be invalid.

> Retrieving 'https://mran.microsoft.com/snapshot/2019-07-04/src/contrib/Archive/askpass/askpass_1.1.tar.gz' ...

This is a bit more surprising, since `askpass 1.1` should be current (not in the archive).

A reproducible example would be helpful here.

**Comment by robertdj** [comment] 2019-12-14 15:57
I'm on a different machine now, but `getOption("repos")` is (something like):
```
InternalCRAN = "http://cran.mycompany.com"
CRAN = "https://mran.microsoft.com/snapshot/2019-07-04"
```
Depending on the project and computer used to `snapshot` the entry in `renv.lock` has either the name ("InternalCRAN"/"CRAN") or the URL. I have not found a pattern in determining which of the two possibilities are used. See also our previous discussion in https://github.com/rstudio/renv/issues/190

Let me see if I can make a reproducible example.

**Comment by kevinushey** [comment] 2019-12-14 15:58
Can you share the lockfile? I wonder if something is being misencoded in there.

**Comment by robertdj** [comment] 2019-12-14 16:00
Let me find the lockfile of Monday when I have access to the troublesome computer again :-)

**Comment by robertdj** [comment] 2019-12-16 11:33
Hi again. I have attached the `renv.lock` (with some substitutions for private packages).
[renv.lock](https://github.com/rstudio/renv/files/3967795/renv.lock.txt)

**Comment by kevinushey** [comment] 2019-12-16 18:46
Unfortunately, I don't see anything out of place, and cannot reproduce the issue locally (substituting my own CRAN repository for the 'internal' one).

Could you also run `renv::diagnostics()` on that machine, and paste the output here?

It's curious to me that MRAN is being used, e.g. here:

```
Retrieving 'https://mran.microsoft.com/snapshot/2019-07-04/src/contrib/Archive/askpass/askpass_1.1.tar.gz' ...
```

but those repositories are not declared in the lockfile. Are you overriding the repositories used in some way during restore?

**Comment by robertdj** [comment] 2019-12-20 14:02
I have uploaded the output from `renv::diagnostics()` (with a few replacements): [renv_diagnostics.txt](https://github.com/rstudio/renv/files/3988546/renv_diagnostics.txt)

I'm not doing any overwriting, just `renv::restore()`

**Comment by kevinushey** [comment] 2019-12-20 21:01
Right, but the repositories encoded in the lockfile are:

```
    "Repositories": [
      {
        "Name": "InternalCRAN",
        "URL": "http://cran.mycompany.com"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
```

And yet, `renv` appears to be using MRAN, as per:

> Retrieving 'https://mran.microsoft.com/snapshot/2019-07-04/src/contrib/Archive/askpass/askpass_1.1.tar.gz' ...

And `renv` takes the repositories from three sources:

1. Explicitly provided as `renv::restore(repos = <...>)`;
2. Provided through the `repos.override` configuration option;
3. Read from the lockfile.

I think ultimately you need to answer the question as to where the MRAN repository is coming from, since to the best of my knowledge `renv` wouldn't be setting that anywhere.

I'd also be curious as to whether you could share the output of:

```
trace(utils::download.file, quote(str(as.list(environment()))))
renv::restore()
```

when using `wininet` -- I wonder if `renv` is trying to set some headers that are tripping up the Windows downloader.

**Comment by robertdj** [comment] 2019-12-21 07:28
Good point with MRAN/CRAN. I usually go with MRAN, but in some projects I switch to CRAN if I need bleeding edge versions of packages. Let me make sure that I haven't messed something up in this project.

I'll try to run the last two commands as well. Might take a day or two, though.

**Comment by robertdj** [comment] 2020-01-01 19:14
Sorry -- I didn't get around to doing this before my holidays.

I think I remember why the MRAN/CRAN is due to me wanting to speed up installation: CRAN is faster than MRAN so after the packages have been installed from MRAN and the versions recorded I just replace the MRAN url with a CRAN url. 

I'll get back to you with the commands next week.

**Comment by kevinushey** [comment] 2020-01-22 02:32
Closing for now -- please re-open if you can provide extra information.

**Closed by kevinushey** 2020-01-22 02:32 UTC
