### ISSUE TITLE
`renv` for R package checking

### ISSUE THREAD

**Issue by pat-s** [rstudio/renv#197] opened 2019-09-24 15:16 UTC
I am thinking about using _renv_ for isolated R pkg checking on CI providers.

My current approach is as follows:

1. `renv::init(bare = TRUE)` to avoid copying unneeded dependencies from the main R lib
2. `renv::install()` to scrape deps from the DESCRIPTION file
3. R CMD build and R CMD check

However when at step 3, I face the following problem 

```r
==> R CMD check *.tar.gz

* checking whether package ‘tic.package’ can be installed ... ERROR
Installation failed.
```

with 

```
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
```

Inspecting the tarball that makes sense since there is no `renv` directory in `00_pkg_src/pkg` since it is listed in `.Rbuildignore`.
However, during R CMD check the `.Rprofile` kicks in and makes R search for that directory which does not exist and hence it fails.

If I change `.Rbuildignore` from

```
^renv$
```

```
^renv/library
^renv/settings
```

everything works since now `renv/activate.R` is within the tarball. Also I get no complains about unwanted files during the check.

However, when restarting the session, `^renv$` is automatically re-added to `.Rbuildignore` which breaks my approach. 

Would it be possible to avoid that behavior of readding `^renv$`? Or even easier, set my own logic for `.Rbuildignore`?

**Comment by kevinushey** [comment] 2019-09-24 17:15
Normally, you don't want any of the `renv` components to enter the built package, as otherwise `R CMD check` will complain --, hence why we exclude the entire folder. I think an alternate solution would be:

1. Remove the `.Rprofile` altogether;
2. Make the sourcing of `renv/activate.R` conditional on that file actually existing.

I think (1) makes sense since normally a package shouldn't be built with its own `.Rprofile`.

**Comment by karawoo** [comment] 2019-09-24 18:26
I feel like I must be missing something obvious, but 1. isn't working for me. I have `^\.Rprofile$` in my [.Rbuildignore](https://github.com/Sage-Bionetworks/dccvalidator/blob/5528e97db97db18352ad50a9693afed6ff728e61/.Rbuildignore#L15) but still can't check the package. 

```r
#> * Project '~/projects/validation/dccvalidator' loaded. [renv 0.7.0-105]
devtools::check()
#> Updating dccvalidator documentation
#> Writing NAMESPACE
#> Loading dccvalidator
#> Loading required package: shinyBS
#> Writing NAMESPACE
#> ── Building ──────────────────────────────────────────────────── dccvalidator ──
#> Setting env vars:
#> ● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
#> ● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
#> ● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
#> ────────────────────────────────────────────────────────────────────────────────
#> ✔  checking for file ‘/Users/kwoo/projects/validation/dccvalidator/DESCRIPTION’
#> ─  preparing ‘dccvalidator’: (25.8s)
#> ✔  checking DESCRIPTION meta-information
#> ─  checking for LF line-endings in source and make files and shell scripts (6.7s)
#> ─  checking for empty or unneeded directories
#> ─  building ‘dccvalidator_0.0.0.9002.tar.gz’
#>    
#> ── Checking ──────────────────────────────────────────────────── dccvalidator ──
#> Setting env vars:
#> ● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
#> ● _R_CHECK_CRAN_INCOMING_       : FALSE
#> ● _R_CHECK_FORCE_SUGGESTS_      : FALSE
#> ── R CMD check ─────────────────────────────────────────────────────────────────
#>    Error in file(filename, "r", encoding = encoding) : 
#>      cannot open the connection
#>    Calls: source -> file
#>    In addition: Warning message:
#>    In file(filename, "r", encoding = encoding) :
#>      cannot open file 'renv/activate.R': No such file or directory
#>    Execution halted
#> ── R CMD check results ──────────────────────────── dccvalidator 0.0.0.9002 ────
#> Duration: 148ms
#> 
#> 0 errors ✔ | 0 warnings ✔ | 0 notes ✔

**Comment by kevinushey** [comment] 2019-09-24 20:40
I think I know what's going on. `renv` tries to set `R_PROFILE_USER` to help ensure the project .Rprofile gets loaded + used by R child processes that get run. This fails in contexts like these. I'll fix this up.

**Comment by kevinushey** [comment] 2019-09-24 20:40
To validate, you can try running:

```
Sys.unsetenv("R_PROFILE_USER")
devtools::check()
```

**Comment by karawoo** [comment] 2019-09-24 20:53
Confirmed, unsetting `"R_PROFILE_USER"` fixes it

**Comment by kevinushey** [comment] 2019-09-24 21:16
This should be fixed up on master in renv now as well. Sorry for the trouble!

**Closed** 2019-10-01 04:18 UTC

**Comment by cjvanlissa** [comment] 2020-01-17 08:17
I'm surprised to get this error on a package I'm building that does **not** use `renv`! There's no .lock file, no renv/ directory, no .Rprofile - and still I get this error when I run the package check:

```
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
```

**Comment by cjvanlissa** [comment] 2020-01-17 10:25
And relatedly: When I try to Install and Restart any package (not using `renv`), the new version is not installed. I do notice that I get the message below, even in packages that do not use `renv`:

`* installing to library 'C:/Git_Repositories/renv/library/R-3.6/x86_64-w64-mingw32'`
