### ISSUE TITLE
Bootstrapping fails when `renv` is installed via `actions/setup-r-dependencies`

### ISSUE THREAD

**Issue by kamilzyla** [rstudio/renv#1772] opened 2023-12-05 14:44 UTC
### Background

Our testing setup in [Rhino](https://github.com/Appsilon/rhino) includes a GitHub Actions workflow which initializes a `renv` project and pushes it to a branch. When we subsequently try to run this project, `renv` fails to bootstrap (install itself). The problem seems to stem from the fact that we install `renv` via `actions/setup-r-dependencies` in our workflow.

### Steps to reproduce

Create a fresh GitHub repository and push a `.github/workflows/renv-test.yml` file with content as follows:

```yml
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          # Speeds up the workflow; does not affect the results.
          # Caching (enabled by default) seems to have no effect either.
          use-public-rspm: true

      - name: Install renv (broken)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: renv

      # - name: Install renv (working)
      #   shell: Rscript {0}
      #   run: install.packages("renv")

      - name: Init renv
        shell: Rscript {0}
        run: renv::init()

      - name: Debug
        run: head renv/activate.R

      - name: Force renv bootstrap
        run: rm -r renv/library

      - name: Say hi
        shell: Rscript {0}
        run: message("Hi!")
```

### Problem

The "Say hi" step fails with the following output:

```
# Bootstrapping renv 1.0.3 [sha: 1.0.3] --------------------------------------
- Downloading renv ... FAILED
Error: Error in h(simpleError(msg, call)) : failed to download:
All download methods failed
Calls: source ... bootstrap -> withCallingHandlers -> renv_bootstrap_download
Execution halted
Error: Process completed with exit code 1.
```

### Expected behavior

After removing `renv/library`, `renv` should bootstrap without issues when running `Rscript` in the "Say hi" step and the whole workflow should succeed.

### Notes

Installing `renv` with `install.packages()` instead of `actions/setup-r-dependencies` resolves the problem. It can be tested by uncommenting the "Install renv (working)" step.

The "Debug" step gives us a hint to the cause of the issue. After installation with `actions/setup-r-dependencies` the `renv/activate.R` file starts with:
```
attr(version, "sha") <- "1.0.3"
```
Setting the attribute to `NULL` instead (as happens when using `install.packages()`) fixes the problem:
```
attr(version, "sha") <- NULL
```

Our workflow uses a fixed version (v2) of `actions/setup-r-dependencies` and the latest CRAN version of `renv`. It stopped working somewhere between 2023-07-06 (last successful run) and 2023-07-24 (first failure) without any relevant changes in the repo. This led me to believe that some `renv` update introduced the problem and that's why I decided to report it here and not in `r-lib/actions` repo.

**Comment by kevinushey** [comment] 2023-12-06 00:42
Thanks! A more direct reproducible example is to simply install `renv` with `pak`, e.g.

```
remove.packages("renv")
pak::pak("renv")
```

And then you'll see the version written out erroneously as a "sha". This happens because `pak` updates the DESCRIPTION file for packages it installs from CRAN as e.g.

```
RemoteType: standard
RemotePkgRef: renv
RemoteRef: renv
RemoteRepos: https://cloud.R-project.org
RemotePkgPlatform: aarch64-apple-darwin20
RemoteSha: 1.0.3
```

and `renv` uses that RemoteSha without first validating that the DESCRIPTION is a "github" remote.

To wit, this should be resolved with https://github.com/rstudio/renv/commit/d4201d86123211b669a2409f5a1d926e6b6ddfc1. Thanks for reporting!

**Closed by kevinushey** 2023-12-06 00:42 UTC
Labels: bug
