### ISSUE TITLE
Installing packages fails with version 0.7.0-22

### ISSUE THREAD

**Issue by matthijsvanderloos** [rstudio/renv#176] opened 2019-09-04 12:34 UTC
The latest renv version (0.7.0-22) fails to install packages, for example:

```r
install.packages("ps")
Installing ps [1.3.0] from CRAN ...
	FAILED
Error installing package 'ps':
==============================

* installing *binary* package 'ps' ...
cp: unknown option -- )
Try '/Rtools/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/<user>/AppData/Local/Temp/RtmpOEKzRg/renv-tempdir-2da43ed34539/renv-templib-2da4143f1288/ps'
In R CMD INSTALL
Error: install of package 'ps' failed
```

**Comment by kevinushey** [comment] 2019-09-04 15:08
I'm not able to reproduce:

```
> renv::install("ps", rebuild = TRUE)
* Querying repositories for available source packages ... Done!
* Querying repositories for available binary packages ... Done!
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/ps_1.3.0.zip' ...
	OK [file is up to date]
Installing ps [1.3.0] from CRAN ...
	OK (installed binary)
* Copying 'ps' into the cache ... Done!
```

Can you provide more information?

**Comment by kevinushey** [comment] 2019-09-04 17:01
https://github.com/r-lib/devtools/issues/1191 seems related -- it would imply that, for some reason, `renv` is attempting to install from an unpacked binary archive as opposed to a zipfile.

Are you able to provide more information as to how you got `renv` into this state?

**Comment by kevinushey** [comment] 2019-09-04 17:04
I'm able to reproduce now in a project where I disabled caching:

```
> renv::install("ps", rebuild = FALSE)
Installing ps [1.3.0] from CRAN ...
	FAILED
Error installing package 'ps':
==============================

* installing *binary* package 'ps' ...
cp: unknown option -- )
Try '/Rtools/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/kevinushey/AppData/Local/Temp/RtmpwNU7A9/renv-tempdir-13683407442a/renv-templib-13681f671082/ps'
```

I'll see if I can figure out what's going on.

**Comment by matthijsvanderloos** [comment] 2019-09-04 17:09
Sure, in a fresh RStudio project:

```R
> renv::init()
* Discovering package dependencies ... Done!
* Copying packages into the cache ... Done!
* Lockfile written to 'C:/Users/<user>/Desktop/test/renv.lock'.
* Project 'C:/Users/<user>/Desktop/test' loaded. [renv 0.7.0-22]

Restarting R session...

* Project 'C:/Users/<user>/Desktop/test' loaded. [renv 0.7.0-22]
```

This indeed works:

```R
> renv::install("ps", rebuild = TRUE)
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.5/ps_1.3.0.zip' ...
	OK [file is up to date]
Installing ps [1.3.0] from CRAN ...
	OK (installed binary)
* Lockfile written to 'C:/Users/<user>/Desktop/test/renv.lock'.
```

Running install.packages instead also does:
```R
> install.packages("ps")
* Querying repositories for available binary packages ... Done!
* Querying repositories for available source packages ... Done!
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.5/ps_1.3.0.zip' ...
	OK [file is up to date]
Installing ps [1.3.0] from CRAN ...
	OK (installed binary)
* Lockfile written to 'C:/Users/<user>/Desktop/test/renv.lock'.
```

But then runing `renv::isolate` and next trying to install the same package fails using `install.packages`.

This works:
```R
> renv::isolate()
> renv::install("ps", rebuild = TRUE)
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.5/ps_1.3.0.zip' ...
	OK [file is up to date]
Installing ps [1.3.0] from CRAN ...
	OK (installed binary)
* Lockfile written to 'C:/Users/<user>/Desktop/test/renv.lock'.
```

This fails:
```R
> renv::isolate()
> install.packages("ps")
Installing ps [1.3.0] from CRAN ...
	FAILED
Error installing package 'ps':
==============================

* installing *binary* package 'ps' ...
cp: unknown option -- )
Try '/Rtools/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Users/<user>/AppData/Local/Temp/Rtmp0cKAeF/renv-tempdir-2a102ebc7e84/renv-templib-2a106cfec01/ps'
In R CMD INSTALL
Error: install of package 'ps' failed
```

**Comment by kevinushey** [comment] 2019-09-04 17:34
Thanks! I think this should be fixed up on master now; at least this works on my Windows VM:

```
> renv::isolate()
> install.packages("ps")
Error: unexpected symbol in "install.packages("ps")V"
> install.packages("ps")
Retrieving 'https://cran.rstudio.com/bin/windows/contrib/3.6/ps_1.3.0.zip' ...
	OK [file is up to date]
Installing ps [1.3.0] from CRAN ...
	OK (installed binary)
* Lockfile written to '~/scratch/sadpq/renv.lock'.
```

**Comment by matthijsvanderloos** [comment] 2019-09-04 17:43
Yes, it works on my setup now as well. Thanks for fixing!

**Comment by kevinushey** [comment] 2019-09-04 20:32
Glad I could help! Thanks for taking the time to report the problem.

**Closed by kevinushey** 2019-09-04 20:32 UTC
