### ISSUE TITLE
Windows network drive switch to project upon deactivate()

### ISSUE THREAD

**Issue by Danny-dK** [rstudio/renv#918] opened 2022-01-19 16:45 UTC
I'm new to renv, so bare with me.

To test renv, I initially used a new directory on a local drive on my laptop. There I saved an R file (not an .Rproj), opened that .R file, and used renv::activate() and renv::deactivate(). This all worked pretty good locally. I then tried this on a windows network drive. When calling deactivate() in the opened .R file, Rstudio switches to the .Rproj file that is in the same directory (created when calling renv::activate() by default) in that network drive.This behaviour does not occur when on a local drive. On the local drive it just restarts the R session without switching to the .Rproj file (that was created by renv::activate()). 

Is there an option to stop renv or rstudio from switching to an .Rproj on a network drive when specifying renv::deactivate()?

system Windows 10
R version 4.1.2
Rstudio 2021.9.1.372
renv 0.15.0

(note: for this case I don't want to open the .Rproj as it was slower in performance on a network drive in conjunction with renv than just opening an .R file and renv::activate, my question is specific for why it switches to .Rproj on a network but not locally)

**Comment by kevinushey** [comment] 2022-01-19 19:45
There isn't currently a way to accomplish this. Are you hoping for something like:

```
renv::deactivate(restart = FALSE)
```

or similar functionality configured via an R option?

For what it's worth, we typically recommend restarting the R session after loading / unloading a particular project, since one cannot always cleanly unload packages that were loaded from a given `renv` project library.

**Comment by Danny-dK** [comment] 2022-01-19 20:25
Thanks for the reply @kevinushey. I want the session to restart, locally that works fine where it does not automatically open the .Rproj when specifying deactivate (but it does restart the session). On a network drive after deactivate it restarts and automatically opens the .Rproj which I find odd that that happens only on network drive. I just want it to restart without switching to project mode again on the network drive.

**Comment by Danny-dK** [comment] 2022-01-19 20:46
I tried to screen record what happens. 

This is my test. I have these files in a directory on a local drive and the same files on a network drive.

![image](https://user-images.githubusercontent.com/45395070/150210247-7a4c3a24-ef00-4320-bb9a-74280d3f9e8b.png)

I open only the .R file (both local drive and network drive), not the .Rproj file.

Then locally what happens is:

https://user-images.githubusercontent.com/45395070/150210401-2f5e4def-721f-44c6-9d88-2aea7ecb9aeb.mp4

But on a network drive what happens is (skip from 4 to 23 seconds (network was a bit slow this time, normally is a bit faster):

https://user-images.githubusercontent.com/45395070/150210454-a2424640-c62b-4f6d-84e2-e80e10f2fe82.mp4

**Comment by Danny-dK** [comment] 2022-01-20 13:09
Can't find a solution. For now I guess I just have to deal with Rprojects being somehwat slower on network drives and just use Rproject with renv (as in a renv project created with renv::init()). The reason I did not use it as a project before was because even more slowdown was noticeable when renv was initialized on the network drive. I'm now directing most renv things (libraries and cache) to a local drive which has reduced slowdown. I've added a .Renviron and .Rprofile to the project.

.Renviron:

```
R_LIBS_USER=file.path(paste0("C:/Program Files/R/R-", R.version$major, '.', R.version$minor, "/library"))
RENV_PATHS_LIBRARY_ROOT=${HOME}/project_libs
RENV_PATHS_LIBRARY=${HOME}/project_libs/project_check
RENV_PATHS_CACHE=${HOME}/project_libs/global_renv_cache

```

.Rprofile:

```
source("renv/activate.R")


.First <- function() {

	Sys.setlocale("LC_TIME", "English")
	
	if(!dir.exists(paste0(Sys.getenv('HOME'), '/project_libs'))){
	
		dir.create(paste0(Sys.getenv('HOME'), '/project_libs'), recursive = TRUE)
	
	}


	# Use following only when package installation fails. The symlink one tells renv to not look in 
	# the global renv library install cache located somewhere on the c drive (which may happen when working
	# from a network drive). The transactional indicates whether to install libraries first into a temp 
	# library (staging) before copying it into the actual project library. this again may cause issues if 
	# TRUE when working on network drives.
	# options(renv.config.cache.symlinks = FALSE)
	 options(renv.config.install.transactional = FALSE)
	 
}

```

With every new project I would only need to change the .Renviron file to create a different library for that project (after `RENV_PATHS_LIBRARY`). This way I can still share it with colleagues working on Windows system on network drives with just a bit of slowdown at startup.

Any tips are of course appreciated. @kevinushey You're welcome to close this issue (as the maintainer of renv).

**Comment by kevinushey** [comment] 2022-01-20 18:56
Thanks! For what it's worth, this is the solution we typically recommend if you want to use `renv` in conjunction with projects that live on (potentially slow) network drives -- if it's possible to keep your `renv` components on a local machine, then that is preferred.

I'll keep this issue open so we can consider whether the changes to activate / deactivate could still be considered.

**Comment by kevinushey** [comment] 2023-05-31 17:11
I'm on the fence about adding a `restart` parameter to `deactivate()`, as I don't want to promise to users that they can safely load / unload an renv project in a single R session and expect that to give them a "clean' session. It's sort of the moral equivalent of `rm(list = ls())` versus a session restart?

For the restart issue with the Windows network drive, I assume that's caused by the logic here:

https://github.com/rstudio/renv/blob/a02b1b28dc1b1752b005ec8fdca1426c5ba4b956/R/restart.R#L49-L59

but I think we need more information or a reprex to know for certain.

All in all, I think we'll close this as not-planned for now but we could revisit if necessary.

**Closed by kevinushey** 2023-05-31 17:11 UTC
Labels: feature, discuss :speaking_head:, activate/init/load :hiking_boot:
